#!/usr/bin/env python3
"""Generate/check M2 map-object locators from guaranteed member seed pixels."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import (
    CONTROL_H,
    CONTROL_W,
    MAP_OUT,
    ROOT,
    WORLD_H,
    WORLD_W,
    WorldModel,
    build_model,
    coastal_edges,
)

OUT = ROOT / "in_game/gfx/map/map_objects"
OVERRIDE_OUT = ROOT / "in_game/gfx/map/locators_override/locators_override.txt"
EARTH_STATIC_OBJECT_DEFINITIONS = (
    "decal_dirt_patch_01_a.txt",
    "decal_rock_clusters_01_a.txt.txt",
    "decal_rock_group_01_a.txt",
    "decal_rock_group_01_b.txt",
    "decal_rock_group_01_c.txt",
    "decal_rock_group_01_d.txt",
    "decal_rock_group_01_e.txt",
    "lakes_locators.txt",
    "new_mapobject_1.txt",
)
EARTH_OBJECT_QUARANTINE = (
    "# ENDÓRË exact-file overlay: retail Earth-authored map-object transforms "
    "are intentionally disabled.\n"
)
ACTIVE_VEGETATION_DEFINITIONS = frozenset(
    f"{family}_generator_{lod}.txt"
    for family in ("forest", "woods", "pine")
    for lod in ("high", "medium", "low")
)


def game_object_text(kind: str, keys: list[str], model: WorldModel) -> str:
    by_key = model.by_key
    lines = [
        "game_object_locator={",
        f'\tname="{kind}"',
        "\tclamp_to_water_level=no",
        "\trender_under_water=no",
        "\tgenerated_content=no",
        '\tlayer=""',
        "\tinstances={",
    ]
    for key in keys:
        location = by_key[key]
        x = (location.x + 0.5) * WORLD_W / CONTROL_W
        z = WORLD_H - (location.y + 0.5) * WORLD_H / CONTROL_H
        lines.extend(
            (
                "\t\t{",
                f"\t\t\tid={key}",
                f"\t\t\tposition={{ {x:.6f} 0.000000 {z:.6f} }}",
                "\t\t\trotation={ 0.000000 0.000000 0.000000 1.000000 }",
                "\t\t\tscale={ 1.000000 1.000000 1.000000 }",
                "\t\t}",
            )
        )
    lines.extend(("\t}", "}", ""))
    return "\n".join(lines)


def locator_payloads(model: WorldModel) -> dict[Path, str]:
    land = [location.key for location in model.locations if location.kind == "land"]
    passable = [
        location.key
        for location in model.locations
        if location.kind != "mountain"
    ]
    dock_indices = sorted(coastal_edges(model))
    dock = [model.locations[index].key for index in dock_indices]
    kinds = {
        "city": land,
        "combat": passable,
        "unit_stack": passable,
        # Live M2 evidence: vfx requires every raster location, including
        # impassable mountain locations.
        "vfx": [location.key for location in model.locations],
        "dock": dock,
        "volcano_eruption": [],
    }
    payloads = {
        OUT / f"generated_map_object_locators_{kind}.txt": game_object_text(
            kind,
            keys,
            model,
        )
        for kind, keys in kinds.items()
    }
    payloads[MAP_OUT / "generated_locators_port.txt"] = game_object_text(
        "port",
        [],
        model,
    )
    payloads[OVERRIDE_OUT] = (
        "# Generated by tools/gen_locators.py --write.\n"
        "# Vanilla coordinate overrides are invalid on the M2 Arda geometry.\n"
    )
    installed = installed_map_objects()
    generated = installed / "generated"
    for source in sorted(generated.glob("*.txt"), key=lambda item: item.name):
        if source.name in ACTIVE_VEGETATION_DEFINITIONS:
            continue
        payloads[OUT / "generated" / source.name] = EARTH_OBJECT_QUARANTINE
    for name in EARTH_STATIC_OBJECT_DEFINITIONS:
        source = installed / name
        if not source.is_file():
            raise ValueError(f"installed map-object contract lacks {name}")
        payloads[OUT / name] = EARTH_OBJECT_QUARANTINE
    return payloads


def installed_map_objects() -> Path:
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    return (
        Path(config["game_dir"])
        / "game/in_game/gfx/map/map_objects/dynamic_game_objects.txt"
    ).parent


def dynamic_text() -> str:
    source = (installed_map_objects() / "dynamic_game_objects.txt").read_text(
        encoding="utf-8-sig"
    )
    return source.split(
        'dynamic_game_object = {\n\tname = "volcano_eruption"'
    )[0]


def write() -> None:
    model = build_model()
    payloads = locator_payloads(model)
    payloads[OUT / "dynamic_game_objects.txt"] = dynamic_text()
    for path, text in payloads.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8-sig")
    print(
        "gen_locators: wrote "
        f"{len(payloads)} deterministic locator/quarantine files"
    )


def check() -> list[str]:
    model = build_model()
    payloads = locator_payloads(model)
    payloads[OUT / "dynamic_game_objects.txt"] = dynamic_text()
    failures: list[str] = []
    for path, expected in payloads.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8-sig") != expected:
            failures.append(f"{path.name} differs from deterministic locator model")
    combat = payloads[OUT / "generated_map_object_locators_combat.txt"]
    expected_instances = sum(
        location.kind != "mountain"
        for location in model.locations
    )
    if combat.count("\n\t\t{") != expected_instances:
        failures.append("combat locator completeness does not match passable map")
    generated_count = len(list((installed_map_objects() / "generated").glob("*.txt")))
    expected_quarantine_count = (
        generated_count
        - len(ACTIVE_VEGETATION_DEFINITIONS)
        + len(EARTH_STATIC_OBJECT_DEFINITIONS)
    )
    actual_quarantine_count = sum(
        payload == EARTH_OBJECT_QUARANTINE
        for payload in payloads.values()
    )
    if actual_quarantine_count != expected_quarantine_count:
        failures.append(
            "Earth map-object quarantine is incomplete: "
            f"{actual_quarantine_count} != {expected_quarantine_count}"
        )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_locators: FAIL {failure}")
        return 1
    print("gen_locators: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
