#!/usr/bin/env python3
"""Generate/check terrain-only M2 location templates."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import CONTROL, MAP_OUT, ROOT, WorldModel, build_model, coastal_edges

OUT = MAP_OUT / "location_templates.txt"
M4_CULTURES = ROOT / "docs/world/peoples/cultures.csv"


def dominant_biomes(model: WorldModel) -> np.ndarray:
    counts = np.bincount(
        (model.labels.ravel() * 11 + model.biomes.ravel()).astype(np.int64),
        minlength=len(model.locations) * 11,
    ).reshape((len(model.locations), 11))
    return np.argmax(counts, axis=1)


def mean_elevations(model: WorldModel) -> np.ndarray:
    with Image.open(CONTROL / "elevation.png") as image:
        elevation = np.asarray(image, dtype=np.float64)
    sums = np.bincount(
        model.labels.ravel(),
        weights=elevation.ravel(),
        minlength=len(model.locations),
    )
    return sums / model.areas


def climate(x: float, y: float, biome_id: int) -> str:
    if biome_id == 5 or y < 0.24:
        return "arctic"
    if biome_id == 10:
        return "arid" if y > 0.88 else "cold_arid"
    if y > 0.78:
        return "subtropical"
    if y > 0.64:
        return "mediterranean"
    if x < 0.43:
        return "oceanic"
    return "continental"


def land_terrain(biome_id: int, elevation: float) -> tuple[str, str]:
    if biome_id == 6:
        return "wetlands", "woods"
    if biome_id == 8:
        return (
            "hills_wasteland" if elevation > 9000 else "flatland_wasteland",
            "desert",
        )
    if biome_id == 10:
        return (
            "dune_wasteland" if elevation < 9000 else "hills_wasteland",
            "desert",
        )
    if biome_id == 9:
        return ("plateau" if elevation > 11000 else "flatland"), "sparse"
    if biome_id == 5:
        return ("hills" if elevation > 12000 else "flatland"), "sparse"
    if biome_id == 3:
        return ("hills" if elevation > 15000 else "flatland"), "forest"
    if biome_id == 2:
        return ("hills" if elevation > 15000 else "flatland"), "woods"
    if biome_id == 4:
        return "hills", "sparse"
    return ("hills" if elevation > 16000 else "flatland"), "grasslands"


def template_text(model: WorldModel) -> str:
    dominant = dominant_biomes(model)
    elevations = mean_elevations(model)
    coast = coastal_edges(model)
    coastal_water = {
        water
        for waters in coast.values()
        for water in waters
    }
    people = None
    if M4_CULTURES.is_file():
        from m4_peoples import assignments

        people = assignments()
    lines = [
        "# Generated by tools/gen_location_templates.py --write.",
        (
            "# M2 terrain joined to the authored M4 people/faith atlas; M5 replaces goods."
            if people is not None
            else "# M2 terrain plus engine-required placeholders; M4/M5 replace people/faith/goods."
        ),
    ]
    for location in model.locations:
        biome_id = int(dominant[location.index])
        nx, ny = location.normalized
        location_climate = climate(nx, ny, biome_id)
        fields: list[str]
        if location.kind == "sea":
            topography = "coastal_ocean" if location.index in coastal_water else "deep_ocean"
            fields = [f"topography = {topography}", f"climate = {location_climate}"]
        elif location.kind == "lake":
            fields = ["topography = lakes", f"climate = {location_climate}"]
        elif location.kind == "mountain":
            topography = (
                "mountain_wasteland"
                if biome_id in (8, 10)
                else "mountains"
            )
            vegetation = "desert" if biome_id in (8, 10) else "sparse"
            fields = [
                f"topography = {topography}",
                f"vegetation = {vegetation}",
                f"climate = {location_climate}",
            ]
        else:
            topography, vegetation = land_terrain(
                biome_id,
                float(elevations[location.index]),
            )
            culture, faith = (
                (people[location.key].culture, people[location.key].faith)
                if people is not None
                else ("swedish", "catholic")
            )
            fields = [
                f"topography = {topography}",
                f"vegetation = {vegetation}",
                f"climate = {location_climate}",
                f"religion = {faith}",
                f"culture = {culture}",
                "raw_material = wheat",
            ]
            if location.index in coast:
                suitability = 0.75 if location.anchor else 0.25
                fields.append(f"natural_harbor_suitability = {suitability:.2f}")
        lines.append(f"{location.key} = {{ {' '.join(fields)} }}")
    return "\n".join(lines) + "\n"


def write() -> None:
    model = build_model()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(template_text(model), encoding="utf-8-sig")
    print(f"gen_location_templates: wrote {len(model.locations)} terrain templates")


def check() -> list[str]:
    model = build_model()
    expected = template_text(model)
    failures: list[str] = []
    if not OUT.is_file():
        failures.append("missing in_game/map_data/location_templates.txt")
    elif OUT.read_text(encoding="utf-8-sig") != expected:
        failures.append("location_templates.txt differs from deterministic terrain model")
    if expected.count(" = { ") != len(model.locations):
        failures.append("template count is not bijective with location model")
    land_count = sum(location.kind == "land" for location in model.locations)
    if M4_CULTURES.is_file():
        if expected.count(" culture = me_") != land_count:
            failures.append("M4 culture assignments are incomplete")
        if expected.count(" religion = me_") != land_count:
            failures.append("M4 faith assignments are incomplete")
        if "culture = swedish" in expected or "religion = catholic" in expected:
            failures.append("technical M2 people/faith defaults survive M4")
    else:
        required_defaults = expected.count(
            "religion = catholic culture = swedish raw_material = wheat"
        )
        if required_defaults != land_count:
            failures.append("engine-required M2 land defaults are incomplete")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_location_templates: FAIL {failure}")
        return 1
    print("gen_location_templates: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
