#!/usr/bin/env python3
"""Generate/check the M2 continent-to-location hierarchy and map localization."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import MAP_OUT, ROOT, Location, WorldModel, build_model

DEFINITIONS_OUT = MAP_OUT / "definitions.txt"
LOCALIZATION_OUT = ROOT / "in_game/localization/english/m2_map_l_english.yml"
CONTINENT_ORDER = (
    "me_eriador",
    "me_forodwaith",
    "me_rhovanion",
    "me_gondor",
    "me_mordor_and_rhun",
    "me_harad",
)
DISPLAY_NAMES = {
    "me_eriador": "Eriador",
    "me_forodwaith": "Forodwaith",
    "me_rhovanion": "Rhovanion",
    "me_gondor": "Gondor",
    "me_mordor_and_rhun": "Mordor and Rhûn",
    "me_harad": "Harad",
    "me_forochel_region": "Forochel",
    "me_angmar_region": "Angmar",
    "me_northern_wastes_region": "Northern Wastes",
    "me_umbar_region": "Umbar",
    "me_near_harad_region": "Near Harad",
    "me_far_harad_region": "Far Harad",
    "me_rhun_region": "Rhûn",
    "me_mordor_region": "Mordor",
    "me_khand_region": "Khand",
    "me_belfalas_region": "Belfalas",
    "me_lebennin_region": "Lebennin",
    "me_ithilien_region": "Ithilien",
    "me_anorien_region": "Anórien",
    "me_south_gondor_region": "South Gondor",
    "me_grey_mountains_region": "Grey Mountains",
    "me_dale_region": "Dale and Erebor",
    "me_mirkwood_region": "Mirkwood",
    "me_rohan_region": "Rohan",
    "me_anduin_vale_region": "Vales of Anduin",
    "me_brown_lands_region": "Brown Lands",
    "me_lindon_region": "Lindon",
    "me_north_arnor_region": "North Arnor",
    "me_shire_breeland_region": "The Shire and Bree-land",
    "me_enedwaith_region": "Enedwaith",
}

# Engine-reported 32-bit localization hash collisions are remapped
# deterministically instead of accepted into the baseline. These are runtime
# facts: the source keys are otherwise valid and do not collide textually.
AREA_KEY_OVERRIDES = {
    "me_belfalas_sea_area_30_21": "me_belfalas_sea_area_30_21_arda",
    "me_khand_area_33_36": "me_khand_area_33_36_arda",
}

# Canon anchors bind the strategic hierarchy to the same source-audited frame
# used by relief and ownership. These contracts catch a broad classifier that
# still looks plausible at world scale while placing a famous site on the wrong
# side of a range or frontier.
ANCHOR_REGION_CONTRACTS = {
    "rivendell": "me_north_arnor_region",
    "moria": "me_anduin_vale_region",
    "dale": "me_dale_region",
    "erebor": "me_dale_region",
    "erech": "me_belfalas_region",
    "morannon": "me_brown_lands_region",
    "minas_morgul": "me_ithilien_region",
    "barad_dur": "me_mordor_region",
    "mount_doom": "me_mordor_region",
    "nurn_fields": "me_mordor_region",
}


def area_key(location: Location) -> str:
    stem = location.region.removesuffix("_region")
    grid_x = location.x // 82
    grid_y = location.y // 52
    # EU5 rejects an area which contains both sea zones and non-sea
    # locations.  Preserve the strategic grid while giving sea areas their
    # own identity at coastlines.  Lakes and impassable mountains follow the
    # surrounding land hierarchy, matching their non-sea engine domain.
    domain = "_sea" if location.kind == "sea" else ""
    key = f"{stem}{domain}_area_{grid_y:02d}_{grid_x:02d}"
    return AREA_KEY_OVERRIDES.get(key, key)


def hierarchy(
    model: WorldModel,
) -> dict[str, dict[str, dict[str, list[list[Location]]]]]:
    buckets: dict[
        str,
        dict[str, dict[str, list[Location]]],
    ] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for location in model.locations:
        buckets[location.continent][location.region][area_key(location)].append(location)

    result: dict[str, dict[str, dict[str, list[list[Location]]]]] = {}
    for continent in CONTINENT_ORDER:
        result[continent] = {}
        for region in sorted(buckets[continent]):
            result[continent][region] = {}
            for area in sorted(buckets[continent][region]):
                ordered = sorted(
                    buckets[continent][region][area],
                    key=lambda item: (item.y, item.x, item.key),
                )
                result[continent][region][area] = [
                    ordered[index : index + 10]
                    for index in range(0, len(ordered), 10)
                ]
    return result


def definitions_text(model: WorldModel) -> tuple[str, list[str], list[str]]:
    structure = hierarchy(model)
    lines = [
        "# Generated by tools/gen_definitions.py --write.",
        "# continent -> subcontinent -> region -> area -> province -> location",
    ]
    area_keys: list[str] = []
    province_keys: list[str] = []
    for continent in CONTINENT_ORDER:
        lines.append(f"{continent} = {{")
        lines.append(f"\t{continent}_subcontinent = {{")
        for region, areas in structure[continent].items():
            lines.append(f"\t\t{region} = {{")
            for area, provinces in areas.items():
                area_keys.append(area)
                lines.append(f"\t\t\t{area} = {{")
                for number, locations in enumerate(provinces, 1):
                    province = f"{area}_province_{number:02d}"
                    province_keys.append(province)
                    lines.append(
                        f"\t\t\t\t{province} = {{ "
                        + " ".join(location.key for location in locations)
                        + " }"
                    )
                lines.append("\t\t\t}")
            lines.append("\t\t}")
        lines.append("\t}")
        lines.append("}")
    lines.append("")
    return "\n".join(lines), area_keys, province_keys


def escape_localization(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def localization_text(model: WorldModel) -> str:
    _, area_keys, province_keys = definitions_text(model)
    location_display_names = {
        location.key: location.display_name
        for location in model.locations
    }
    if (ROOT / "docs/world/realms.csv").is_file():
        # M3 owns the final per-location gazetteer while this generator
        # remains the single writer for the map-localization database.
        from m3_realms import location_names

        location_display_names = location_names(model)
    lines = [
        "\ufeffl_english:",
        ' middle_earth: "Middle-earth"',
        ' me_arda_surface: "Lands of Middle-earth"',
        ' me_arda_surface_desc: "The varied physical lands of Middle-earth."',
    ]
    for key in CONTINENT_ORDER:
        lines.append(f' {key}: "{escape_localization(DISPLAY_NAMES[key])}"')
        lines.append(
            f' {key}_subcontinent: "{escape_localization(DISPLAY_NAMES[key])}"'
        )
    regions = sorted({location.region for location in model.locations})
    for key in regions:
        lines.append(
            f' {key}: "{escape_localization(DISPLAY_NAMES.get(key, key.replace("_", " ").title()))}"'
        )
    for key in area_keys:
        label = key.removeprefix("me_").replace("_", " ").title()
        lines.append(f' {key}: "{escape_localization(label)}"')
    for key in province_keys:
        label = key.removeprefix("me_").replace("_", " ").title()
        lines.append(f' {key}: "{escape_localization(label)}"')
    for location in model.locations:
        lines.append(
            f' {location.key}: "{escape_localization(location_display_names[location.key])}"'
        )
    return "\n".join(lines) + "\n"


def write() -> None:
    model = build_model()
    text, _, _ = definitions_text(model)
    DEFINITIONS_OUT.parent.mkdir(parents=True, exist_ok=True)
    LOCALIZATION_OUT.parent.mkdir(parents=True, exist_ok=True)
    DEFINITIONS_OUT.write_text(text, encoding="utf-8-sig")
    # localization_text includes its own BOM marker so write plain UTF-8.
    LOCALIZATION_OUT.write_text(localization_text(model), encoding="utf-8")
    print(
        f"gen_definitions: wrote {len(model.locations)} locations across "
        f"{len({item.region for item in model.locations})} regions"
    )


def check() -> list[str]:
    failures: list[str] = []
    model = build_model()
    expected_definitions, _, _ = definitions_text(model)
    expected_localization = localization_text(model)
    if not DEFINITIONS_OUT.is_file():
        failures.append("missing in_game/map_data/definitions.txt")
    elif DEFINITIONS_OUT.read_text(encoding="utf-8-sig") != expected_definitions:
        failures.append("definitions.txt differs from deterministic hierarchy")
    if not LOCALIZATION_OUT.is_file():
        failures.append("missing in_game/localization/english/m2_map_l_english.yml")
    elif LOCALIZATION_OUT.read_text(encoding="utf-8") != expected_localization:
        failures.append("m2_map_l_english.yml differs from deterministic hierarchy")

    flattened = [
        location.key
        for continents in hierarchy(model).values()
        for areas in continents.values()
        for provinces in areas.values()
        for province in provinces
        for location in province
    ]
    if len(flattened) != len(set(flattened)):
        failures.append("hierarchy repeats one or more locations")
    if set(flattened) != {location.key for location in model.locations}:
        failures.append("hierarchy is not bijective with the location model")
    for key, expected_region in ANCHOR_REGION_CONTRACTS.items():
        location = model.by_key.get(key)
        if location is None:
            failures.append(f"hierarchy lost canonical anchor {key}")
        elif location.region != expected_region:
            failures.append(
                f"canonical anchor {key} is in {location.region}, "
                f"expected {expected_region}"
            )
    for continent in hierarchy(model).values():
        for areas in continent.values():
            for area, provinces in areas.items():
                kinds = {
                    location.kind
                    for province in provinces
                    for location in province
                }
                if "sea" in kinds and len(kinds) > 1:
                    failures.append(
                        f"{area} mixes sea and non-sea locations"
                    )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_definitions: FAIL {failure}")
        return 1
    print("gen_definitions: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
