#!/usr/bin/env python3
"""Generate/check M2 location geometry and its RGB registry."""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import (
    CONTROL_H,
    CONTROL_W,
    DERIVED,
    MAP_OUT,
    WORLD_H,
    WORLD_W,
    WorldModel,
    build_model,
    installed_named_registry,
    model_manifest,
    save_json,
)

NAMED_OUT = MAP_OUT / "named_locations/00_default.txt"
MANIFEST_OUT = DERIVED / "world_manifest.json"
INDEX_OUT = DERIVED / "location_index.csv"
PREVIEW_OUT = DERIVED / "location_preview.png"

PREVIEW_COLORS = {
    0: (38, 73, 96),
    1: (126, 145, 95),
    2: (68, 113, 69),
    3: (37, 79, 52),
    4: (126, 124, 117),
    5: (167, 177, 170),
    6: (81, 108, 88),
    7: (52, 98, 128),
    8: (89, 69, 60),
    9: (146, 137, 82),
    10: (172, 141, 91),
}


def named_text(model: WorldModel) -> str:
    vanilla_text, vanilla_names, _ = installed_named_registry()
    collisions = sorted(
        location.key
        for location in model.locations
        if location.key in vanilla_names
    )
    if collisions:
        raise ValueError(f"custom location keys collide with vanilla registry: {collisions}")
    lines = [
        vanilla_text.rstrip(),
        "",
        "# Generated by tools/gen_locations.py --write.",
        "# ENDÓRË colors are exact, unique, and disjoint from vanilla.",
    ]
    lines.extend(
        f"{location.key} = {location.color[0]:02x}{location.color[1]:02x}{location.color[2]:02x}"
        for location in model.locations
    )
    return "\n".join(lines) + "\n"


def index_text(model: WorldModel) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        (
            "index",
            "key",
            "display_name",
            "kind",
            "control_x",
            "control_y",
            "normalized_x",
            "normalized_y",
            "control_area",
            "biome_id",
            "continent",
            "region",
            "rgb",
            "anchor",
        )
    )
    for location in model.locations:
        nx, ny = location.normalized
        writer.writerow(
            (
                location.index,
                location.key,
                location.display_name,
                location.kind,
                location.x,
                location.y,
                f"{nx:.7f}",
                f"{ny:.7f}",
                int(model.areas[location.index]),
                location.biome_id,
                location.continent,
                location.region,
                "".join(f"{value:02x}" for value in location.color),
                "yes" if location.anchor else "no",
            )
        )
    return output.getvalue()


def coarse_rgb(model: WorldModel) -> np.ndarray:
    palette = np.asarray(
        [location.color for location in model.locations],
        dtype=np.uint8,
    )
    return palette[model.labels]


def preview_image(model: WorldModel) -> Image.Image:
    array = np.zeros((CONTROL_H, CONTROL_W, 3), dtype=np.uint8)
    for biome_id, color in PREVIEW_COLORS.items():
        array[model.biomes == biome_id] = color
    boundary = np.zeros(model.labels.shape, dtype=bool)
    boundary[:, 1:] |= model.labels[:, 1:] != model.labels[:, :-1]
    boundary[1:, :] |= model.labels[1:, :] != model.labels[:-1, :]
    array[boundary] = (43, 39, 34)
    image = Image.fromarray(array, "RGB")
    draw = ImageDraw.Draw(image)
    for location in model.locations:
        if not location.anchor:
            continue
        radius = 3
        draw.ellipse(
            (
                location.x - radius,
                location.y - radius,
                location.x + radius,
                location.y + radius,
            ),
            fill=(214, 176, 81),
            outline=(34, 28, 23),
        )
    return image


def write() -> None:
    model = build_model()
    MAP_OUT.mkdir(parents=True, exist_ok=True)
    NAMED_OUT.parent.mkdir(parents=True, exist_ok=True)
    DERIVED.mkdir(parents=True, exist_ok=True)

    full = Image.fromarray(coarse_rgb(model), "RGB").resize(
        (WORLD_W, WORLD_H),
        Image.Resampling.NEAREST,
    )
    full.save(MAP_OUT / "locations.png", compress_level=9)
    NAMED_OUT.write_text(named_text(model), encoding="utf-8-sig")
    INDEX_OUT.write_text(index_text(model), encoding="utf-8-sig")
    preview_image(model).save(PREVIEW_OUT, compress_level=9)
    manifest = model_manifest(model)
    save_json(MANIFEST_OUT, manifest)
    save_json(MAP_OUT / "m2_manifest.json", manifest)
    print(json.dumps(manifest, indent=2, ensure_ascii=False))


def check() -> list[str]:
    failures: list[str] = []
    model = build_model()
    expected_manifest = model_manifest(model)
    for path in (MANIFEST_OUT, MAP_OUT / "m2_manifest.json"):
        if not path.is_file():
            failures.append(f"missing {path.relative_to(MAP_OUT.parent.parent)}")
        else:
            actual = json.loads(path.read_text(encoding="utf-8-sig"))
            if actual != expected_manifest:
                failures.append(f"{path.name} differs from deterministic world model")

    expected_text = {
        NAMED_OUT: named_text(model),
        INDEX_OUT: index_text(model),
    }
    for path, expected in expected_text.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(MAP_OUT.parent.parent)}")
        elif path.read_text(encoding="utf-8-sig") != expected:
            failures.append(f"{path.name} differs from deterministic world model")

    locations_path = MAP_OUT / "locations.png"
    if not locations_path.is_file():
        failures.append("missing in_game/map_data/locations.png")
    else:
        with Image.open(locations_path) as image:
            if image.mode != "RGB" or image.size != (WORLD_W, WORLD_H):
                failures.append(
                    f"locations.png is {image.mode} {image.size}, expected RGB {(WORLD_W, WORLD_H)}"
                )
            else:
                sampled = np.asarray(
                    image.resize((CONTROL_W, CONTROL_H), Image.Resampling.NEAREST)
                )
                if not np.array_equal(sampled, coarse_rgb(model)):
                    failures.append("locations.png pixels differ from deterministic world model")
                colors = image.getcolors(maxcolors=len(model.locations) + 1)
                if colors is None or len(colors) != len(model.locations):
                    failures.append("locations.png color count is not bijective with registry")

    expected_preview = preview_image(model)
    if not PREVIEW_OUT.is_file():
        failures.append("missing docs/world/derived/location_preview.png")
    else:
        with Image.open(PREVIEW_OUT) as actual_preview:
            if (
                actual_preview.mode != expected_preview.mode
                or actual_preview.size != expected_preview.size
                or not np.array_equal(
                    np.asarray(actual_preview),
                    np.asarray(expected_preview),
                )
            ):
                failures.append("location_preview.png differs from deterministic world model")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_locations: FAIL {failure}")
        return 1
    print("gen_locations: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
