#!/usr/bin/env python3
"""Generate/check terrain-only M2 location templates."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import (
    CONTROL,
    MAP_OUT,
    ROOT,
    WorldModel,
    build_model,
    coastal_edges,
    effective_template_biomes,
    location_biome_counts,
)

OUT = MAP_OUT / "location_templates.txt"
M4_CULTURES = ROOT / "docs/world/peoples/cultures.csv"
M5_CENSUS = ROOT / "docs/world/economy/realm_census.csv"


def mean_elevations(model: WorldModel) -> np.ndarray:
    with Image.open(CONTROL / "elevation.png") as image:
        elevation = np.asarray(image, dtype=np.float64)
    sums = np.bincount(
        model.labels.ravel(),
        weights=elevation.ravel(),
        minlength=len(model.locations),
    )
    return sums / model.areas


def climate(x: float, y: float, biome_id: int, kind: str) -> str:
    # EU5 resolves terrain biomes from location-scoped climate, topography,
    # and vegetation. Varying any of those values across 12,104 generated
    # locations repaints the continuous terrain cache as visible cell islands.
    # Seasonal/latitudinal appearance is authored in the Arda-native material
    # cache instead, so every playable land cell uses one neutral climate.
    return "me_arda_surface" if kind in {"land", "mountain"} else "continental"


def land_terrain(biome_id: int, elevation: float) -> tuple[str, str]:
    # Height, terrain-cache materials, rivers, and object transforms are all
    # continuous authored rasters. Keep the renderer's location template
    # neutral so forest, desert, marsh, tundra, and foothill transitions follow
    # those rasters instead of exposing generated cell boundaries.
    return "flatland", "grasslands"


def template_text(model: WorldModel) -> str:
    counts = location_biome_counts(model)
    dominant = effective_template_biomes(model, counts)
    elevations = mean_elevations(model)
    coast = coastal_edges(model)
    people = None
    goods = None
    if M4_CULTURES.is_file():
        from m4_peoples import assignments

        people = assignments()
    if M5_CENSUS.is_file():
        from m5_census import raw_materials

        goods = raw_materials()
    lines = [
        "# Generated by tools/gen_location_templates.py --write.",
        (
            "# M2 terrain joined to the authored M4 people/faith atlas and M5 economy."
            if goods is not None
            else "# M2 terrain joined to the authored M4 people/faith atlas; M5 replaces goods."
            if people is not None
            else "# M2 terrain plus engine-required placeholders; M4/M5 replace people/faith/goods."
        ),
    ]
    for location in model.locations:
        biome_id = int(dominant[location.index])
        nx, ny = location.normalized
        location_climate = climate(nx, ny, biome_id, location.kind)
        fields: list[str]
        if location.kind == "sea":
            # Shore materials and bathymetry are continuous in the authored
            # cache. A coastal/deep switch per sea cell otherwise exposes the
            # sparse sea tessellation as large polygons.
            fields = ["topography = deep_ocean", f"climate = {location_climate}"]
        elif location.kind == "lake":
            fields = ["topography = lakes", f"climate = {location_climate}"]
        elif location.kind == "mountain":
            # Passability is owned independently by default.map's explicit
            # ``impassable_mountains`` section. A mountain_wasteland template
            # repaints each generated crest location as a giant grey/white
            # polygon, hiding the continuous source relief beneath it. Keep
            # the renderer neutral here: the q64 heightfield and semantic
            # material cache still provide rock, snow, and volcanic ground.
            topography = "flatland"
            vegetation = "grasslands"
            fields = [
                f"topography = {topography}",
                f"vegetation = {vegetation}",
                f"climate = {location_climate}",
            ]
        else:
            topography, vegetation = land_terrain(
                biome_id,
                float(elevations[location.index]),
            )
            culture, faith = (
                (people[location.key].culture, people[location.key].faith)
                if people is not None
                else ("swedish", "catholic")
            )
            fields = [
                f"topography = {topography}",
                f"vegetation = {vegetation}",
                f"climate = {location_climate}",
                f"religion = {faith}",
                f"culture = {culture}",
                f"raw_material = {goods[location.key] if goods is not None else 'wheat'}",
            ]
            if location.index in coast:
                suitability = 0.75 if location.anchor else 0.25
                fields.append(f"natural_harbor_suitability = {suitability:.2f}")
        lines.append(f"{location.key} = {{ {' '.join(fields)} }}")
    return "\n".join(lines) + "\n"


def write() -> None:
    model = build_model()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(template_text(model), encoding="utf-8-sig")
    print(f"gen_location_templates: wrote {len(model.locations)} terrain templates")


def check() -> list[str]:
    model = build_model()
    expected = template_text(model)
    failures: list[str] = []
    if not OUT.is_file():
        failures.append("missing in_game/map_data/location_templates.txt")
    elif OUT.read_text(encoding="utf-8-sig") != expected:
        failures.append("location_templates.txt differs from deterministic terrain model")
    if expected.count(" = { ") != len(model.locations):
        failures.append("template count is not bijective with location model")
    land_count = sum(location.kind == "land" for location in model.locations)
    rendered_land_count = sum(
        location.kind in {"land", "mountain"} for location in model.locations
    )
    if expected.count("climate = me_arda_surface") != rendered_land_count:
        failures.append("continuous rendering climate does not cover every land cell")
    mountain_count = sum(
        location.kind == "mountain" for location in model.locations
    )
    neutral_mountain_template = (
        "topography = flatland vegetation = grasslands "
        "climate = me_arda_surface }"
    )
    if expected.count(neutral_mountain_template) != mountain_count:
        failures.append("impassable mountain renderer templates are not neutral")
    if "mountain_wasteland" in expected:
        failures.append("cell-shaped mountain_wasteland rendering survives")
    if M4_CULTURES.is_file():
        if expected.count(" culture = me_") != land_count:
            failures.append("M4 culture assignments are incomplete")
        if expected.count(" religion = me_") != land_count:
            failures.append("M4 faith assignments are incomplete")
        if "culture = swedish" in expected or "religion = catholic" in expected:
            failures.append("technical M2 people/faith defaults survive M4")
    else:
        required_defaults = expected.count(
            "religion = catholic culture = swedish raw_material = wheat"
        )
        if required_defaults != land_count:
            failures.append("engine-required M2 land defaults are incomplete")
    if M5_CENSUS.is_file():
        if expected.count(" raw_material = ") != land_count:
            failures.append("M5 raw-material assignments are incomplete")
        if expected.count("raw_material = wheat") == land_count:
            failures.append("M5 raw-material map did not replace the M2 monoculture")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_location_templates: FAIL {failure}")
        return 1
    print("gen_location_templates: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
