#!/usr/bin/env python3
"""Generate/check the M2 default.map classification contract."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import MAP_OUT, build_model

OUT = MAP_OUT / "default.map"


def wrapped_section(name: str, keys: list[str], width: int = 8) -> list[str]:
    lines = [f"{name} = {{"]
    for index in range(0, len(keys), width):
        lines.append("\t" + " ".join(keys[index : index + width]))
    lines.append("}")
    return lines


def config_text() -> str:
    model = build_model()
    kinds = {
        kind: [location.key for location in model.locations if location.kind == kind]
        for kind in ("sea", "lake", "mountain")
    }
    lines = [
        '# Generated by tools/gen_map_config.py --write.',
        'provinces = "locations.png"',
        'rivers = "rivers.png"',
        'topology = "heightmap.heightmap"',
        'adjacencies = "adjacencies.csv"',
        'setup = "definitions.txt"',
        'ports = "ports.csv"',
        'location_templates = "location_templates.txt"',
        "",
        "# The physical equator lies south of this north-western Middle-earth extent.",
        "equator_y = 4600",
        "wrap_x = no",
        "",
        "sound_toll = {",
        "}",
        "volcanoes = {",
        "}",
        "earthquakes = {",
        "}",
        "",
    ]
    lines.extend(wrapped_section("sea_zones", kinds["sea"]))
    lines.append("")
    lines.extend(wrapped_section("lakes", kinds["lake"]))
    lines.append("")
    lines.extend(wrapped_section("impassable_mountains", kinds["mountain"]))
    lines.extend(
        (
            "",
            "non_ownable = {",
            "}",
            "",
        )
    )
    return "\n".join(lines)


def write() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(config_text(), encoding="utf-8-sig")
    print("gen_map_config: wrote no-wrap M2 map classifications")


def check() -> list[str]:
    failures: list[str] = []
    expected = config_text()
    if not OUT.is_file():
        failures.append("missing in_game/map_data/default.map")
    elif OUT.read_text(encoding="utf-8-sig") != expected:
        failures.append("default.map differs from deterministic classifications")
    if "wrap_x = no" not in expected:
        failures.append("default.map does not disable horizontal wrapping")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_map_config: FAIL {failure}")
        return 1
    print("gen_map_config: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
