#!/usr/bin/env python3
"""Generate/check Arda-native close-zoom vegetation transforms.

EU5 generated map-object bins are headerless arrays of ten little-endian
floats: position xyz, quaternion xyzw, and scale xyz. The installed meshes and
LOD layer names are reused exactly; every placement is generated only from
ENDÓRË's authored biome controls.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import struct
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import CONTROL, CONTROL_H, CONTROL_W, ROOT, WORLD_H, WORLD_W

OUT = ROOT / "in_game/gfx/map/map_objects"
GENERATED = OUT / "generated"
RECORD = struct.Struct("<10f")
GENERATOR_VERSION = 2


@dataclass(frozen=True)
class Family:
    key: str
    biome_ids: tuple[int, ...]
    y_max: float
    meshes: tuple[str, ...]
    counts: tuple[int, int, int]
    scale: tuple[float, float]


FAMILIES = (
    Family(
        "forest",
        (3,),
        1.0,
        (
            "vegetation_diorama_tree_single_mesh",
            "vegetation_diorama_tree_single1_mesh",
            "vegetation_diorama_tree_single2_mesh",
            "vegetation_diorama_tree_single3_mesh",
        ),
        (120_000, 60_000, 30_000),
        (0.72, 0.92),
    ),
    Family(
        "woods",
        (2, 6),
        1.0,
        (
            "vegetation_diorama_tree_single_mesh",
            "vegetation_diorama_tree_single1_mesh",
            "vegetation_diorama_tree_single2_mesh",
            "vegetation_diorama_tree_single3_mesh",
        ),
        (64_000, 32_000, 16_000),
        (0.68, 0.88),
    ),
    Family(
        "pine",
        (2, 3, 5),
        0.36,
        (
            "vegetation_diorama_arctic_tree_mesh",
            "vegetation_diorama_arctic_tree2_mesh",
            "vegetation_diorama_arctic_tree3_mesh",
            "vegetation_diorama_arctic_tree4_mesh",
        ),
        (56_000, 28_000, 14_000),
        (0.70, 0.86),
    ),
)
LODS = ("high", "medium", "low")


def seed(*parts: str) -> int:
    payload = "|".join(("ENDORE", str(GENERATOR_VERSION), *parts, "3018"))
    return int.from_bytes(hashlib.sha256(payload.encode("utf-8")).digest()[:8], "little")


def controls() -> tuple[np.ndarray, np.ndarray]:
    with Image.open(CONTROL / "biomes.png") as image:
        biomes = np.asarray(image, dtype=np.uint8)
    with Image.open(CONTROL / "density.png") as image:
        density = np.asarray(image, dtype=np.uint8)
    if biomes.shape != (CONTROL_H, CONTROL_W):
        raise ValueError("vegetation source has the wrong control resolution")
    return biomes, density


def eligible_cells(family: Family, biomes: np.ndarray) -> np.ndarray:
    mask = np.isin(biomes, family.biome_ids)
    if family.y_max < 1.0:
        mask[round(family.y_max * CONTROL_H) :, :] = False
    cells = np.argwhere(mask)
    if not len(cells):
        raise ValueError(f"{family.key} has no eligible authored cells")
    return cells


def transforms(
    family: Family,
    lod: str,
    count: int,
    biomes: np.ndarray,
    density: np.ndarray,
) -> tuple[bytes, ...]:
    rng = np.random.default_rng(seed(family.key, lod))
    cells = eligible_cells(family, biomes)
    weights = density[cells[:, 0], cells[:, 1]].astype(np.float64)
    weights = np.square(np.clip(weights / 255.0, 0.18, 1.0))
    choices = rng.choice(len(cells), size=count, replace=True, p=weights / weights.sum())
    selected = cells[choices]
    # Random position inside its authored control cell; source Y is inverted
    # to EU5's world-space Z, matching generated locators.
    x = (selected[:, 1] + rng.random(count)) * WORLD_W / CONTROL_W
    z = WORLD_H - (selected[:, 0] + rng.random(count)) * WORLD_H / CONTROL_H
    yaw = rng.uniform(0.0, 2.0 * math.pi, count)
    scale = rng.uniform(family.scale[0], family.scale[1], count)
    variants = rng.integers(0, len(family.meshes), count)
    payloads = [bytearray() for _ in family.meshes]
    for index in range(count):
        half = yaw[index] * 0.5
        value = RECORD.pack(
            float(x[index]),
            0.0,
            float(z[index]),
            0.0,
            float(math.sin(half)),
            0.0,
            float(math.cos(half)),
            float(scale[index]),
            float(scale[index]),
            float(scale[index]),
        )
        payloads[int(variants[index])].extend(value)
    return tuple(bytes(payload) for payload in payloads)


def definition_text(family: Family, lod: str) -> str:
    lines = [
        "# Generated by tools/gen_map_objects.py --write.",
        "# Vanilla EU5 meshes and LOD layers; ENDÓRË-authored transforms only.",
    ]
    for index, mesh in enumerate(family.meshes):
        # The renderer keys these generated layers by the installed object
        # name as well as by their exact definition filename. Keep the object
        # ABI exact while redirecting only its transform payload to Arda.
        object_name = f"{family.key}_generator_{lod}_{index}"
        transform_name = object_name
        lines.extend(
            (
                "object={",
                f'\tname="{object_name}"',
                "\tclamp_to_water_level=no",
                "\trender_under_water=no",
                "\tgenerated_content=yes",
                f'\tlayer="vegetation_{lod}"',
                f'\tpdxmesh="{mesh}"',
                f'\ttransform_bin_file="gfx/map/map_objects/{transform_name}.bin"',
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def payloads() -> dict[Path, bytes]:
    biomes, density = controls()
    result: dict[Path, bytes] = {}
    for family in FAMILIES:
        for lod_index, lod in enumerate(LODS):
            # EU5's renderer discovers these generated layers by the exact
            # retail definition filename. Arbitrary sibling definitions parse
            # without an error but are not activated by the map-object system.
            result[GENERATED / f"{family.key}_generator_{lod}.txt"] = (
                definition_text(family, lod).encode("utf-8")
            )
            bins = transforms(
                family,
                lod,
                family.counts[lod_index],
                biomes,
                density,
            )
            for index, data in enumerate(bins):
                result[
                    OUT / f"{family.key}_generator_{lod}_{index}.bin"
                ] = data
    return result


def write() -> None:
    expected = payloads()
    for path, data in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    expected_names = {path.name for path in expected}
    for directory, pattern in (
        (GENERATED, "endore_*.txt"),
        (OUT, "endore_*.bin"),
    ):
        for path in directory.glob(pattern):
            if path.name not in expected_names:
                path.unlink()
    records = sum(
        len(data) // RECORD.size
        for path, data in expected.items()
        if path.suffix == ".bin"
    )
    total_bytes = sum(len(data) for data in expected.values())
    print(
        "gen_map_objects: wrote "
        f"{records:,} Arda-native vegetation transforms "
        f"({total_bytes / 1_000_000:.1f} MB)"
    )


def check() -> list[str]:
    failures: list[str] = []
    expected = payloads()
    for path, data in expected.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_bytes() != data:
            failures.append(f"{path.name} differs from authored vegetation model")
    expected_names = {path.name for path in expected}
    stale = [
        path.name
        for directory in (OUT, GENERATED)
        for path in directory.glob("endore_*")
        if path.name not in expected_names
    ]
    if stale:
        failures.append(f"stale ENDÓRË vegetation outputs: {', '.join(sorted(stale))}")
    definition_count = sum(path.suffix == ".txt" for path in expected)
    bin_count = sum(path.suffix == ".bin" for path in expected)
    if definition_count != 9 or bin_count != 36:
        failures.append("vegetation output family/LOD contract is incomplete")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"gen_map_objects: FAIL {failure}")
        return 1
    print("gen_map_objects: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
