#!/usr/bin/env python3
"""Generate/check the M2 vanilla geography-reference quarantine sweep."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_definitions import hierarchy
from worldgen import MAP_OUT, ROOT, build_model, game_map

M1_MARKER = "# Generated M1 geography compatibility overlay; replaced wholesale by M2.\n"
M2_MARKER = "# Generated by tools/m2_quarantine.py --write; M2 geography quarantine.\n"
MANIFEST = MAP_OUT / "m2_script_overlay_manifest.json"
OLD_MANIFEST = MAP_OUT / "m1_script_overlay_manifest.json"
UNUSED_EARTH_STATIC_MODIFIERS = frozenset(
    {
        "sbl_heir_of_empty_coat",
        "is_byz_john_kantakouzenos",
        "is_tim_timur",
        "is_lbv_heinrich_xiv_wittelsbach",
        "chi_administration_in_disarray",
        "chi_yuan_religious_stability",
        "falun_base",
        "golconda_base",
        "almaden_base",
        "huancavelica_base",
        "idrija_base",
        "lanmuchang_base",
        "potosi_base",
        "zacatecas_base",
        "guanajuato_base",
        "spice_islands_base",
        "nile_delta_rice_base",
        "nile_delta_wheat_base",
        "nile_delta_sugar_base",
        "nile_delta_cotton_base",
        "nile_delta_legumes_base",
        "nile_delta_fiber_crops_base",
        "nile_delta_fruit_base",
        "coffee_yemen_base",
        "sahara_salt_mines_base",
        "sikar_copper_mines_base",
        "nishapur_gems_mines_base",
        "panjshir_valley_silver_mines_base",
        "turda_salt_mines_base",
        "kutna_hora_silver_mines_base",
        "rammelsberg_silver_mines_base",
        "mali_gold_mines_base",
        "kremnica_gold_mines",
        "srebrenica_silver_mines_base",
        "newfoundland_fishing_grounds_base",
        "amber_coast_base",
        "sicily_sulfur_mines",
        "damascus_base",
        "flanders_fine_cloth_base",
        "tuscany_fine_cloth_base",
        "venice_glass_base",
        "toledo_weaponry_base",
        "bilbao_iron_base",
        "milan_weaponry_base",
        "yorkshire_cloth_base",
        "england_wool_base",
        "bengal_cotton_base",
        "gujarat_cotton_base",
        "better_morale",
    }
)


def strip_comments(text: str) -> str:
    return re.sub(r"#.*", "", text)


def hierarchy_keys(text: str) -> list[list[str]]:
    levels: list[list[str]] = [[] for _ in range(5)]
    depth = 0
    token_re = re.compile(r"([A-Za-z0-9_]+)\s*=\s*\{|\}")
    for match in token_re.finditer(strip_comments(text)):
        key = match.group(1)
        if key is not None:
            if depth < len(levels):
                levels[depth].append(key)
            depth += 1
        else:
            depth -= 1
    if depth:
        raise ValueError(f"installed definitions end at brace depth {depth}")
    return levels


def standin_path() -> tuple[str, str, str, str, str, str]:
    model = build_model()
    target = model.by_key["minas_tirith"]
    structure = hierarchy(model)
    for continent, regions in structure.items():
        for region, areas in regions.items():
            for area, provinces in areas.items():
                for number, province in enumerate(provinces, 1):
                    if any(location.key == target.key for location in province):
                        return (
                            continent,
                            f"{continent}_subcontinent",
                            region,
                            area,
                            f"{area}_province_{number:02d}",
                            target.key,
                        )
    raise ValueError("Minas Tirith is absent from generated hierarchy")


def installed_game() -> Path:
    return game_map().parents[1]


def replacement_map() -> dict[str, str]:
    definitions = (game_map() / "definitions.txt").read_text(encoding="utf-8-sig")
    standins = standin_path()[:5]
    replacements: dict[str, str] = {}
    for depth, keys in enumerate(hierarchy_keys(definitions)):
        for key in keys:
            replacements.setdefault(key, standins[depth])
    # Installed evidence: these two legal keys occur at more than one depth.
    replacements["eastern_baltic_sea"] = standins[3]
    replacements["limousin_province"] = standins[4]
    return replacements


def scripted_geography_rewrite(text: str) -> str:
    blocks = (
        ("location", standin_path()[5]),
        ("province_definition", standin_path()[4]),
        ("area", standin_path()[3]),
        ("region", standin_path()[2]),
        ("subcontinent", standin_path()[1]),
        ("continent", standin_path()[0]),
    )
    for block_name, standin in blocks:
        text = re.sub(
            rf"(?ms)(^\s*{block_name}\s*=\s*\{{\s*$).*?(^\s*\}}\s*$)",
            rf"\1\n\t\t{standin}\n\2",
            text,
        )
    return text


def disable_named_blocks(text: str, name: str) -> str:
    """Disable named schedule blocks while respecting nesting and comments."""
    header = re.compile(
        rf"(?m)^[ \t]*{re.escape(name)}\s*=\s*\{{"
    )
    cursor = 0
    result: list[str] = []
    while True:
        match = header.search(text, cursor)
        if match is None:
            result.append(text[cursor:])
            return "".join(result)
        result.append(text[cursor:match.start()])
        indent = re.match(r"[ \t]*", match.group(0)).group(0)
        depth = 1
        quoted = False
        escaped = False
        commented = False
        index = match.end()
        while index < len(text) and depth:
            character = text[index]
            if commented:
                if character in "\r\n":
                    commented = False
            elif escaped:
                escaped = False
            elif quoted and character == "\\":
                escaped = True
            elif character == '"':
                quoted = not quoted
            elif not quoted and character == "#":
                commented = True
            elif not quoted and character == "{":
                depth += 1
            elif not quoted and character == "}":
                depth -= 1
            index += 1
        if depth:
            raise ValueError(f"unterminated {name} block")
        result.append(
            f"{indent}{name} = {{\n"
            f"{indent}\ttag = SWE\n"
            f"{indent}\tfrom = 9999.1.1\n"
            f"{indent}\tto = 9999.1.2\n"
            f"{indent}\tmonthly_chance = 0\n"
            f"{indent}}}"
        )
        cursor = index


def disable_predicate_blocks(text: str, name: str) -> str:
    """Replace named trigger blocks with an unconditional false predicate."""
    header = re.compile(
        rf"(?m)^[ \t]*{re.escape(name)}\s*=\s*\{{"
    )
    cursor = 0
    result: list[str] = []
    while True:
        match = header.search(text, cursor)
        if match is None:
            result.append(text[cursor:])
            return "".join(result)
        result.append(text[cursor:match.start()])
        indent = re.match(r"[ \t]*", match.group(0)).group(0)
        depth = 1
        quoted = False
        escaped = False
        commented = False
        index = match.end()
        while index < len(text) and depth:
            character = text[index]
            if commented:
                if character in "\r\n":
                    commented = False
            elif escaped:
                escaped = False
            elif quoted and character == "\\":
                escaped = True
            elif character == '"':
                quoted = not quoted
            elif not quoted and character == "#":
                commented = True
            elif not quoted and character == "{":
                depth += 1
            elif not quoted and character == "}":
                depth -= 1
            index += 1
        if depth:
            raise ValueError(f"unterminated {name} block")
        result.append(
            f"{indent}{name} = {{\n"
            f"{indent}\talways = no\n"
            f"{indent}}}"
        )
        cursor = index


def remove_named_blocks(text: str, names: frozenset[str]) -> str:
    """Remove exact top-level database blocks and preserve all other entries."""
    header = re.compile(
        rf"(?m)^[ \t]*(?:{'|'.join(re.escape(name) for name in sorted(names))})"
        r"\s*=\s*\{"
    )
    cursor = 0
    result: list[str] = []
    while True:
        match = header.search(text, cursor)
        if match is None:
            result.append(text[cursor:])
            return "".join(result)
        result.append(text[cursor:match.start()])
        depth = 1
        quoted = False
        escaped = False
        commented = False
        index = match.end()
        while index < len(text) and depth:
            character = text[index]
            if commented:
                if character in "\r\n":
                    commented = False
            elif escaped:
                escaped = False
            elif quoted and character == "\\":
                escaped = True
            elif character == '"':
                quoted = not quoted
            elif not quoted and character == "#":
                commented = True
            elif not quoted and character == "{":
                depth += 1
            elif not quoted and character == "}":
                depth -= 1
            index += 1
        if depth:
            raise ValueError("unterminated static modifier block")
        while index < len(text) and text[index] in " \t":
            index += 1
        if index < len(text) and text[index] == "\r":
            index += 1
        if index < len(text) and text[index] == "\n":
            index += 1
        cursor = index


def flag_definition_rewrite(text: str) -> str:
    """Keep flag-rule consumers while guarding predicates invalid during setup."""
    # The predicates above live in the scripted-trigger file; this function is
    # also applied there. Capital-based flag variants can be evaluated while a
    # setup country still has no valid capital, so disable only those variants.
    text = re.sub(
        r"\bgovernment_type\s*=\s*government_type:[A-Za-z0-9_]+",
        "always = no",
        text,
    )
    text = re.sub(
        r"(?m)^(\s*)capital\s*=\s*location:[A-Za-z0-9_]+\s*$",
        r"\1always = no",
        text,
    )
    return text


def hardcoded_on_action_rewrite(text: str) -> str:
    """Guard retail setup scopes which are intentionally absent from M2."""
    text = re.sub(
        (
            r"(?m)^(\s*)"
            r"(c:(?!SWE\b)[A-Z0-9_]+|"
            r"international_organization:(?:catholic_church|shinto))"
            r"\s*=\s*\{"
        ),
        r"\1\2 ?= {",
        text,
    )
    text = re.sub(
        r"\bthis\s*=\s*c:(?!SWE\b)[A-Z0-9_]+",
        "always = no",
        text,
    )
    text = re.sub(
        (
            r"(?m)^\s*"
            r"(?:china|majapahit|japan|byz|ver)_set_up\s*=\s*yes\s*$"
        ),
        "",
        text,
    )
    text = re.sub(
        (
            r"(?m)^\s*add_country_to_international_organization"
            r"(?:_no_update)?\s*=\s*[A-Za-z0-9_:]+\s*$"
        ),
        "",
        text,
    )
    return text


def expected_overlays() -> dict[str, str]:
    # Runtime/scenario neutralizers own their exact files and take precedence
    # over generic token substitution.
    from m2_runtime import payloads as runtime_payloads

    runtime_owned = {
        path.relative_to(ROOT).as_posix()
        for path in runtime_payloads()
    }
    realms = ROOT / "docs/world/realms.csv"
    if realms.is_file():
        from m3_realms import owned_paths as m3_owned_paths

        runtime_owned.update(
            path.relative_to(ROOT).as_posix()
            for path in m3_owned_paths()
        )
    m4_cultures = ROOT / "docs/world/peoples/cultures.csv"
    if m4_cultures.is_file():
        from m4_peoples import owned_paths as m4_owned_paths

        runtime_owned.update(
            path.relative_to(ROOT).as_posix()
            for path in m4_owned_paths()
        )
    replacements = replacement_map()
    token_re = re.compile(r"\b[A-Za-z0-9_]+\b")
    geography_namespaces = {
        "location",
        "province_definition",
        "province",
        "area",
        "region",
        "subcontinent",
        "sub_continent",
        "continent",
    }
    protected_fields = {
        "culture_definition",
        "religion_definition",
        "culture",
        "religion",
        "language",
        "goods",
        "character",
        "dynasty",
        "tag",
        "modifier",
        "type",
        "id",
        "name",
        "text",
        "description_category",
        "color",
        "color2",
    }
    typed_scope_re = re.compile(
        (
            r"\b(location|province_definition|province|area|region|"
            r"subcontinent|sub_continent|continent)"
            r":([A-Za-z0-9_]+)"
        )
    )
    geography_field_re = re.compile(
        (
            r"\b(location|province_definition|province|area|region|"
            r"subcontinent|sub_continent|continent|"
            r"capital|birth_location)\s*=\s*([A-Za-z0-9_]+)"
        )
    )
    payloads: dict[str, str] = {}
    game = installed_game()
    for tree in ("in_game", "main_menu", "loading_screen"):
        installed_tree = game / tree
        for source_path in sorted(installed_tree.rglob("*.txt")):
            relative_in_tree = source_path.relative_to(installed_tree).as_posix()
            if tree == "in_game" and relative_in_tree.startswith("map_data/"):
                continue
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/cultures/")
            ):
                # Culture keys can legally collide with geography keys. A
                # global token substitution would rename the database entry.
                continue
            if tree == "loading_screen" and relative_in_tree.startswith("sound/"):
                continue
            relative = f"{tree}/{relative_in_tree}"
            if relative in runtime_owned:
                continue
            source = source_path.read_text(encoding="utf-8-sig", errors="strict")
            def replace_token(match: re.Match[str]) -> str:
                token = match.group(0)
                replacement = replacements.get(token)
                if replacement is None:
                    return token
                line_start = source.rfind("\n", 0, match.start()) + 1
                prefix = source[line_start:match.start()]
                namespace = re.search(r"([A-Za-z0-9_]+):\s*$", prefix)
                if (
                    namespace is not None
                    and namespace.group(1) not in geography_namespaces
                ):
                    return token
                field = re.search(r"([A-Za-z0-9_]+)\s*=\s*$", prefix)
                if field is not None and field.group(1) in protected_fields:
                    return token
                return replacement

            rewritten = token_re.sub(replace_token, source)
            rewritten = typed_scope_re.sub(
                lambda match: (
                    f"{match.group(1)}:"
                    f"{replacements.get(match.group(2), match.group(2))}"
                ),
                rewritten,
            )
            rewritten = geography_field_re.sub(
                lambda match: (
                    f"{match.group(1)} = "
                    f"{replacements.get(match.group(2), match.group(2))}"
                ),
                rewritten,
            )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/scripted_geography/")
            ):
                rewritten = scripted_geography_rewrite(rewritten)
            if relative in {
                "main_menu/common/flag_definitions/00_flag_definitions.txt",
                "main_menu/common/scripted_triggers/00_coa_triggers.txt",
            }:
                rewritten = flag_definition_rewrite(rewritten)
            if relative == "in_game/common/on_action/_hardcoded.txt":
                rewritten = hardcoded_on_action_rewrite(rewritten)
            if relative == "in_game/common/on_action/location_pulses.txt":
                # Retail weather routes are authored as long Earth-location
                # paths. Geography token substitution collapses those routes
                # onto one stand-in and the monthly pulse then rejects them.
                # M5 can author Middle-earth weather paths with the census.
                rewritten = remove_named_blocks(
                    rewritten,
                    frozenset({"start_weather_system"}),
                )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/situations/")
            ):
                # Keep the installed situation registry for script consumers,
                # but no historical-Earth situation may activate before M10.
                rewritten = re.sub(
                    (
                        r"(?m)^(\s*monthly_spawn_chance\s*=\s*)"
                        r"[A-Za-z0-9_.:-]+\s*$"
                    ),
                    r"\g<1>0",
                    rewritten,
                )
                rewritten = disable_predicate_blocks(rewritten, "can_start")
                rewritten = re.sub(
                    (
                        r"(?m)^(\s*)"
                        r"(c:[A-Z0-9_]+|location:[A-Za-z0-9_]+|"
                        r"international_organization:[A-Za-z0-9_]+)"
                        r"\s*=\s*\{"
                    ),
                    r"\1\2 ?= {",
                    rewritten,
                )
            if (
                relative
                == "in_game/common/disasters/sinicization_disaster.txt"
            ):
                # Country selection evaluates comparison operands even when
                # the preceding country_exists = c:CHI guard is false. Keep
                # the ABI definition and its variable reads intact, but remove
                # the only hard missing-country scope that returns `none`.
                rewritten = re.sub(
                    (
                        r"(?m)^(\s*value\s*=\s*)"
                        r"c:CHI\.country_economical_base\s*$"
                    ),
                    r"\g<1>0",
                    rewritten,
                )
            if relative == "in_game/common/laws/02_country_specific.txt":
                law_country = (
                    "GON"
                    if (ROOT / "docs/world/realms.csv").is_file()
                    else "SWE"
                )
                rewritten = re.sub(
                    r"(?m)^(\s*law_country_group\s*=\s*)[A-Z0-9_]+\s*$",
                    rf"\g<1>{law_country}",
                    rewritten,
                )
            if relative.startswith(
                "main_menu/common/static_modifiers/"
            ):
                rewritten = remove_named_blocks(
                    rewritten,
                    UNUSED_EARTH_STATIC_MODIFIERS,
                )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/building_types/")
            ):
                # An M2 gate location can be economically unlinked during the
                # first daily tick. Optional scopes preserve retail behavior
                # once a market exists without emitting invalid-link errors.
                rewritten = re.sub(
                    r"(?m)^(\s*)market\s*=\s*\{",
                    r"\1market ?= {",
                    rewritten,
                )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/advances/")
            ):
                # Country-specific advances can probe a capital before M5
                # creates a complete market graph.
                rewritten = re.sub(
                    r"(?m)^(\s*)market\s*=\s*\{",
                    r"\1market ?= {",
                    rewritten,
                )
            if relative == "in_game/common/generic_actions/markets.txt":
                rewritten = re.sub(
                    r"(?m)^(\s*potential\s*=\s*)\{\s*\}",
                    r"\1{ always = no }",
                    rewritten,
                )
            if (
                relative
                == "in_game/common/cabinet_actions/office_of_new_converts.txt"
            ):
                rewritten = (
                    "office_of_new_converts = {\n"
                    "\tability = mil\n"
                    "\tallow_multiple = no\n"
                    "\tpotential = { always = no }\n"
                    "\tallow = { always = no }\n"
                    "\tcountry_modifier = { }\n"
                    "}\n"
                )
            if (
                tree == "in_game"
                and (
                    relative_in_tree.startswith("common/formable_countries/")
                    or relative_in_tree.startswith("common/government_reforms/")
                )
            ):
                # Earth dynasty predicates cannot resolve against the neutral
                # M2/M3 setup, which intentionally has no historical dynasties.
                rewritten = re.sub(
                    r"dynasty\s*\??=\s*dynasty:[A-Za-z0-9_]+",
                    "always = no",
                    rewritten,
                )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("events/")
            ):
                rewritten = disable_named_blocks(
                    rewritten,
                    "dynamic_historical_event",
                )
            if relative == "in_game/events/DHE/flavor_chi.txt":
                rewritten = re.sub(
                    (
                        r"(?m)^[ \t]*set_variable\s*=\s*"
                        r"chi_red_turban_leader_arrested\s*$"
                    ),
                    "",
                    rewritten,
                )
            if relative in {
                (
                    "in_game/common/parliament_issues/"
                    "06_peasants_estate_parliament_issues.txt"
                ),
                (
                    "in_game/common/parliament_issues/"
                    "07_expansion_parliament_issues.txt"
                ),
            }:
                rewritten = flag_definition_rewrite(rewritten)
            if rewritten != source:
                # Retail source contains a handful of whitespace-only line tails.
                # Keep token substitution exact while ensuring generated overlays
                # remain clean commit artifacts.
                rewritten = re.sub(r"[ \t]+(?=\r?$)", "", rewritten, flags=re.MULTILINE)
                rewritten = re.sub(
                    r"(?m)^[ \t]+",
                    lambda match: re.sub(r" +\t", "\t", match.group(0)),
                    rewritten,
                )
                # Generated overlays have exactly one terminal newline. Some
                # retail databases become empty after their obsolete M2-only
                # entries are removed, and retaining the source's blank tail
                # would make `git diff --check` fail.
                rewritten = rewritten.rstrip() + "\n" if rewritten.strip() else ""
                payloads[relative] = M2_MARKER + rewritten
    return payloads


def remove_m1_overlays() -> None:
    if OLD_MANIFEST.is_file():
        paths = json.loads(OLD_MANIFEST.read_text(encoding="utf-8-sig"))
        for relative in paths:
            path = ROOT / relative
            if path.is_file() and path.read_text(
                encoding="utf-8-sig",
                errors="replace",
            ).startswith(M1_MARKER.rstrip()):
                path.unlink()
        OLD_MANIFEST.unlink()


def write() -> None:
    remove_m1_overlays()
    payloads = expected_overlays()
    previous: set[str] = set()
    if MANIFEST.is_file():
        previous = set(json.loads(MANIFEST.read_text(encoding="utf-8-sig")))
    for relative in previous - set(payloads):
        path = ROOT / relative
        if path.is_file() and path.read_text(
            encoding="utf-8-sig",
            errors="replace",
        ).startswith(M2_MARKER.rstrip()):
            path.unlink()
    for relative, text in payloads.items():
        path = ROOT / relative
        if path.is_file():
            existing = path.read_text(encoding="utf-8-sig", errors="replace")
            if not existing.startswith((M1_MARKER.rstrip(), M2_MARKER.rstrip())):
                # Preserve authored mod files; the sweep only owns generated overlays.
                continue
        path.parent.mkdir(parents=True, exist_ok=True)
        # The installed mirrors are declared ``-text`` in .gitattributes so
        # Git will not normalize them for us. Force deterministic LF bytes on
        # Windows; otherwise each topology-triggered rewrite churns hundreds
        # of semantically identical overlays into CRLF form.
        path.write_text(text, encoding="utf-8-sig", newline="\n")
    MANIFEST.write_text(
        json.dumps(sorted(payloads), indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"m2_quarantine: wrote {len(payloads)} exact-file overlays")


def check() -> list[str]:
    failures: list[str] = []
    expected = expected_overlays()
    if OLD_MANIFEST.exists():
        failures.append("M1 overlay manifest still exists")
    if not MANIFEST.is_file():
        failures.append("missing M2 overlay manifest")
    else:
        actual_manifest = json.loads(MANIFEST.read_text(encoding="utf-8-sig"))
        if actual_manifest != sorted(expected):
            failures.append("M2 overlay manifest differs from installed sweep")
    for relative, text in expected.items():
        path = ROOT / relative
        if not path.is_file():
            failures.append(f"missing quarantine overlay {relative}")
        elif path.read_text(encoding="utf-8-sig") != text:
            failures.append(f"quarantine overlay differs: {relative}")
    stale = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*.txt")
        if path.is_file()
        and path.read_text(encoding="utf-8-sig", errors="replace").startswith(
            M1_MARKER.rstrip()
        )
    ]
    if stale:
        failures.append(f"{len(stale)} M1 geography overlays remain")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures[:50]:
            print(f"m2_quarantine: FAIL {failure}")
        if len(failures) > 50:
            print(f"m2_quarantine: FAIL ... {len(failures) - 50} more")
        return 1
    print("m2_quarantine: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
