#!/usr/bin/env python3
"""Generate/check the M2 vanilla geography-reference quarantine sweep."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_definitions import hierarchy
from worldgen import MAP_OUT, ROOT, build_model, game_map, installed_named_registry

M1_MARKER = "# Generated M1 geography compatibility overlay; replaced wholesale by M2.\n"
M2_MARKER = "# Generated by tools/m2_quarantine.py --write; M2 geography quarantine.\n"
MANIFEST = MAP_OUT / "m2_script_overlay_manifest.json"
OLD_MANIFEST = MAP_OUT / "m1_script_overlay_manifest.json"


def strip_comments(text: str) -> str:
    return re.sub(r"#.*", "", text)


def hierarchy_keys(text: str) -> list[list[str]]:
    levels: list[list[str]] = [[] for _ in range(5)]
    depth = 0
    token_re = re.compile(r"([A-Za-z0-9_]+)\s*=\s*\{|\}")
    for match in token_re.finditer(strip_comments(text)):
        key = match.group(1)
        if key is not None:
            if depth < len(levels):
                levels[depth].append(key)
            depth += 1
        else:
            depth -= 1
    if depth:
        raise ValueError(f"installed definitions end at brace depth {depth}")
    return levels


def standin_path() -> tuple[str, str, str, str, str, str]:
    model = build_model()
    target = model.by_key["minas_tirith"]
    structure = hierarchy(model)
    for continent, regions in structure.items():
        for region, areas in regions.items():
            for area, provinces in areas.items():
                for number, province in enumerate(provinces, 1):
                    if any(location.key == target.key for location in province):
                        return (
                            continent,
                            f"{continent}_subcontinent",
                            region,
                            area,
                            f"{area}_province_{number:02d}",
                            target.key,
                        )
    raise ValueError("Minas Tirith is absent from generated hierarchy")


def installed_game() -> Path:
    return game_map().parents[1]


def replacement_map() -> dict[str, str]:
    definitions = (game_map() / "definitions.txt").read_text(encoding="utf-8-sig")
    standins = standin_path()[:5]
    installed_locations = installed_named_registry()[1]
    replacements: dict[str, str] = {}
    for depth, keys in enumerate(hierarchy_keys(definitions)):
        for key in keys:
            if key not in installed_locations:
                replacements.setdefault(key, standins[depth])
    # Installed evidence: these two legal keys occur at more than one depth.
    replacements["eastern_baltic_sea"] = standins[3]
    replacements["limousin_province"] = standins[4]
    return replacements


def scripted_geography_rewrite(text: str) -> str:
    blocks = (
        ("location", standin_path()[5]),
        ("province_definition", standin_path()[4]),
        ("area", standin_path()[3]),
        ("region", standin_path()[2]),
        ("subcontinent", standin_path()[1]),
        ("continent", standin_path()[0]),
    )
    for block_name, standin in blocks:
        text = re.sub(
            rf"(?ms)(^\s*{block_name}\s*=\s*\{{\s*$).*?(^\s*\}}\s*$)",
            rf"\1\n\t\t{standin}\n\2",
            text,
        )
    return text


def expected_overlays() -> dict[str, str]:
    # Runtime/scenario neutralizers own their exact files and take precedence
    # over generic token substitution.
    from m2_runtime import payloads as runtime_payloads

    runtime_owned = {
        path.relative_to(ROOT).as_posix()
        for path in runtime_payloads()
    }
    replacements = replacement_map()
    token_re = re.compile(r"\b[A-Za-z0-9_]+\b")
    payloads: dict[str, str] = {}
    game = installed_game()
    for tree in ("in_game", "main_menu", "loading_screen"):
        installed_tree = game / tree
        for source_path in sorted(installed_tree.rglob("*.txt")):
            relative_in_tree = source_path.relative_to(installed_tree).as_posix()
            if tree == "in_game" and relative_in_tree.startswith("map_data/"):
                continue
            if tree == "loading_screen" and relative_in_tree.startswith("sound/"):
                continue
            relative = f"{tree}/{relative_in_tree}"
            if relative in runtime_owned:
                continue
            source = source_path.read_text(encoding="utf-8-sig", errors="strict")
            rewritten = token_re.sub(
                lambda match: replacements.get(match.group(0), match.group(0)),
                source,
            )
            if (
                tree == "in_game"
                and relative_in_tree.startswith("common/scripted_geography/")
            ):
                rewritten = scripted_geography_rewrite(rewritten)
            if rewritten != source:
                # Retail source contains a handful of whitespace-only line tails.
                # Keep token substitution exact while ensuring generated overlays
                # remain clean commit artifacts.
                rewritten = re.sub(r"[ \t]+(?=\r?$)", "", rewritten, flags=re.MULTILINE)
                rewritten = re.sub(
                    r"(?m)^[ \t]+",
                    lambda match: re.sub(r" +\t", "\t", match.group(0)),
                    rewritten,
                )
                payloads[relative] = M2_MARKER + rewritten
    return payloads


def remove_m1_overlays() -> None:
    if OLD_MANIFEST.is_file():
        paths = json.loads(OLD_MANIFEST.read_text(encoding="utf-8-sig"))
        for relative in paths:
            path = ROOT / relative
            if path.is_file() and path.read_text(
                encoding="utf-8-sig",
                errors="replace",
            ).startswith(M1_MARKER.rstrip()):
                path.unlink()
        OLD_MANIFEST.unlink()


def write() -> None:
    remove_m1_overlays()
    payloads = expected_overlays()
    previous: set[str] = set()
    if MANIFEST.is_file():
        previous = set(json.loads(MANIFEST.read_text(encoding="utf-8-sig")))
    for relative in previous - set(payloads):
        path = ROOT / relative
        if path.is_file() and path.read_text(
            encoding="utf-8-sig",
            errors="replace",
        ).startswith(M2_MARKER.rstrip()):
            path.unlink()
    for relative, text in payloads.items():
        path = ROOT / relative
        if path.is_file():
            existing = path.read_text(encoding="utf-8-sig", errors="replace")
            if not existing.startswith((M1_MARKER.rstrip(), M2_MARKER.rstrip())):
                # Preserve authored mod files; the sweep only owns generated overlays.
                continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8-sig")
    MANIFEST.write_text(
        json.dumps(sorted(payloads), indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"m2_quarantine: wrote {len(payloads)} exact-file overlays")


def check() -> list[str]:
    failures: list[str] = []
    expected = expected_overlays()
    if OLD_MANIFEST.exists():
        failures.append("M1 overlay manifest still exists")
    if not MANIFEST.is_file():
        failures.append("missing M2 overlay manifest")
    else:
        actual_manifest = json.loads(MANIFEST.read_text(encoding="utf-8-sig"))
        if actual_manifest != sorted(expected):
            failures.append("M2 overlay manifest differs from installed sweep")
    for relative, text in expected.items():
        path = ROOT / relative
        if not path.is_file():
            failures.append(f"missing quarantine overlay {relative}")
        elif path.read_text(encoding="utf-8-sig") != text:
            failures.append(f"quarantine overlay differs: {relative}")
    stale = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*.txt")
        if path.is_file()
        and path.read_text(encoding="utf-8-sig", errors="replace").startswith(
            M1_MARKER.rstrip()
        )
    ]
    if stale:
        failures.append(f"{len(stale)} M1 geography overlays remain")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures[:50]:
            print(f"m2_quarantine: FAIL {failure}")
        if len(failures) > 50:
            print(f"m2_quarantine: FAIL ... {len(failures) - 50} more")
        return 1
    print("m2_quarantine: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
