#!/usr/bin/env python3
"""Generate/check the neutral runtime scaffold used to verify the M2 map."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldgen import MAP_OUT, ROOT, build_model, game_map

START_OUT = ROOT / "main_menu/setup/start"
SCENARIO_OUT = ROOT / "main_menu/common/scenarios"
TEST_OUT = ROOT / "in_game/common/tests"
TRAIT_OUT = ROOT / "in_game/common/traits"
LOC_OUT = ROOT / "in_game/localization/english"


def start_payloads() -> dict[Path, str]:
    model = build_model()
    owned = [
        location.key
        for location in model.locations
        if location.kind == "land"
    ]
    anchor = "minas_tirith"
    prefix = "# Generated by tools/m2_runtime.py --write; neutral M2 gate scaffold.\n"
    files = {
        "02_core.txt": "institution_manager = {\n\tinstitutions = {\n\t}\n}\nreligion_manager = {\n}\n",
        "03_markets.txt": f"market_manager = {{\n\tadd_market = {anchor}\n}}\n",
        "04_dynasties.txt": "dynasty_manager = {\n}\n",
        "05_characters.txt": "character_db = {\n}\n",
        "06_pops.txt": (
            "locations = {\n"
            + "".join(
                f"\t{key} = {{ define_pop = "
                "{ type = peasants size = 1 culture = swedish religion = catholic } }\n"
                for key in owned
            )
            + "}\n"
        ),
        "07_cities_and_buildings.txt": (
            "locations = {\n"
            f"\t{anchor} = {{ rank = town }}\n"
            "}\n"
            "building_manager = {\n}\n"
        ),
        "08_institutions.txt": "locations = {\n}\n",
        "09_roads.txt": "road_network = {\n}\n",
        "10_countries.txt": (
            "current_age = age_1_traditions\n"
            "countries = {\n"
            "\tcountries = {\n"
            "\t\tSWE = {\n"
            f"\t\t\town_control_core = {{ {' '.join(owned)} }}\n"
            '\t\t\tinclude = "catholic_monarchy"\n'
            "\t\t\tcountry_rank = rank_county\n"
            f"\t\t\tcapital = {anchor}\n"
            "\t\t}\n"
            "\t}\n"
            "}\n"
        ),
        "11_art.txt": "work_of_art_manager = {\n}\n",
        "12_diplomacy.txt": "diplomacy_manager = {\n}\n",
        "13_religion.txt": "building_manager = {\n}\nreligion_manager = {\n}\n",
        "14_development.txt": "development = {\n\tbase = 0\n}\n",
        "15_international_organizations.txt": (
            "international_organization_manager = {\n"
            "\tadd_international_organization = {\n"
            "\t\ttype = hre\n"
            "\t\tcreation_date = 3018.1.1\n"
            "\t\tmap_color = hsv360 { 40 50 70 }\n"
            "\t\tmembers = { SWE }\n"
            "\t\tleader = SWE\n"
            "\t\temperor = { SWE }\n"
            "\t}\n"
            "}\n"
        ),
        "16_wars.txt": "war_manager = {\n}\n",
        "18_opinions.txt": "diplomacy_manager = {\n}\n",
        "19_diseases.txt": "disease_outbreak_manager = {\n}\n",
        "20_rivals.txt": "diplomacy_manager = {\n}\n",
        "21_locations.txt": "locations = {\n}\n",
        "22_situations.txt": "situation_manager = {\n}\n",
        "23_colonies.txt": "colony_manager = {\n}\n",
        "24_town_rights.txt": "townrights_manager = {\n}\n",
        "25_area_preferences.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
        "26_ai_personalities.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
        "27_armies.txt": "unit_manager = {\n}\n",
    }
    return {START_OUT / name: prefix + text for name, text in files.items()}


def other_payloads() -> dict[Path, str]:
    payloads: dict[Path, str] = {}
    payloads[SCENARIO_OUT / "00_scenarios.txt"] = (
        "\ufeff# Generated by tools/m2_runtime.py --write; neutral M2 scenario.\n"
        "me_m2_map_scenario = {\n"
        "\tcountry = SWE\n"
        "\tplayer_playstyle = ADMINISTRATIVE\n"
        "\tplayer_proficiency = NOVICE\n"
        "}\n"
    )
    payloads[TEST_OUT / "me_m2_map.txt"] = (
        "\ufeff# Generated by tools/m2_runtime.py --write; M2 runtime probe.\n"
        "me_m2_map_test = {\n"
        "\tyear = 3019\n"
        "\tsuccess = { always = yes }\n"
        "\tend_year = 3020\n"
        "\tfail_on_end_year = yes\n"
        "\tsuccess_effect = {\n"
        "\t\ttest_log = {\n"
        "\t\t\tname = me_m2_map_test\n"
        '\t\t\ttext = "M2 production map runtime test passed"\n'
        "\t\t}\n"
        "\t}\n"
        "}\n"
    )
    payloads[TRAIT_OUT / "me_m2_immortality_probe.txt"] = (
        "\ufeff# Native immortality remains a proven ENDÓRË engine contract.\n"
        "me_m2_immortality_probe = {\n"
        "\tallow = { }\n"
        "\tcategory = ruler\n"
        "\tmodifier = {\n"
        "\t\tis_immortal = yes\n"
        "\t}\n"
        "}\n"
    )
    payloads[LOC_OUT / "m2_runtime_l_english.yml"] = (
        '\ufeffl_english:\n'
        ' me_m2_immortality_probe: "Undying"\n'
        ' desc_me_m2_immortality_probe: "This probe preserves the native immortality contract."\n'
        ' me_m2_immortality_probe_die_desc: "An immortal character cannot die naturally."\n'
    )

    installed_tests = game_map().parent / "common/tests"
    for path in installed_tests.glob("*.txt"):
        if path.name == "readme.txt":
            continue
        payloads[TEST_OUT / path.name] = (
            "\ufeff# Generated M2 quarantine: vanilla geography-dependent runtime test.\n"
        )
    installed_holy_sites = game_map().parent / "common/holy_sites"
    for path in installed_holy_sites.glob("*.txt"):
        payloads[ROOT / "in_game/common/holy_sites" / path.name] = (
            "\ufeff# Generated M2 quarantine: vanilla Earth holy sites.\n"
        )
    payloads[ROOT / "in_game/common/scripted_effects/___test_effects.txt"] = (
        "\ufeff# Generated M2 quarantine: retail debug effects reference Earth databases.\n"
    )
    payloads[ROOT / "in_game/events/debug/000_johan_debug.txt"] = (
        "\ufeff# Generated M2 quarantine: retail developer-only event payload.\n"
    )
    succession_source = (
        game_map().parent / "common/disasters/byzantine_succession_crisis.txt"
    ).read_text(encoding="utf-8-sig")
    payloads[
        ROOT / "in_game/common/disasters/byzantine_succession_crisis.txt"
    ] = "\ufeff" + succession_source.replace(
        "\t\tset_variable = succession_crisis_disaster_counter\n",
        "",
    )
    return payloads


def payloads() -> dict[Path, str]:
    result = start_payloads()
    result.update(other_payloads())
    return result


def stale_m1_paths() -> tuple[Path, ...]:
    return (
        MAP_OUT / "m1_manifest.json",
        TEST_OUT / "me_m1_proof.txt",
        TRAIT_OUT / "me_m1_immortality_probe.txt",
        LOC_OUT / "m1_proof_l_english.yml",
    )


def write() -> None:
    data = payloads()
    for path, text in data.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    for path in stale_m1_paths():
        if path.is_file():
            path.unlink()
    print(f"m2_runtime: wrote {len(data)} neutral scaffold/quarantine files")


def check() -> list[str]:
    failures: list[str] = []
    for path, expected in payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M2 runtime model")
    stale = [path.relative_to(ROOT).as_posix() for path in stale_m1_paths() if path.exists()]
    if stale:
        failures.append("stale M1 runtime files remain: " + ", ".join(stale))
    owned = [
        location.key
        for location in build_model().locations
        if location.kind == "land"
    ]
    countries = start_payloads()[START_OUT / "10_countries.txt"]
    if any(key not in countries for key in owned):
        failures.append("dummy M2 country does not cover every passable land location")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"m2_runtime: FAIL {failure}")
        return 1
    print("m2_runtime: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
