#!/usr/bin/env python3
"""Generate/check the M3 Middle-earth political map, gazetteer, and ruin layer."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, str(Path(__file__).resolve().parent))

from m2_controls import ENGINE_WATER_LEVEL_SAMPLE
from m2_runtime import sanitized_monarchy_template
from worldgen import (
    CONTROL,
    CONTROL_H,
    CONTROL_W,
    DERIVED,
    MORDOR_REGION_POLYGON,
    ROOT,
    Location,
    WorldModel,
    build_model,
    load_anchors,
    model_manifest,
)

REALMS_CSV = ROOT / "docs/world/realms.csv"
LANDMARKS_CSV = ROOT / "docs/world/control/m3_landmarks.csv"
OWNERSHIP_CSV = DERIVED / "m3_ownership.csv"
OWNERSHIP_AUDIT_CSV = DERIVED / "m3_ownership_audit.csv"
OWNERSHIP_AUDIT_JSON = DERIVED / "m3_ownership_audit.json"
GAZETTEER_CSV = DERIVED / "m3_gazetteer.csv"
MANIFEST_JSON = DERIVED / "m3_manifest.json"
POLITICAL_QA_OUT = DERIVED / "m3_political_control.png"
PORTS_OUT = ROOT / "in_game/map_data/ports.csv"
COUNTRY_OUT = ROOT / "in_game/setup/countries/me_00_world.txt"
SCANDINAVIA_OUT = ROOT / "in_game/setup/countries/_scandinavia.txt"
START_COUNTRIES_OUT = ROOT / "main_menu/setup/start/10_countries.txt"
START_LOCATIONS_OUT = ROOT / "main_menu/setup/start/21_locations.txt"
COA_OUT = ROOT / "main_menu/common/coat_of_arms/coat_of_arms/me_00_realms.txt"
FLAGS_OUT = ROOT / "main_menu/common/flag_definitions/00_flag_definitions.txt"
SCENARIO_OUT = ROOT / "main_menu/common/scenarios/00_scenarios.txt"
LOCALIZATION_OUT = ROOT / "in_game/localization/english/m3_realms_l_english.yml"

WILD = "WILD"
M3_MARKER = "# Generated by tools/m3_realms.py --write."
EXPECTED_REALM_COUNT = 38
MINAS_MORGUL_DECISION = (
    "Minas Morgul is a Mordor fortress-location, not a separate country."
)

# Source-side political envelopes are deliberately few and high-confidence. They bind
# the theatres whose unrestricted nearest-seat allocation visibly crossed canonical
# physical barriers; other realms continue to use their reviewed region membership.
# Coordinates are in the equal-scale ENDÓRË projection. Exact borders are necessarily
# judgement calls because Tolkien supplies named lands and physical frontiers rather
# than cadastral boundaries; the rationale is logged in docs/ASSUMPTIONS.md.
CLAIM_BOUNDS: dict[str, tuple[float, float, float, float, str]] = {
    "GON": (0.350, 0.690, 0.550, 0.770, "Gondor fiefs from Anfalas to the Anduin"),
    "DAM": (0.460, 0.530, 0.600, 0.730, "Dol Amroth and Belfalas peninsula"),
    "ROH": (0.450, 0.570, 0.420, 0.580, "The Mark between Isen, Anduin, and White Mountains"),
    "SHI": (0.315, 0.390, 0.200, 0.290, "Shire bounds west of the Brandywine"),
    "BRE": (0.380, 0.415, 0.200, 0.285, "Bree-land's four-village crossroads"),
    "RAN": (0.430, 0.500, 0.235, 0.335, "The Angle and immediate Ranger refuge"),
    "LIN": (0.140, 0.320, 0.110, 0.380, "Lindon west of the Blue Mountains"),
    "BLU": (0.260, 0.320, 0.120, 0.230, "Surviving Ered Luin halls"),
    "LOR": (0.498, 0.550, 0.330, 0.395, "Naith between Misty foothills and Anduin"),
    "DUN": (0.395, 0.470, 0.400, 0.515, "Dunland west of Isen and the Gap"),
    "MOA": (0.470, 0.505, 0.300, 0.370, "Moria and immediate Dimrill/Sirannon approaches"),
    "GOB": (0.490, 0.522, 0.150, 0.235, "Goblin-town and High Pass under the Misty Mountains"),
    "GUN": (0.470, 0.545, 0.065, 0.150, "Gundabad and the northern mountain junction"),
    "IRO": (0.645, 0.710, 0.120, 0.190, "Iron Hills source label and adjacent holds"),
    "ERE": (0.570, 0.630, 0.110, 0.190, "Erebor and its immediate mountain approaches"),
    "DAL": (0.585, 0.640, 0.130, 0.230, "Dale and the upper Celduin plain"),
    "ESG": (0.585, 0.630, 0.150, 0.230, "Lake-town and Long Lake shore"),
    "WOO": (0.550, 0.640, 0.120, 0.305, "Thranduil's northern and eastern Mirkwood"),
    "WDM": (0.525, 0.595, 0.220, 0.355, "Woodmen settlements in western Mirkwood"),
    "BEO": (0.490, 0.555, 0.150, 0.300, "Beorning crossings and upper Anduin vales"),
    "DOL": (0.530, 0.600, 0.310, 0.410, "Dol Guldur's southern Mirkwood shadow"),
    "DOR": (0.640, 0.730, 0.285, 0.440, "Dorwinion around the northwest Sea of Rhûn"),
    "FAN": (0.450, 0.520, 0.405, 0.505, "Fangorn source forest and Entwash headwaters"),
    "DRU": (0.535, 0.585, 0.560, 0.625, "Drúadan Forest and Stonewain approaches"),
    "RIV": (0.475, 0.510, 0.195, 0.245, "Imladris hidden valley and immediate refuge"),
    "LOS": (0.190, 0.410, 0.000, 0.130, "Lossoth settlements around the Icebay"),
    "MOR": (0.595, 0.770, 0.515, 0.730, "Mordor within the enclosing mountain walls"),
    "ISE": (0.445, 0.480, 0.415, 0.515, "Isengard ring and Nan Curunír approaches"),
    "UMB": (0.440, 0.590, 0.770, 1.000, "Umbar coast and corsair hinterland"),
    "ANG": (0.415, 0.480, 0.060, 0.200, "Mount Gram and Angmar remnant fastnesses"),
    "RHO": (0.552, 0.580, 0.265, 0.300, "Rhosgobel's single inhabited clearing"),
}

# A rectangle is only a coarse search envelope. Canonical woodland realms use the
# hash-pinned Arda Maps physical polygon itself, raster-overlapped against complete EU5
# locations, while Dunland follows a reviewed lowland frontier rather than filling its
# rectangular search box. Forced seats remain admissible and visible in the audit.
SOURCE_ZONE_CLAIMS: dict[str, tuple[str, int, str]] = {
    "LOR": ("lothlorien", 4, "Arda Maps Golden Wood / Naith physical polygon"),
    "FAN": ("fangorn", 10, "Arda Maps Fangorn physical woodland polygon"),
    "DRU": ("druadan", 8, "Arda Maps Drúadan Forest physical woodland polygon"),
    "WOO": ("mirkwood", 10, "Arda Maps Mirkwood polygon: northern/eastern Woodland Realm"),
    "WDM": ("mirkwood", 10, "Arda Maps Mirkwood polygon: western Woodmen settlements"),
    "DOL": ("mirkwood", 10, "Arda Maps Mirkwood polygon: southern Dol Guldur shadow"),
}
CLAIM_POLYGONS: dict[str, tuple[tuple[tuple[float, float], ...], str]] = {
    "ANG": (
        (
            (0.447, 0.122),
            (0.460, 0.128),
            (0.468, 0.141),
            (0.466, 0.157),
            (0.454, 0.166),
            (0.438, 0.164),
            (0.428, 0.153),
            (0.429, 0.137),
            (0.438, 0.126),
        ),
        "compact Mount Gram remnant with Carn Dum retained only as a forced fastness",
    ),
    "LOR": (
        (
            (0.501, 0.339),
            (0.512, 0.326),
            (0.532, 0.331),
            (0.545, 0.349),
            (0.543, 0.378),
            (0.529, 0.398),
            (0.507, 0.390),
            (0.498, 0.366),
        ),
        "Lothlórien's Naith east of the Misty crest and west of Anduin",
    ),
    "WOO": (
        (
            (0.553, 0.122),
            (0.598, 0.118),
            (0.631, 0.145),
            (0.631, 0.218),
            (0.616, 0.266),
            (0.588, 0.300),
            (0.560, 0.287),
            (0.550, 0.221),
        ),
        "Woodland Realm in northern and northeastern Mirkwood",
    ),
    "WDM": (
        (
            (0.529, 0.218),
            (0.558, 0.210),
            (0.584, 0.236),
            (0.595, 0.284),
            (0.580, 0.340),
            (0.548, 0.350),
            (0.526, 0.313),
        ),
        "Woodmen clearings along western and central Mirkwood",
    ),
    "DOL": (
        (
            (0.538, 0.307),
            (0.577, 0.306),
            (0.603, 0.332),
            (0.596, 0.382),
            (0.566, 0.409),
            (0.534, 0.384),
        ),
        "Dol Guldur's southern Mirkwood shadow",
    ),
    "DUN": (
        (
            (0.414, 0.414),
            (0.445, 0.401),
            (0.461, 0.425),
            (0.458, 0.468),
            (0.446, 0.507),
            (0.420, 0.500),
            (0.406, 0.462),
        ),
        "Dunland lowlands west of Isen and the Gap, south of Glanduin",
    ),
    "ISE": (
        (
            (0.458, 0.424),
            (0.470, 0.420),
            (0.478, 0.438),
            (0.477, 0.459),
            (0.471, 0.477),
            (0.458, 0.477),
            (0.450, 0.460),
            (0.451, 0.440),
        ),
        "compact Nan Curunir vale north of the Fords of Isen",
    ),
    "ERE": (
        (
            (0.5997, 0.118),
            (0.6090, 0.121),
            (0.6140, 0.128),
            (0.6140, 0.138),
            (0.6070, 0.146),
            (0.5980, 0.148),
            (0.5890, 0.143),
            (0.5850, 0.133),
            (0.5890, 0.123),
        ),
        "Lonely Mountain and its immediate source-centred approaches",
    ),
    "MOR": (
        MORDOR_REGION_POLYGON,
        "Mordor inside the source-reviewed Ered Lithui and Ephel Duath enclosure",
    ),
    "HNE": (
        (
            (0.555, 0.754),
            (0.650, 0.747),
            (0.711, 0.774),
            (0.718, 0.825),
            (0.688, 0.858),
            (0.612, 0.851),
            (0.565, 0.817),
        ),
        "Harnendor between the Poros approaches and the Harnen",
    ),
    "HRA": (
        (
            (0.600, 0.824),
            (0.688, 0.818),
            (0.742, 0.850),
            (0.736, 0.919),
            (0.697, 0.965),
            (0.625, 0.950),
            (0.594, 0.889),
        ),
        "Qarsad's inland Near Harad sphere, separated from Harnendor and Khand",
    ),
    "HFA": (
        (
            (0.490, 0.904),
            (0.575, 0.892),
            (0.660, 0.919),
            (0.682, 0.997),
            (0.482, 0.997),
            (0.463, 0.958),
        ),
        "represented northern fringe of Far Harad",
    ),
    "KHA": (
        (
            (0.686, 0.671),
            (0.756, 0.650),
            (0.833, 0.685),
            (0.858, 0.751),
            (0.828, 0.823),
            (0.755, 0.836),
            (0.692, 0.795),
        ),
        "Khand east and southeast of Mordor, excluding Far Harad",
    ),
    "RHU": (
        (
            (0.700, 0.115),
            (0.770, 0.105),
            (0.818, 0.142),
            (0.825, 0.235),
            (0.798, 0.310),
            (0.727, 0.323),
            (0.682, 0.268),
            (0.684, 0.176),
        ),
        "western Rhûn polity north and east of Dorwinion",
    ),
    "RH2": (
        (
            (0.720, 0.286),
            (0.791, 0.270),
            (0.855, 0.301),
            (0.871, 0.382),
            (0.839, 0.455),
            (0.759, 0.461),
            (0.709, 0.407),
        ),
        "southeastern Rhûn wain-kingdom beyond the Sea of Rhûn",
    ),
    "RH3": (
        (
            (0.777, 0.091),
            (0.851, 0.082),
            (0.897, 0.124),
            (0.898, 0.220),
            (0.864, 0.283),
            (0.811, 0.277),
            (0.785, 0.219),
        ),
        "northeastern Rhûn confederation beyond the Iron Hills",
    ),
}
CONTRACTED_TAGS = (
    frozenset(CLAIM_BOUNDS)
    | frozenset(SOURCE_ZONE_CLAIMS)
    | frozenset(CLAIM_POLYGONS)
)

# Measured against the validated v71 nearest-seat tree before these contracts were
# applied. Retaining the baseline in the generated audit makes the correction reviewable
# without keeping a second, stale political raster.
PRE_CONTRACT_EXCEPTIONS: dict[str, tuple[int, int]] = {
    "LOR": (16, 55),
    "DUN": (218, 265),
    "MOA": (3, 26),
    "GOB": (3, 32),
    "GUN": (34, 62),
    "IRO": (0, 1),
    "WOO": (40, 119),
    "WDM": (30, 95),
    "BEO": (10, 65),
    "DOL": (20, 65),
}

# These compact, well-attested polities have no canonical reason to fracture into
# detached colour islands.  Mountain strongholds and coastal powers are audited but
# deliberately omitted because impassable ridges and water can split their location
# graph without implying a political error.
CONTIGUOUS_CLAIM_REALMS = frozenset(
    {
        "BLU",
        "BRE",
        "DOL",
        "DOR",
        "DUN",
        "ERE",
        "ESG",
        "FAN",
        "IRO",
        "ISE",
        "LOR",
        "MOA",
        "RAN",
        "WDM",
        "WOO",
    }
)

# Player-scale silhouette contracts bind reviewed political shapes to physical
# coordinates, not generated location IDs.  They deliberately cover only defects that
# have been demonstrated in the live political map; future additions require the same
# source/owner review rather than arbitrary numerical tidying.
POLITICAL_SILHOUETTE_CONTRACTS: dict[
    str, tuple[int, int, tuple[float, float, float, float], str]
] = {
    "ANG": (
        16,
        22,
        (0.425, 0.470, 0.060, 0.168),
        "Mount Gram must remain a remnant holding, not restore territorial Angmar",
    ),
    "ISE": (
        8,
        18,
        (0.445, 0.480, 0.420, 0.480),
        "Isengard must remain a compact Nan Curunir holding, not a state-sized strip",
    ),
    "ERE": (
        7,
        12,
        (0.585, 0.614, 0.118, 0.148),
        "Erebor must remain a compact Lonely Mountain holding, not an east-west strip",
    ),
    "MOR": (
        260,
        310,
        (0.595, 0.716, 0.505, 0.731),
        "Mordor must follow its mountain enclosure, not fill an eastern rectangle",
    ),
}

# The Fords lie south of Orthanc at the Gap and cannot be swallowed by Saruman's compact
# ring-domain.  The positive owner may change with a later source-backed Rohan/Dunland
# frontier revision, so the durable contract records only the canonically impossible
# owner.
FRONTIER_LANDMARK_EXCLUSIONS: dict[str, frozenset[str]] = {
    "fords_of_isen": frozenset({"ISE"}),
}
# The climate-density reseed changed generated location IDs after the v77/v78
# political review. Each repair therefore carries a narrow physical witness as
# well as the target owner: expected region and normalized coordinate window.
# This makes a future reseed fail at assignment time rather than silently
# repainting an unrelated cell that inherited an old generated ID.
#
# These are deliberately local corrections, not a generic smoothing pass that
# could erase real islands, divided valleys, or mountain fastnesses.
REVIEWED_COMPONENT_REPAIRS: dict[
    str, tuple[str, str, str, tuple[float, float, float, float]]
] = {
    "me_land_1771": (
        "DAM",
        "Belfalas coast contiguous with the Dol Amroth fief",
        "me_belfalas_region",
        (0.500, 0.520, 0.720, 0.740),
    ),
    "me_land_2353": (
        "GON",
        "south of the White Mountains on Gondor's side",
        "me_belfalas_region",
        (0.460, 0.480, 0.550, 0.580),
    ),
    "me_land_2909": (
        "GON",
        "south of the White Mountains on Gondor's side",
        "me_belfalas_region",
        (0.460, 0.480, 0.550, 0.580),
    ),
    "me_land_1346": (
        WILD,
        "east of the reviewed Brandywine Shire claim at the Bree frontier",
        "me_shire_breeland_region",
        (0.375, 0.395, 0.255, 0.280),
    ),
    "me_land_2747": (
        WILD,
        "east/north of the reviewed Brandywine Shire claim at the Bree frontier",
        "me_shire_breeland_region",
        (0.375, 0.395, 0.205, 0.225),
    ),
    "me_land_0486": (
        "BLU",
        "Blue Mountain holding closer to the Blue Halls than northern Lindon",
        "me_lindon_region",
        (0.300, 0.320, 0.125, 0.145),
    ),
    "me_land_4249": (
        "BLU",
        "Blue Mountain holding closer to the Blue Halls than northern Lindon",
        "me_lindon_region",
        (0.270, 0.290, 0.115, 0.130),
    ),
    "me_land_0003": (
        WILD,
        "unattested remote island beyond Lindon's coast",
        "me_lindon_region",
        (0.135, 0.155, 0.165, 0.185),
    ),
    "me_land_4894": (
        "ESG",
        "Long Lake shore contiguous with and closer to Esgaroth than Dale",
        "me_dale_region",
        (0.600, 0.620, 0.210, 0.230),
    ),
    "me_land_1707": (
        "BEO",
        "Anduin-vale side of the High Pass frontier, contiguous with the Beornings",
        "me_anduin_vale_region",
        (0.510, 0.530, 0.210, 0.230),
    ),
    "me_land_0973": (
        WILD,
        "east-of-crest highland beyond the compact Goblin-town holding",
        "me_anduin_vale_region",
        (0.495, 0.505, 0.220, 0.240),
    ),
    "me_land_3898": (
        WILD,
        "isolated western tip beyond the continuous southeastern Rhûn claim",
        "me_rhun_region",
        (0.710, 0.730, 0.395, 0.415),
    ),
}
# Every surviving non-primary, non-forced political component has an explicit
# physical explanation. The exact member sets intentionally make topology
# changes fail validation and return to review rather than silently inheriting
# an obsolete exception.
REVIEWED_DISCONNECTED_COMPONENTS: dict[tuple[str, frozenset[str]], str] = {
    ("GON", frozenset({"me_land_0004", "me_land_1280"})): (
        "Tolfalas island, separated from mainland Gondor by engine water"
    ),
    ("MOR", frozenset({"me_land_4703"})): (
        "southeastern Nurn pocket divided from the main component by lake and "
        "impassable enclosure topology"
    ),
    (
        "ROH",
        frozenset(
            {
                "me_land_0119",
                "me_land_0426",
                "me_land_0502",
                "me_land_0537",
                "me_land_0556",
                "me_land_0756",
                "me_land_0771",
                "me_land_1198",
                "me_land_2167",
                "me_land_2549",
                "me_land_3295",
                "me_land_3414",
                "me_land_4614",
                "me_land_4946",
            }
        ),
    ): "Westfold component divided by river/impassable location topology",
    (
        "LIN",
        frozenset(
            {
                "me_land_0214",
                "me_land_0778",
                "me_land_2766",
                "me_land_2938",
                "me_land_3349",
                "me_land_4046",
                "me_land_4096",
                "me_land_4373",
                "me_land_5113",
            }
        ),
    ): "reviewed Lindon coast divided by Gulf and Blue Mountain topology",
    (
        "LOS",
        frozenset(
            {
                "me_land_0001",
                "me_land_0117",
                "me_land_0284",
                "me_land_0775",
                "me_land_1562",
                "me_land_1699",
                "me_land_2259",
                "me_land_2977",
                "me_land_3182",
                "me_land_4177",
                "me_land_4447",
                "me_land_4665",
                "me_land_4833",
                "me_land_4898",
            }
        ),
    ): "reviewed Lossoth shore divided by Icebay water topology",
    ("LOS", frozenset({"me_land_0002"})): "remote reviewed Icebay shore/island",
    (
        "GUN",
        frozenset(
            {
                "me_land_1267",
                "me_land_2275",
                "me_land_2708",
                "me_land_4604",
                "me_land_4785",
            }
        ),
    ): "northern goblin fastnesses divided by impassable mountain locations",
    (
        "GUN",
        frozenset(
            {
                "me_land_0908",
                "me_land_3360",
                "me_land_4787",
                "me_land_5022",
            }
        ),
    ): "northern goblin fastnesses divided by impassable mountain locations",
    ("GUN", frozenset({"me_land_1335"})): (
        "isolated northern goblin fastness among impassable peaks"
    ),
    (
        "BEO",
        frozenset(
            {
                "me_land_0258",
                "me_land_0361",
                "me_land_0637",
                "me_land_2685",
                "me_land_2700",
                "me_land_3535",
            }
        ),
    ): "upper Anduin settlements divided by High Pass and impassable mountain locations",
    (
        "HNE",
        frozenset(
            {
                "me_land_0786",
                "me_land_1114",
                "me_land_1409",
                "me_land_2356",
                "me_land_2512",
                "me_land_2645",
                "me_land_3066",
                "me_land_3652",
                "me_land_4156",
            }
        ),
    ): "lower-confidence Near Harad component divided at the southern crop edge",
    ("KHA", frozenset({"me_land_1202", "me_land_2057", "me_land_4792"})): (
        "Khand approach divided from its basin by Mordor's mountain wall"
    ),
    ("RHU", frozenset({"me_land_3054", "me_land_4727", "me_land_4963"})): (
        "western Rhûn component divided from its basin at the Dorwinion frontier"
    ),
}
# Region-only claims lack a precise source envelope, so this ceiling prevents their
# allocator from reaching implausibly far across the thinly documented East and South.
# Contracted realms instead use their stronger, source-specific physical bounds.
MAX_UNCONTRACTED_CAPITAL_DISTANCE = 0.32
_LOCATION_ADJACENCY_CACHE: dict[str, dict[str, set[str]]] = {}


@dataclass(frozen=True)
class Realm:
    tag: str
    name: str
    adjective: str
    capital_ref: str
    x: float
    y: float
    regions: frozenset[str]
    style: str
    color: tuple[int, int, int]
    emblem: str
    max_locations: int
    source: str


@dataclass(frozen=True)
class Landmark:
    ref: str
    name: str
    x: float
    y: float
    rank: str
    source: str


@dataclass
class RealmState:
    model: WorldModel
    realms: tuple[Realm, ...]
    by_tag: dict[str, Realm]
    ref_to_location: dict[str, str]
    landmark_by_location: dict[str, Landmark]
    source_zone_claims: dict[str, frozenset[str]]
    ownership: dict[str, str]
    wild_reason: dict[str, str]
    names: dict[str, str]
    rank: dict[str, str]
    source: dict[str, str]


# Invented fill names use phonotactic impressions and ordinary English compounds;
# they do not claim to reconstruct Tolkien's languages. The judgement is logged in
# docs/ASSUMPTIONS.md and the full output remains auditable in the gazetteer.
STYLE_PARTS: dict[str, tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]] = {
    "sindarin": (
        ("Amon", "Dol", "Eithel", "Emyn", "Imlad", "Minas", "Ost", "Taur", "Bar", "Calen", "Celon", "Nim"),
        ("adar", "ael", "annon", "bel", "born", "caran", "duin", "falas", "galen", "gond", "loth", "morn", "nen", "rath", "sarn", "thoron"),
        ("ath", "dor", "dûr", "en", "eth", "ion", "lad", "lin", "nor", "or", "ost", "rim"),
    ),
    "westron": (
        ("Alder", "Ash", "Barrow", "Beacon", "Black", "Bramble", "Buckland", "Cedar", "Deep", "East", "Green", "Grey", "Long", "North", "Oak", "South", "Stone", "West"),
        ("bank", "bourne", "bridge", "brook", "down", "field", "ford", "gate", "hall", "heath", "mere", "ridge", "stead", "water", "wood"),
        ("", " End", " Fold", " March", " Reach", " Side", " Vale", " Ward"),
    ),
    "hobbit": (
        ("Apple", "Bramble", "Brown", "Butter", "Clover", "Dimple", "Fern", "Hay", "Hazel", "Holly", "Merry", "Moss", "Nut", "Rush", "Thistle", "Willow"),
        ("bank", "bottom", "brook", "bury", "combe", "croft", "delving", "fold", "ham", "hollow", "mead", "ton", "well", "wick"),
        ("", " Green", " Hill", " Lane", " Side", " Wood"),
    ),
    "rohirric": (
        ("Ald", "Beor", "Brego", "Ceorl", "Déor", "Eorl", "Folc", "Fram", "Grim", "Helm", "Heru", "Léod", "Rid", "Thengel", "Wold"),
        ("berg", "burna", "denu", "feld", "fold", "ford", "gar", "ham", "holt", "mere", "seld", "stede", "wæd", "worth"),
        ("", " Eastmark", " Green", " March", " Westmark"),
    ),
    "khuzdul": (
        ("Azan", "Baraz", "Bizar", "Bund", "Dum", "Felek", "Gamil", "Gathol", "Gund", "Khaz", "Kheled", "Narg", "Shar", "Zigil"),
        ("abad", "aglar", "bizar", "dûm", "gathol", "inbar", "kibil", "nâla", "rakhas", "sigin", "tumun", "zirak"),
        ("", " Gate", " Halls", " Hold", " Mines", " Vault"),
    ),
    "dalish": (
        ("Amber", "Bard", "Bell", "Bow", "Celduin", "Dale", "East", "Esgar", "King", "Lake", "Long", "North", "Raven", "Red", "West"),
        ("bank", "by", "fell", "ford", "garth", "holm", "mark", "ness", "stead", "strand", "thorpe", "wick"),
        ("", " Reach", " Road", " Shore", " Vale"),
    ),
    "beorning": (
        ("Bear", "Bee", "Carrock", "Golden", "Honey", "Oak", "River", "Skin", "Stone", "Vale", "Wild", "Wood"),
        ("bank", "den", "ford", "hall", "holt", "mead", "rock", "stead", "ward", "wood"),
        ("", " Crossing", " Lodge", " Vale"),
    ),
    "entish": (
        ("Alder", "Beech", "Birch", "Bough", "Elm", "Fir", "Leaf", "Oak", "Rowan", "Root", "Willow"),
        ("bark", "bole", "bough", "deep", "dingle", "grove", "shade", "song", "well", "wood"),
        ("", " Entwood", " Long Slow Vale", " Welling"),
    ),
    "lossoth": (
        ("Cold", "Drift", "Frost", "Ice", "North", "Pale", "Seal", "Snow", "Star", "White", "Winter"),
        ("bay", "camp", "fell", "floe", "haven", "mere", "point", "shore", "water"),
        ("", " Reach", " Sound", " Waste"),
    ),
    "orkish": (
        ("Ash", "Azg", "Black", "Burz", "Dush", "Ghash", "Gor", "Grish", "Krimp", "Lug", "Mauh", "Muzg", "Nazg", "Skai", "Ugl", "Uruk"),
        ("bag", "burz", "dûr", "fang", "gash", "glob", "grat", "krak", "lug", "mauk", "nakh", "shak", "snaga", "zagh"),
        ("", " Camp", " Cleft", " Den", " Hold", " Pits"),
    ),
    "haradric": (
        ("Azr", "Bahr", "Dar", "Far", "Hadr", "Khar", "Mahr", "Nar", "Qas", "Rakh", "Sahr", "Taz", "Umr", "Zar"),
        ("abad", "ahir", "amar", "an", "ara", "asir", "em", "esh", "im", "ir", "un", "ur"),
        ("", " Gate", " Oasis", " Wells"),
    ),
    "khandish": (
        ("Arz", "Balk", "Draz", "Ghar", "Kand", "Khaz", "Khor", "Ruz", "Skarn", "Targ", "Vark", "Zand"),
        ("ak", "an", "ar", "ash", "ek", "esh", "or", "uk", "un"),
        ("", " Camp", " Ford", " Hold", " March"),
    ),
    "rhunic": (
        ("Bal", "Bor", "Gath", "Karm", "Khur", "Lod", "Nar", "Rhov", "Sag", "Shar", "Uld", "Wain", "Zor"),
        ("ach", "ad", "ar", "ath", "en", "od", "or", "un", "ur"),
        ("", " Camp", " March", " Road", " Steppe"),
    ),
}

REGION_STYLE = {
    "me_forochel_region": "lossoth",
    "me_angmar_region": "orkish",
    "me_northern_wastes_region": "lossoth",
    "me_umbar_region": "haradric",
    "me_near_harad_region": "haradric",
    "me_far_harad_region": "haradric",
    "me_rhun_region": "rhunic",
    "me_mordor_region": "orkish",
    "me_khand_region": "khandish",
    "me_belfalas_region": "sindarin",
    "me_lebennin_region": "sindarin",
    "me_ithilien_region": "sindarin",
    "me_anorien_region": "sindarin",
    "me_south_gondor_region": "sindarin",
    "me_grey_mountains_region": "khuzdul",
    "me_dale_region": "dalish",
    "me_mirkwood_region": "westron",
    "me_rohan_region": "rohirric",
    "me_anduin_vale_region": "westron",
    "me_brown_lands_region": "sindarin",
    "me_lindon_region": "sindarin",
    "me_north_arnor_region": "sindarin",
    "me_shire_breeland_region": "hobbit",
    "me_enedwaith_region": "westron",
}


def load_realms() -> tuple[Realm, ...]:
    with REALMS_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return tuple(
        Realm(
            tag=row["tag"],
            name=row["name"],
            adjective=row["adjective"],
            capital_ref=row["capital_ref"],
            x=float(row["x"]),
            y=float(row["y"]),
            regions=frozenset(row["regions"].split("|")),
            style=row["style"],
            color=tuple(int(value) for value in row["color"].split()),
            emblem=row["emblem"],
            max_locations=int(row["max_locations"]),
            source=row["source"],
        )
        for row in rows
    )


def load_landmarks() -> tuple[Landmark, ...]:
    with LANDMARKS_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return tuple(
        Landmark(
            ref=row["ref"],
            name=row["name"],
            x=float(row["x"]),
            y=float(row["y"]),
            rank=row["rank"],
            source=row["source"],
        )
        for row in rows
    )


def normalized_distance(location: Location, x: float, y: float) -> float:
    lx, ly = location.normalized
    # Normalized x spans a canvas twice as wide as normalized y. The source
    # projection preserves equal physical scale, so x must be expanded by two
    # when comparing strategic distances.
    return ((lx - x) * 2.0) ** 2 + (ly - y) ** 2


def point_in_polygon(
    x: float,
    y: float,
    polygon: tuple[tuple[float, float], ...],
) -> bool:
    """Return whether an equal-scale source point lies inside a simple polygon."""

    inside = False
    previous_x, previous_y = polygon[-1]
    for current_x, current_y in polygon:
        if (current_y > y) != (previous_y > y):
            crossing_x = (
                (previous_x - current_x)
                * (y - current_y)
                / (previous_y - current_y)
                + current_x
            )
            if x < crossing_x:
                inside = not inside
        previous_x, previous_y = current_x, current_y
    return inside


def source_zone_location_claims(model: WorldModel) -> dict[str, frozenset[str]]:
    """Map source woodland polygons to every substantially overlapping location."""

    # Local import avoids coupling the political module's basic data types to the
    # renderer generator while sharing its exact hash-pinned/naturalized mask routine.
    from gen_map_objects import named_forest_mask

    result: dict[str, frozenset[str]] = {}
    for tag, (zone, dilation, _) in SOURCE_ZONE_CLAIMS.items():
        mask = named_forest_mask(zone)
        if dilation:
            mask = np.asarray(
                Image.fromarray(mask.astype(np.uint8) * 255, "L").filter(
                    ImageFilter.MaxFilter(dilation * 2 + 1)
                ),
                dtype=np.uint8,
            ) > 0
        overlap = np.bincount(
            model.labels[mask].astype(np.int64),
            minlength=len(model.locations),
        )
        # Sixteen source pixels is well below a typical location's area but rejects a
        # one-pixel tangency. Full location assignment then stays jagged and contiguous
        # without turning the source polygon into a cadastral rectangle.
        result[tag] = frozenset(
            location.key
            for location in model.locations
            if location.kind == "land" and overlap[location.index] >= 16
        )
    return result


def claim_contract(
    location: Location,
    realm: Realm,
    source_zone_claims: dict[str, frozenset[str]],
) -> tuple[bool, str]:
    """Apply reviewed physical-frontier contracts before political allocation."""
    source_contract = SOURCE_ZONE_CLAIMS.get(realm.tag)
    if source_contract is not None:
        allowed = location.key in source_zone_claims[realm.tag]
        rationales = [source_contract[2]]
        bounds = CLAIM_BOUNDS.get(realm.tag)
        if bounds is not None:
            x0, x1, y0, y1, _ = bounds
            x, y = location.normalized
            allowed = allowed and x0 <= x <= x1 and y0 <= y <= y1
            rationales.append(bounds[4])
        polygon_contract = CLAIM_POLYGONS.get(realm.tag)
        if polygon_contract is not None:
            polygon, rationale = polygon_contract
            allowed = allowed and point_in_polygon(
                *location.normalized,
                polygon,
            )
            rationales.append(rationale)
        return allowed, "; ".join(rationales)
    polygon_contract = CLAIM_POLYGONS.get(realm.tag)
    if polygon_contract is not None:
        polygon, rationale = polygon_contract
        return point_in_polygon(*location.normalized, polygon), rationale
    contract = CLAIM_BOUNDS.get(realm.tag)
    if contract is None:
        return True, "reviewed_region_claim"
    x0, x1, y0, y1, rationale = contract
    x, y = location.normalized
    if x0 <= x <= x1 and y0 <= y <= y1:
        return True, rationale
    return False, rationale


def resolve_landmarks(
    model: WorldModel,
) -> tuple[dict[str, str], dict[str, Landmark]]:
    anchors = load_anchors()
    land = [location for location in model.locations if location.kind == "land"]
    anchor_locations = [location for location in land if location.anchor]
    ref_to_location: dict[str, str] = {}
    reserved: set[str] = set()
    for anchor in anchors:
        location = min(
            anchor_locations,
            key=lambda item: normalized_distance(item, anchor.x, anchor.y),
        )
        ref_to_location[anchor.key] = location.key
        reserved.add(location.key)

    landmark_by_location: dict[str, Landmark] = {}
    for landmark in load_landmarks():
        if landmark.ref in ref_to_location:
            continue
        candidates = [location for location in land if location.key not in reserved]
        location = min(
            candidates,
            key=lambda item: normalized_distance(item, landmark.x, landmark.y),
        )
        ref_to_location[landmark.ref] = location.key
        landmark_by_location[location.key] = landmark
        reserved.add(location.key)
    return ref_to_location, landmark_by_location


def wilderness_reason(location: Location, protected: set[str]) -> str | None:
    if location.key in protected:
        return None
    x, y = location.normalized
    if location.region == "me_northern_wastes_region" and y < 0.155:
        return "wild_forodwaith"
    if (
        location.region == "me_enedwaith_region"
        and x < 0.42
        and 0.36 < y < 0.53
    ):
        return "wild_enedwaith"
    if (
        location.region == "me_brown_lands_region"
        and location.biome_id in {6, 8}
        and x < 0.62
    ):
        return "wild_brown_lands"
    if location.region == "me_ithilien_region":
        return "wild_ithilien"
    return None


def forced_ownership(
    realms: tuple[Realm, ...],
    ref_to_location: dict[str, str],
) -> dict[str, str]:
    forced_owner = {
        ref_to_location[realm.capital_ref]: realm.tag
        for realm in realms
    }
    if len(forced_owner) != len(realms):
        raise ValueError("two M3 realms resolve to the same capital location")
    hint_owner = {
        "Lindon": "LIN",
        "Angmar": "ANG",
        "Shire": "SHI",
        "Bree-land": "BRE",
        "Imladris": "RIV",
        "Misty Mountains": "GOB",
        "Gundabad": "GUN",
        "Moria": "MOA",
        "Beornings": "BEO",
        "Lothlórien": "LOR",
        "Dol Guldur": "DOL",
        "Woodland Realm": "WOO",
        "Lake-town": "ESG",
        "Dale": "DAL",
        "Erebor": "ERE",
        "Dorwinion": "DOR",
        "Isengard": "ISE",
        "Rohan": "ROH",
        "Gondor": "GON",
        "Mordor": "MOR",
        "Umbar": "UMB",
    }
    anchor_rank = {anchor.key: anchor.rank for anchor in load_anchors()}
    anchor_hint = {anchor.key: anchor.realm_hint for anchor in load_anchors()}
    for ref, location_key in ref_to_location.items():
        if ref not in anchor_hint or anchor_rank[ref] == "ruin":
            continue
        tag = hint_owner.get(anchor_hint[ref])
        if ref == "dol_amroth":
            tag = "DAM"
        if tag:
            forced_owner[location_key] = tag
    # These operational landmarks come from the richer M3 landmark table
    # rather than the projection anchor roster.  Several intentionally sit in
    # otherwise wild theatres (notably emptied Ithilien), but their forts and
    # refuges are canonically occupied on TA 3018.1.1.  Pin them before the
    # wilderness mask so their generated town setup always has a valid owner.
    operational_landmark_owners = {
        "derndingle": "FAN",
        "cair_andros": "GON",
        "henneth_annun": "GON",
        "harlond_gondor": "GON",
        "cirith_ungol": "MOR",
        "durthang": "MOR",
        "narchost": "MOR",
        "carchost": "MOR",
    }
    for ref, tag in operational_landmark_owners.items():
        location_key = ref_to_location.get(ref)
        if location_key is None:
            raise ValueError(f"unresolved operational landmark {ref}")
        forced_owner[location_key] = tag
    return forced_owner


def assign_ownership(
    model: WorldModel,
    realms: tuple[Realm, ...],
    ref_to_location: dict[str, str],
    source_zone_claims: dict[str, frozenset[str]],
) -> tuple[dict[str, str], dict[str, str]]:
    ownership: dict[str, str] = {}
    wild_reason: dict[str, str] = {}
    counts: Counter[str] = Counter()
    by_tag = {realm.tag: realm for realm in realms}
    forced_owner = forced_ownership(realms, ref_to_location)
    for key, tag in forced_owner.items():
        ownership[key] = tag
        counts[tag] += 1

    candidates_by_region: dict[str, list[Realm]] = defaultdict(list)
    for realm in realms:
        for region in realm.regions:
            candidates_by_region[region].append(realm)

    unassigned = [
        location
        for location in model.locations
        if location.kind == "land" and location.key not in ownership
    ]
    # Allocate the strongest Voronoi claims first so deliberately tiny realms
    # retain the compact heartland nearest their seat.
    scored: list[tuple[float, str, Location, list[tuple[float, Realm]]]] = []
    protected = set(forced_owner)
    for location in unassigned:
        reason = wilderness_reason(location, protected)
        if reason:
            ownership[location.key] = WILD
            wild_reason[location.key] = reason
            continue
        choices = sorted(
            (
                normalized_distance(location, realm.x, realm.y),
                realm,
            )
            for realm in candidates_by_region.get(location.region, ())
            if claim_contract(location, realm, source_zone_claims)[0]
        )
        if not choices:
            ownership[location.key] = WILD
            wild_reason[location.key] = "wild_unclaimed"
            continue
        scored.append((choices[0][0], location.key, location, choices))
    for _, _, location, choices in sorted(scored):
        chosen: Realm | None = None
        for _, realm in choices:
            if realm.max_locations == 0 or counts[realm.tag] < realm.max_locations:
                chosen = realm
                break
        if chosen is None:
            ownership[location.key] = WILD
            wild_reason[location.key] = "wild_buffer"
        else:
            ownership[location.key] = chosen.tag
            counts[chosen.tag] += 1

    for location in model.locations:
        if location.kind != "land":
            ownership[location.key] = WILD
            wild_reason[location.key] = f"wild_{location.kind}"
    for key, (tag, rationale, expected_region, witness) in REVIEWED_COMPONENT_REPAIRS.items():
        location = model.by_key.get(key)
        if location is None or location.kind != "land":
            raise ValueError(f"reviewed political repair lost land location {key}")
        if key in forced_owner:
            raise ValueError(f"reviewed political repair overlaps forced anchor {key}")
        if tag != WILD and tag not in by_tag:
            raise ValueError(f"reviewed political repair uses unknown realm {tag}")
        if location.region != expected_region:
            raise ValueError(
                f"reviewed political repair {key} moved from {expected_region} "
                f"to {location.region}"
            )
        x0, x1, y0, y1 = witness
        x, y = location.normalized
        if not (x0 <= x <= x1 and y0 <= y <= y1):
            raise ValueError(
                f"reviewed political repair {key} moved outside its physical witness: "
                f"{x:.7f},{y:.7f}"
            )
        if tag != WILD:
            accepted, contract = claim_contract(location, by_tag[tag], source_zone_claims)
            if not accepted:
                raise ValueError(
                    f"reviewed political repair {key}->{tag} violates {contract}"
                )
        ownership[key] = tag
        if tag == WILD:
            wild_reason[key] = f"wild_reviewed_component: {rationale}"
        else:
            wild_reason.pop(key, None)
    counts = Counter(
        ownership[location.key]
        for location in model.locations
        if location.kind == "land" and ownership[location.key] != WILD
    )
    for tag in by_tag:
        if counts[tag] < 1:
            raise ValueError(f"{tag} owns no location")
    return ownership, wild_reason


def generated_compound(style: str, serial: int) -> str:
    first, second, third = STYLE_PARTS[style]
    base_count = len(first) * len(second) * len(third)
    base_serial = serial % base_count
    cycle = serial // base_count
    a = first[base_serial % len(first)]
    b = second[(base_serial // len(first)) % len(second)]
    c = third[(base_serial // (len(first) * len(second))) % len(third)]
    if style in {"sindarin"}:
        result = f"{a} {b}{c}"
    else:
        result = f"{a}{b}{c}"
    if cycle:
        # Productive "of X" compounds keep the generated lexicon finite-state
        # and deterministic without ever exposing engineering ordinals.
        qualifier_serial = cycle - 1
        qa = first[qualifier_serial % len(first)]
        qb = second[(qualifier_serial // len(first)) % len(second)]
        qualifier = f"{qa} {qb}" if style == "sindarin" else f"{qa}{qb}"
        result = f"{result} of {qualifier}"
    return result


def all_location_names(
    model: WorldModel,
    ownership: dict[str, str],
    by_tag: dict[str, Realm],
    landmark_by_location: dict[str, Landmark],
) -> tuple[dict[str, str], dict[str, str], dict[str, str]]:
    anchor_by_name = {anchor.name: anchor for anchor in load_anchors()}
    names: dict[str, str] = {}
    ranks: dict[str, str] = {}
    sources: dict[str, str] = {}
    used: set[str] = set()
    counters: Counter[tuple[str, str]] = Counter()
    for location in model.locations:
        if location.anchor:
            anchor = anchor_by_name[location.display_name]
            name = anchor.name
            rank = anchor.rank
            source = anchor.source
        elif location.key in landmark_by_location:
            landmark = landmark_by_location[location.key]
            name = landmark.name
            rank = landmark.rank
            source = landmark.source
        else:
            owner = ownership[location.key]
            style = (
                by_tag[owner].style
                if owner != WILD
                else REGION_STYLE[location.region]
            )
            counter_key = (style, location.kind)
            serial = counters[counter_key]
            while True:
                compound = generated_compound(style, serial)
                if location.kind == "mountain":
                    name = (
                        f"Ered {compound}"
                        if style == "sindarin"
                        else f"{compound} Heights"
                    )
                elif location.kind == "lake":
                    name = (
                        f"Nen {compound}"
                        if style == "sindarin"
                        else f"Lake {compound}"
                    )
                elif location.kind == "sea":
                    name = (
                        f"Bay of {compound}"
                        if serial % 3 == 0
                        else f"{compound} Reach"
                    )
                else:
                    name = compound
                serial += 1
                if name not in used:
                    break
            counters[counter_key] = serial
            rank = "wilderness" if owner == WILD else "place"
            source = "† M3 regional lexicon"
        if name in used:
            raise ValueError(f"duplicate M3 display name: {name}")
        used.add(name)
        names[location.key] = name
        ranks[location.key] = rank
        sources[location.key] = source
    return names, ranks, sources


@lru_cache(maxsize=1)
def build_state() -> RealmState:
    model = build_model()
    realms = load_realms()
    by_tag = {realm.tag: realm for realm in realms}
    ref_to_location, landmark_by_location = resolve_landmarks(model)
    source_zone_claims = source_zone_location_claims(model)
    ownership, wild_reason = assign_ownership(
        model,
        realms,
        ref_to_location,
        source_zone_claims,
    )
    names, rank, source = all_location_names(
        model,
        ownership,
        by_tag,
        landmark_by_location,
    )
    return RealmState(
        model=model,
        realms=realms,
        by_tag=by_tag,
        ref_to_location=ref_to_location,
        landmark_by_location=landmark_by_location,
        source_zone_claims=source_zone_claims,
        ownership=ownership,
        wild_reason=wild_reason,
        names=names,
        rank=rank,
        source=source,
    )


def location_names(model: WorldModel | None = None) -> dict[str, str]:
    state = build_state()
    if model is not None and len(model.locations) != len(state.model.locations):
        raise ValueError("M3 naming model differs from M2 world model")
    return dict(state.names)


def physical_alignment(state: RealmState) -> dict[str, object]:
    """Prove political ownership and capitals sit on authored dry land."""
    with Image.open(CONTROL / "elevation.png") as image:
        elevation = np.asarray(image, dtype=np.uint16)
    if elevation.shape != state.model.labels.shape:
        raise ValueError(
            f"elevation shape {elevation.shape} differs from political labels "
            f"{state.model.labels.shape}"
        )
    owned_index = np.array(
        [
            state.ownership[location.key] != WILD
            for location in state.model.locations
        ],
        dtype=bool,
    )
    owned_pixels = owned_index[state.model.labels]
    wet_owned_pixels = int(
        np.count_nonzero(
            owned_pixels & (elevation <= ENGINE_WATER_LEVEL_SAMPLE)
        )
    )
    capitals: dict[str, dict[str, object]] = {}
    maximum_snap_distance = 0.0
    for realm in state.realms:
        key = state.ref_to_location[realm.capital_ref]
        location = state.model.by_key[key]
        distance = normalized_distance(location, realm.x, realm.y) ** 0.5
        maximum_snap_distance = max(maximum_snap_distance, distance)
        capitals[realm.tag] = {
            "location": key,
            "kind": location.kind,
            "normalized": [
                round(location.normalized[0], 6),
                round(location.normalized[1], 6),
            ],
            "authored": [realm.x, realm.y],
            "snap_distance": round(distance, 6),
            "raw_height": int(elevation[location.y, location.x]),
        }
    return {
        "engine_water_level_sample": ENGINE_WATER_LEVEL_SAMPLE,
        "owned_control_pixels": int(np.count_nonzero(owned_pixels)),
        "wet_owned_control_pixels": wet_owned_pixels,
        "maximum_capital_snap_distance": round(maximum_snap_distance, 6),
        "capitals": capitals,
    }


def political_qa_png(state: RealmState) -> bytes:
    """Render the exact ownership lookup over the physical control raster."""
    palette = np.zeros((len(state.model.locations), 3), dtype=np.uint8)
    for location in state.model.locations:
        owner = state.ownership[location.key]
        if owner != WILD:
            palette[location.index] = state.by_tag[owner].color
        elif location.kind == "sea":
            palette[location.index] = (20, 48, 72)
        elif location.kind == "lake":
            palette[location.index] = (30, 72, 88)
        elif location.kind == "mountain":
            palette[location.index] = (58, 56, 52)
        else:
            palette[location.index] = (118, 112, 96)
    image = Image.fromarray(palette[state.model.labels], mode="RGB")
    draw = ImageDraw.Draw(image)
    for realm in state.realms:
        location = state.model.by_key[
            state.ref_to_location[realm.capital_ref]
        ]
        x, y = location.x, location.y
        draw.rectangle((x - 2, y - 2, x + 2, y + 2), fill=(8, 8, 8))
        draw.point((x, y), fill=(255, 255, 255))
        # The audit raster is a review artifact, not in-game art.  Labelling
        # every seat makes the full 38-realm frontier review possible without
        # guessing colours or cross-referencing a second image.
        draw.text(
            (x + 5, y - 6),
            realm.tag,
            fill=(255, 255, 255),
            stroke_width=2,
            stroke_fill=(8, 8, 8),
        )
    output = io.BytesIO()
    image.save(output, format="PNG", compress_level=9)
    return output.getvalue()


def country_definitions(state: RealmState) -> str:
    m4_profiles = ROOT / "docs/world/peoples/realm_profiles.csv"
    if m4_profiles.is_file():
        from m4_peoples import country_profile

    lines = [
        "\ufeff" + M3_MARKER,
        (
            "# M3 realm registry joined to the authored M4 people/faith atlas."
            if m4_profiles.is_file()
            else "# M3 realm registry; technical culture and faith are replaced in M4."
        ),
    ]
    for realm in state.realms:
        red, green, blue = realm.color
        culture, faith = (
            country_profile(realm.tag)
            if m4_profiles.is_file()
            else ("swedish", "catholic")
        )
        lines.extend(
            (
                "",
                f"{realm.tag} = {{ # {realm.name}; {realm.source}",
                f"\tcolor = rgb {{ {red} {green} {blue} }}",
                f"\tcolor2 = rgb {{ {255-red} {255-green} {255-blue} }}",
                f"\tculture_definition = {culture}",
                f"\treligion_definition = {faith}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def coa_definitions(state: RealmState) -> str:
    color_names = ("black", "white", "red", "green", "blue", "yellow", "purple")
    lines = [M3_MARKER, "# Script-only M3 arms; bespoke emblems replace these in M11."]
    for index, realm in enumerate(state.realms):
        primary = color_names[index % len(color_names)]
        secondary = color_names[(index + 1 + index // len(color_names)) % len(color_names)]
        if primary == secondary:
            secondary = "white" if primary != "white" else "black"
        lines.extend(
            (
                "",
                f"{realm.tag} = {{",
                '\tpattern = "pattern_solid.dds"',
                f'\tcolor1 = "{primary}"',
                f'\tcolor2 = "{secondary}"',
                '\tcolor3 = "white"',
                "\tcolored_emblem = {",
                f'\t\ttexture = "{realm.emblem}"',
                "\t\tcolor1 = color2",
                "\t\tcolor2 = color2",
                "\t\tcolor3 = color3",
                "\t\tinstance = { position = { 0.5 0.5 } scale = { 0.78 0.78 } }",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def flag_definitions(state: RealmState) -> str:
    lines = [
        "\ufeff" + M3_MARKER,
        "DEFAULT = {",
        "\tflag_definition = {",
        "\t\tcoa = GON",
        "\t\tpriority = -100",
        "\t\ttrigger = {",
        "\t\t\talways = no",
        "\t\t\thas_variable = has_had_war_of_the_roses_disaster",
        "\t\t\thas_variable = hab_imperial_flag",
        "\t\t}",
        "\t}",
        "}",
    ]
    for realm in state.realms:
        lines.extend(
            (
                f"{realm.tag} = {{",
                "\tflag_definition = {",
                f"\t\tcoa = {realm.tag}",
                "\t\tpriority = 1",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def start_countries(state: RealmState) -> str:
    discovered = sorted({location.region for location in state.model.locations})
    owned_by_tag: dict[str, list[str]] = defaultdict(list)
    for key, tag in state.ownership.items():
        if tag != WILD:
            owned_by_tag[tag].append(key)
    monarchy = sanitized_monarchy_template().splitlines()
    lines = [
        M3_MARKER,
        "current_age = age_1_traditions",
        "",
        "countries = {",
        "\tcountries = {",
    ]
    for realm in state.realms:
        owned = sorted(owned_by_tag[realm.tag])
        lines.append(f"\t\t{realm.tag} = {{ # {realm.name}")
        lines.append("\t\t\town_control_core = {")
        lines.extend(f"\t\t\t\t{key}" for key in owned)
        lines.append("\t\t\t}")
        lines.extend(f"\t\t\t{line}" if line else "" for line in monarchy)
        lines.append("\t\t\tcountry_rank = rank_county")
        lines.append("\t\t\tdiscovered_regions = {")
        lines.extend(f"\t\t\t\t{region}" for region in discovered)
        lines.append("\t\t\t}")
        lines.append(
            f"\t\t\tcapital = {state.ref_to_location[realm.capital_ref]}"
        )
        if realm.tag == "UMB":
            # Vanilla setup ABI: accepted cultures are declared directly in
            # the country block.  Umbarite remains the realm's primary culture;
            # the old Black Numenorean houses are accepted so their noble
            # stratum can participate in the estate rather than initialize as
            # a discriminated estate culture.
            lines.append(
                "\t\t\taccepted_cultures = { me_black_numenorean }"
            )
        lines.extend(("\t\t}", ""))
    lines.extend(("\t}", "}", ""))
    return "\n".join(lines)


def start_locations(state: RealmState) -> str:
    ruins = sorted(
        key
        for key, rank in state.rank.items()
        if rank == "ruin"
    )
    lines = [
        M3_MARKER,
        "# Canonical ruins are deliberately wild and receive no census pop.",
        "locations = {",
    ]
    for key in ruins:
        lines.append(f"\t# ruin: {key}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def localization(state: RealmState) -> str:
    lines = ["\ufeffl_english:", " # Generated M3 realm and ruin localization."]
    for realm in state.realms:
        lines.append(f' {realm.tag}: "{realm.name}"')
        lines.append(f' {realm.tag}_ADJ: "{realm.adjective}"')
    return "\n".join(lines) + "\n"


def ownership_csv(state: RealmState) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(("location", "kind", "region", "realm", "status"))
    for location in state.model.locations:
        owner = state.ownership[location.key]
        status = (
            "owned"
            if owner != WILD
            else state.wild_reason[location.key]
        )
        writer.writerow((location.key, location.kind, location.region, owner, status))
    return output.getvalue()


def ownership_audit_rows(state: RealmState) -> list[dict[str, object]]:
    forced = forced_ownership(state.realms, state.ref_to_location)
    rows: list[dict[str, object]] = []
    for location in state.model.locations:
        if location.kind != "land":
            continue
        owner = state.ownership[location.key]
        x, y = location.normalized
        if owner == WILD:
            rows.append(
                {
                    "location": location.key,
                    "realm": WILD,
                    "normalized_x": f"{x:.7f}",
                    "normalized_y": f"{y:.7f}",
                    "region": location.region,
                    "biome_id": location.biome_id,
                    "distance_to_capital": "",
                    "forced": "no",
                    "contract": "deliberately unclaimed",
                    "verdict": state.wild_reason[location.key],
                }
            )
            continue
        realm = state.by_tag[owner]
        is_forced = forced.get(location.key) == owner
        component_repair = REVIEWED_COMPONENT_REPAIRS.get(location.key)
        allowed, rationale = claim_contract(
            location,
            realm,
            state.source_zone_claims,
        )
        if is_forced:
            verdict = "accepted_forced_anchor"
        elif component_repair and component_repair[0] == owner:
            rationale = component_repair[1]
            verdict = "accepted_component_repair"
        elif owner in SOURCE_ZONE_CLAIMS:
            verdict = "accepted_source_zone_overlap" if allowed else "violation"
        elif owner in CLAIM_POLYGONS:
            verdict = "accepted_frontier_polygon" if allowed else "violation"
        elif owner in CLAIM_BOUNDS:
            verdict = "accepted_source_side_envelope" if allowed else "violation"
        else:
            verdict = "accepted_reviewed_region"
        rows.append(
            {
                "location": location.key,
                "realm": owner,
                "normalized_x": f"{x:.7f}",
                "normalized_y": f"{y:.7f}",
                "region": location.region,
                "biome_id": location.biome_id,
                "distance_to_capital": (
                    f"{normalized_distance(location, realm.x, realm.y) ** 0.5:.7f}"
                ),
                "forced": "yes" if is_forced else "no",
                "contract": rationale,
                "verdict": verdict,
            }
        )
    return rows


def ownership_audit_csv(state: RealmState) -> str:
    output = io.StringIO(newline="")
    fields = (
        "location",
        "realm",
        "normalized_x",
        "normalized_y",
        "region",
        "biome_id",
        "distance_to_capital",
        "forced",
        "contract",
        "verdict",
    )
    writer = csv.DictWriter(output, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerows(ownership_audit_rows(state))
    return output.getvalue()


def location_adjacency(model: WorldModel) -> dict[str, set[str]]:
    """Return edge-sharing land-location neighbours from the generated raster."""
    model_hash = model_manifest(model)["model_sha256"]
    cached = _LOCATION_ADJACENCY_CACHE.get(model_hash)
    if cached is not None:
        return cached
    adjacency: dict[str, set[str]] = {
        location.key: set()
        for location in model.locations
        if location.kind == "land"
    }
    labels = model.labels
    pairs = np.concatenate(
        (
            np.stack((labels[:, :-1].ravel(), labels[:, 1:].ravel()), axis=1),
            np.stack((labels[:-1, :].ravel(), labels[1:, :].ravel()), axis=1),
        )
    )
    kinds = [location.kind for location in model.locations]
    keys = [location.key for location in model.locations]
    for left, right in np.unique(pairs[pairs[:, 0] != pairs[:, 1]], axis=0):
        left_index, right_index = int(left), int(right)
        if kinds[left_index] != "land" or kinds[right_index] != "land":
            continue
        left_key, right_key = keys[left_index], keys[right_index]
        adjacency[left_key].add(right_key)
        adjacency[right_key].add(left_key)
    _LOCATION_ADJACENCY_CACHE[model_hash] = adjacency
    return adjacency


def realm_connectivity(state: RealmState) -> dict[str, dict[str, object]]:
    """Summarize and disposition every connected political component."""
    adjacency = location_adjacency(state.model)
    forced = forced_ownership(state.realms, state.ref_to_location)
    result: dict[str, dict[str, object]] = {}
    for realm in state.realms:
        owned = {
            location.key
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] == realm.tag
        }
        unseen = set(owned)
        components: list[set[str]] = []
        while unseen:
            seed = min(unseen)
            component = {seed}
            frontier = [seed]
            unseen.remove(seed)
            while frontier:
                current = frontier.pop()
                neighbours = adjacency[current] & unseen & owned
                if neighbours:
                    unseen.difference_update(neighbours)
                    component.update(neighbours)
                    frontier.extend(sorted(neighbours))
            components.append(component)
        components.sort(key=lambda values: (-len(values), min(values)))
        component_rows: list[dict[str, object]] = []
        for index, component in enumerate(components):
            forced_anchors = sum(
                forced.get(location) == realm.tag for location in component
            )
            if index == 0:
                disposition = "primary_component"
            elif forced_anchors:
                disposition = "accepted_forced_anchor_barrier_split"
            else:
                disposition = REVIEWED_DISCONNECTED_COMPONENTS.get(
                    (realm.tag, frozenset(component)),
                    "unreviewed",
                )
            component_rows.append(
                {
                    "size": len(component),
                    "forced_anchors": forced_anchors,
                    "sample": sorted(component)[:5],
                    "locations": sorted(component) if index else [],
                    "disposition": disposition,
                }
            )
        detached_unforced_specks = sum(
            row["size"] <= 2 and row["forced_anchors"] == 0
            for row in component_rows[1:]
        )
        result[realm.tag] = {
            "components": len(components),
            "largest_component": len(components[0]) if components else 0,
            "largest_component_fraction": (
                round(len(components[0]) / len(owned), 6)
                if components and owned
                else 0.0
            ),
            "detached_unforced_specks": detached_unforced_specks,
            "component_detail": component_rows,
        }
    return result


def ownership_audit_json(state: RealmState) -> str:
    rows = ownership_audit_rows(state)
    connectivity = realm_connectivity(state)
    contracted: dict[str, dict[str, object]] = {}
    for tag in sorted(CONTRACTED_TAGS):
        contract = CLAIM_BOUNDS.get(tag)
        tag_rows = [row for row in rows if row["realm"] == tag]
        realm = state.by_tag[tag]
        eligible_locations = sum(
            location.kind == "land"
            and claim_contract(location, realm, state.source_zone_claims)[0]
            for location in state.model.locations
        )
        xs = [float(row["normalized_x"]) for row in tag_rows]
        ys = [float(row["normalized_y"]) for row in tag_rows]
        violations = sum(row["verdict"] == "violation" for row in tag_rows)
        contracted[tag] = {
            "rationale": (
                SOURCE_ZONE_CLAIMS[tag][2]
                if tag in SOURCE_ZONE_CLAIMS
                else CLAIM_POLYGONS[tag][1]
                if tag in CLAIM_POLYGONS
                else contract[4]
            ),
            "claim_bounds": list(contract[:4]) if contract else None,
            "source_zone": SOURCE_ZONE_CLAIMS[tag][0] if tag in SOURCE_ZONE_CLAIMS else None,
            "source_dilation_pixels": SOURCE_ZONE_CLAIMS[tag][1] if tag in SOURCE_ZONE_CLAIMS else None,
            "claim_polygon": [list(point) for point in CLAIM_POLYGONS[tag][0]] if tag in CLAIM_POLYGONS else None,
            "locations": len(tag_rows),
            "eligible_locations": eligible_locations,
            "claim_fill_fraction": (
                round(len(tag_rows) / eligible_locations, 6)
                if eligible_locations
                else 0.0
            ),
            "forced_anchors": sum(row["forced"] == "yes" for row in tag_rows),
            "final_bbox": (
                [min(xs), max(xs), min(ys), max(ys)] if tag_rows else None
            ),
            "contract_violations": violations,
            "connectivity": connectivity[tag],
            "pre_contract_outside": (
                list(PRE_CONTRACT_EXCEPTIONS[tag])
                if tag in PRE_CONTRACT_EXCEPTIONS
                else None
            ),
        }
    uncontracted: dict[str, dict[str, object]] = {}
    for realm in state.realms:
        if realm.tag in CONTRACTED_TAGS:
            continue
        tag_rows = [row for row in rows if row["realm"] == realm.tag]
        xs = [float(row["normalized_x"]) for row in tag_rows]
        ys = [float(row["normalized_y"]) for row in tag_rows]
        distances = [
            float(row["distance_to_capital"])
            for row in tag_rows
            if row["distance_to_capital"] and row["forced"] == "no"
        ]
        uncontracted[realm.tag] = {
            "rationale": "lower-confidence region claim; no invented cadastral envelope",
            "locations": len(tag_rows),
            "final_bbox": (
                [min(xs), max(xs), min(ys), max(ys)] if tag_rows else None
            ),
            "maximum_unforced_capital_distance": (
                max(distances) if distances else 0.0
            ),
            "connectivity": connectivity[realm.tag],
        }
    payload = {
        "schema": 4,
        "milestone": "M3 political assignment audit",
        "audited_land_locations": len(rows),
        "owned_locations": sum(row["realm"] != WILD for row in rows),
        "wild_locations": sum(row["realm"] == WILD for row in rows),
        "contract_violations": sum(
            row["verdict"] == "violation" for row in rows
        ),
        "contracted_realms": contracted,
        "uncontracted_realms": uncontracted,
        "all_realm_connectivity": connectivity,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def gazetteer_csv(state: RealmState) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(("location", "name", "kind", "region", "realm", "rank", "source"))
    for location in state.model.locations:
        writer.writerow(
            (
                location.key,
                state.names[location.key],
                location.kind,
                location.region,
                state.ownership[location.key],
                state.rank[location.key],
                state.source[location.key],
            )
        )
    return output.getvalue()


def manifest(state: RealmState) -> str:
    counts = Counter(state.ownership.values())
    payload = {
        "schema": 1,
        "milestone": "M3",
        "model_sha256": model_manifest(state.model)["model_sha256"],
        "realm_count": len(state.realms),
        "owned_land": sum(
            1
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] != WILD
        ),
        "wild_land": sum(
            1
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] == WILD
        ),
        "ruins": sum(rank == "ruin" for rank in state.rank.values()),
        "minas_morgul_decision": MINAS_MORGUL_DECISION,
        "physical_alignment": physical_alignment(state),
        "realm_location_counts": {
            realm.tag: counts[realm.tag]
            for realm in state.realms
        },
        "source_sha256": hashlib.sha256(
            REALMS_CSV.read_bytes() + b"\0" + LANDMARKS_CSV.read_bytes()
        ).hexdigest(),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def scenario() -> str:
    return (
        "\ufeff"
        f"{M3_MARKER}\n"
        "me_war_of_the_ring_scenario = {\n"
        "\tcountry = GON\n"
        "\tplayer_playstyle = ADMINISTRATIVE\n"
        "\tplayer_proficiency = NOVICE\n"
        "}\n"
    )


def expected_payloads() -> dict[Path, str]:
    state = build_state()
    return {
        COUNTRY_OUT: country_definitions(state),
        SCANDINAVIA_OUT: (
            "\ufeff"
            f"{M3_MARKER}\n"
            "# M3 replaces the technical SWE gate country with Middle-earth realms.\n"
        ),
        START_COUNTRIES_OUT: start_countries(state),
        START_LOCATIONS_OUT: start_locations(state),
        COA_OUT: coa_definitions(state),
        FLAGS_OUT: flag_definitions(state),
        SCENARIO_OUT: scenario(),
        LOCALIZATION_OUT: localization(state),
        OWNERSHIP_CSV: ownership_csv(state),
        OWNERSHIP_AUDIT_CSV: ownership_audit_csv(state),
        OWNERSHIP_AUDIT_JSON: ownership_audit_json(state),
        GAZETTEER_CSV: gazetteer_csv(state),
        MANIFEST_JSON: manifest(state),
    }


def expected_binary_payloads() -> dict[Path, bytes]:
    state = build_state()
    return {
        POLITICAL_QA_OUT: political_qa_png(state),
    }


def owned_paths() -> tuple[Path, ...]:
    return (
        COUNTRY_OUT,
        SCANDINAVIA_OUT,
        START_COUNTRIES_OUT,
        START_LOCATIONS_OUT,
        COA_OUT,
        FLAGS_OUT,
        SCENARIO_OUT,
        LOCALIZATION_OUT,
        OWNERSHIP_CSV,
        OWNERSHIP_AUDIT_CSV,
        OWNERSHIP_AUDIT_JSON,
        GAZETTEER_CSV,
        MANIFEST_JSON,
        POLITICAL_QA_OUT,
    )


def write() -> None:
    payloads = expected_payloads()
    for path, text in payloads.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    for path, payload in expected_binary_payloads().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    stale_modifier = ROOT / "main_menu/common/static_modifiers/me_m3_locations.txt"
    if stale_modifier.is_file():
        stale_modifier.unlink()
    print(
        f"m3_realms: wrote {len(build_state().realms)} realms and "
        f"{len(build_state().model.locations)} gazetteer entries"
    )


def check() -> list[str]:
    failures: list[str] = []
    state = build_state()
    realms = state.realms
    if len(realms) != EXPECTED_REALM_COUNT:
        failures.append(
            f"realm roster has {len(realms)} rows, expected {EXPECTED_REALM_COUNT}"
        )
    tags = [realm.tag for realm in realms]
    if len(tags) != len(set(tags)):
        failures.append("realm roster repeats a tag")
    if any(not re.fullmatch(r"[A-Z0-9]{3}", tag) for tag in tags):
        failures.append("every realm tag must be exactly three uppercase alphanumerics")
    colors = [realm.color for realm in realms]
    if len(colors) != len(set(colors)):
        failures.append("realm map colors are not unique")
    if any(realm.style not in STYLE_PARTS for realm in realms):
        failures.append("realm roster uses an undefined naming style")
    alignment = physical_alignment(state)
    if alignment["wet_owned_control_pixels"]:
        failures.append(
            "political ownership paints "
            f"{alignment['wet_owned_control_pixels']} below-water control pixels"
        )
    if alignment["maximum_capital_snap_distance"] > 0.025:
        failures.append(
            "a realm capital snaps too far from its authored position: "
            f"{alignment['maximum_capital_snap_distance']:.6f}"
        )
    audit_rows = ownership_audit_rows(state)
    contract_violations = [
        row for row in audit_rows if row["verdict"] == "violation"
    ]
    if contract_violations:
        failures.append(
            "political claim contracts reject final locations: "
            f"{contract_violations[:5]}"
        )
    excessive_distance = [
        row
        for row in audit_rows
        if row["realm"] != WILD
        and row["realm"] not in CONTRACTED_TAGS
        and row["forced"] == "no"
        and row["distance_to_capital"]
        and float(row["distance_to_capital"]) > MAX_UNCONTRACTED_CAPITAL_DISTANCE
    ]
    if excessive_distance:
        failures.append(
            "uncontracted political claims exceed the anti-sprawl distance: "
            f"{excessive_distance[:5]}"
        )
    connectivity = realm_connectivity(state)
    fragmented_compact_realms = {
        tag: connectivity[tag]["component_detail"]
        for tag in CONTIGUOUS_CLAIM_REALMS
        if connectivity[tag]["components"] != 1
    }
    if fragmented_compact_realms:
        failures.append(
            "compact source-side realms contain detached political components: "
            f"{fragmented_compact_realms}"
        )
    for tag, (
        minimum,
        maximum,
        bbox,
        rationale,
    ) in POLITICAL_SILHOUETTE_CONTRACTS.items():
        owned = [
            location
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] == tag
        ]
        if not minimum <= len(owned) <= maximum:
            failures.append(
                f"{tag} silhouette owns {len(owned)} locations outside "
                f"reviewed range {minimum}..{maximum}: {rationale}"
            )
        x0, x1, y0, y1 = bbox
        outside = [
            location.key
            for location in owned
            if not (
                x0 <= location.normalized[0] <= x1
                and y0 <= location.normalized[1] <= y1
            )
        ]
        if outside:
            failures.append(
                f"{tag} silhouette escapes reviewed physical bbox {bbox}: "
                f"{outside[:5]} ({rationale})"
            )
    for ref, excluded_owners in FRONTIER_LANDMARK_EXCLUSIONS.items():
        location_key = state.ref_to_location.get(ref)
        if location_key is None:
            failures.append(f"political frontier landmark {ref} is unresolved")
            continue
        actual_owner = state.ownership[location_key]
        if actual_owner in excluded_owners:
            failures.append(
                f"political frontier landmark {ref} is incorrectly owned by "
                f"{actual_owner}; excluded owners are {sorted(excluded_owners)}"
            )
    unreviewed_components = {
        tag: [
            row
            for row in summary["component_detail"][1:]
            if row["disposition"] == "unreviewed"
        ]
        for tag, summary in connectivity.items()
        if any(
            row["disposition"] == "unreviewed"
            for row in summary["component_detail"][1:]
        )
    }
    if unreviewed_components:
        failures.append(
            "political components lack a physical disposition: "
            f"{unreviewed_components}"
        )
    regions = {location.region for location in state.model.locations}
    for realm in realms:
        unknown = realm.regions - regions
        if unknown:
            failures.append(f"{realm.tag} uses unknown regions: {sorted(unknown)}")
        capital = state.ref_to_location.get(realm.capital_ref)
        if capital is None:
            failures.append(f"{realm.tag} has unresolved capital {realm.capital_ref}")
        elif state.ownership.get(capital) != realm.tag:
            failures.append(f"{realm.tag} does not own its capital {capital}")
        elif state.model.by_key[capital].kind != "land":
            failures.append(f"{realm.tag} capital {capital} is not passable land")
        count = sum(value == realm.tag for value in state.ownership.values())
        if count < 1:
            failures.append(f"{realm.tag} owns no locations")
        reviewed_allowance = sum(
            target == realm.tag
            for target, _, _, _ in REVIEWED_COMPONENT_REPAIRS.values()
        )
        if (
            realm.max_locations
            and count > realm.max_locations + reviewed_allowance
        ):
            failures.append(
                f"{realm.tag} owns {count}, above allocator cap "
                f"{realm.max_locations} plus {reviewed_allowance} reviewed repairs"
            )
    if sum(value == "IRO" for value in state.ownership.values()) < 12:
        failures.append("Iron Hills lacks a viable source-side territorial cluster")
    parent = list(range(len(state.model.locations)))

    def find(value: int) -> int:
        while parent[value] != value:
            parent[value] = parent[parent[value]]
            value = parent[value]
        return value

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    labels = state.model.labels
    kind = [location.kind for location in state.model.locations]
    pairs = np.concatenate(
        (
            np.stack((labels[:, :-1].ravel(), labels[:, 1:].ravel()), axis=1),
            np.stack((labels[:-1, :].ravel(), labels[1:, :].ravel()), axis=1),
        )
    )
    for left, right in np.unique(pairs[pairs[:, 0] != pairs[:, 1]], axis=0):
        if kind[int(left)] == "land" and kind[int(right)] == "land":
            union(int(left), int(right))
    with PORTS_OUT.open("r", encoding="utf-8-sig", newline="") as handle:
        port_locations = {
            row["LandProvince"]
            for row in csv.DictReader(handle, delimiter=";")
        }
    port_components = {
        find(state.model.by_key[key].index)
        for key in port_locations
    }
    no_port_land = [
        location.key
        for location in state.model.locations
        if location.kind == "land"
        and find(location.index) not in port_components
    ]
    if no_port_land:
        sample = ", ".join(no_port_land[:20])
        failures.append(
            f"{len(no_port_land)} passable locations have no reachable port component: "
            f"{sample}"
        )
    for realm in realms:
        capital = state.ref_to_location[realm.capital_ref]
        capital_component = find(state.model.by_key[capital].index)
        if capital_component not in port_components:
            failures.append(
                f"{realm.tag} capital {capital} has no reachable port component"
            )
    missing = {
        location.key
        for location in state.model.locations
        if location.key not in state.ownership
    }
    if missing:
        failures.append(f"ownership ledger omits {len(missing)} locations")
    owned_non_land = [
        location.key
        for location in state.model.locations
        if location.kind != "land" and state.ownership[location.key] != WILD
    ]
    if owned_non_land:
        failures.append(
            f"{len(owned_non_land)} non-land locations have political owners"
        )
    bad_land = [
        location.key
        for location in state.model.locations
        if location.kind == "land"
        and state.ownership[location.key] == WILD
        and location.key not in state.wild_reason
    ]
    if bad_land:
        failures.append(f"{len(bad_land)} wild land locations lack a reason")
    pops = (ROOT / "main_menu/setup/start/06_pops.txt").read_text(
        encoding="utf-8-sig"
    )
    populated_ruins = [
        key
        for key, rank in state.rank.items()
        if rank == "ruin" and re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*\{{", pops)
    ]
    if populated_ruins:
        failures.append(f"canonical ruins retain census pops: {populated_ruins[:5]}")
    if len(state.names) != len(state.model.locations):
        failures.append("gazetteer does not cover every location")
    if len(set(state.names.values())) != len(state.names):
        failures.append("gazetteer display names are not unique")
    engineering = [
        name
        for name in state.names.values()
        if re.fullmatch(r"(?:Land|Sea|Lake|Mountain) \d+", name)
    ]
    if engineering:
        failures.append("engineering fill display names remain")
    banned = re.compile(
        r"\b(?:colonial|colony|crusade|pope|papal|catholic|protestant|"
        r"gunpowder|musket|cannon|renaissance|parliament|senate|republic|"
        r"Europe|Asia|Africa|America|French|Roman|Byzantine)\b",
        re.IGNORECASE,
    )
    visible = list(state.names.values()) + [
        value
        for realm in realms
        for value in (realm.name, realm.adjective)
    ]
    hits = [value for value in visible if banned.search(value)]
    if hits:
        failures.append(f"banned visible terms in M3 data: {hits[:5]}")
    game_dir = Path(
        json.loads(
            (ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig")
        )["game_dir"]
    )
    emblem_dir = game_dir / "game/main_menu/gfx/coat_of_arms/colored_emblems"
    for realm in realms:
        if not (emblem_dir / realm.emblem).is_file():
            failures.append(f"{realm.tag} missing vanilla COA emblem {realm.emblem}")
    for path, expected in expected_payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M3 model")
    for path, expected in expected_binary_payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M3 model")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"m3_realms: FAIL {failure}")
        return 1
    state = build_state()
    print(
        f"m3_realms: PASS ({len(state.realms)} realms, "
        f"{sum(value != WILD for value in state.ownership.values())} assigned, "
        f"{sum(value == WILD for value in state.ownership.values())} wild)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
