#!/usr/bin/env python3
"""Generate/check the M3 Middle-earth political map, gazetteer, and ruin layer."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parent))

from m2_controls import ENGINE_WATER_LEVEL_SAMPLE
from m2_runtime import sanitized_monarchy_template
from worldgen import (
    CONTROL,
    CONTROL_H,
    CONTROL_W,
    DERIVED,
    ROOT,
    Location,
    WorldModel,
    build_model,
    load_anchors,
    model_manifest,
)

REALMS_CSV = ROOT / "docs/world/realms.csv"
LANDMARKS_CSV = ROOT / "docs/world/control/m3_landmarks.csv"
OWNERSHIP_CSV = DERIVED / "m3_ownership.csv"
GAZETTEER_CSV = DERIVED / "m3_gazetteer.csv"
MANIFEST_JSON = DERIVED / "m3_manifest.json"
POLITICAL_QA_OUT = DERIVED / "m3_political_control.png"
PORTS_OUT = ROOT / "in_game/map_data/ports.csv"
COUNTRY_OUT = ROOT / "in_game/setup/countries/me_00_world.txt"
SCANDINAVIA_OUT = ROOT / "in_game/setup/countries/_scandinavia.txt"
START_COUNTRIES_OUT = ROOT / "main_menu/setup/start/10_countries.txt"
START_LOCATIONS_OUT = ROOT / "main_menu/setup/start/21_locations.txt"
COA_OUT = ROOT / "main_menu/common/coat_of_arms/coat_of_arms/me_00_realms.txt"
FLAGS_OUT = ROOT / "main_menu/common/flag_definitions/00_flag_definitions.txt"
SCENARIO_OUT = ROOT / "main_menu/common/scenarios/00_scenarios.txt"
LOCALIZATION_OUT = ROOT / "in_game/localization/english/m3_realms_l_english.yml"

WILD = "WILD"
M3_MARKER = "# Generated by tools/m3_realms.py --write."
EXPECTED_REALM_COUNT = 38
MINAS_MORGUL_DECISION = (
    "Minas Morgul is a Mordor fortress-location, not a separate country."
)


@dataclass(frozen=True)
class Realm:
    tag: str
    name: str
    adjective: str
    capital_ref: str
    x: float
    y: float
    regions: frozenset[str]
    style: str
    color: tuple[int, int, int]
    emblem: str
    max_locations: int
    source: str


@dataclass(frozen=True)
class Landmark:
    ref: str
    name: str
    x: float
    y: float
    rank: str
    source: str


@dataclass
class RealmState:
    model: WorldModel
    realms: tuple[Realm, ...]
    by_tag: dict[str, Realm]
    ref_to_location: dict[str, str]
    landmark_by_location: dict[str, Landmark]
    ownership: dict[str, str]
    wild_reason: dict[str, str]
    names: dict[str, str]
    rank: dict[str, str]
    source: dict[str, str]


# Invented fill names use phonotactic impressions and ordinary English compounds;
# they do not claim to reconstruct Tolkien's languages. The judgement is logged in
# docs/ASSUMPTIONS.md and the full output remains auditable in the gazetteer.
STYLE_PARTS: dict[str, tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]] = {
    "sindarin": (
        ("Amon", "Dol", "Eithel", "Emyn", "Imlad", "Minas", "Ost", "Taur", "Bar", "Calen", "Celon", "Nim"),
        ("adar", "ael", "annon", "bel", "born", "caran", "duin", "falas", "galen", "gond", "loth", "morn", "nen", "rath", "sarn", "thoron"),
        ("ath", "dor", "dûr", "en", "eth", "ion", "lad", "lin", "nor", "or", "ost", "rim"),
    ),
    "westron": (
        ("Alder", "Ash", "Barrow", "Beacon", "Black", "Bramble", "Buckland", "Cedar", "Deep", "East", "Green", "Grey", "Long", "North", "Oak", "South", "Stone", "West"),
        ("bank", "bourne", "bridge", "brook", "down", "field", "ford", "gate", "hall", "heath", "mere", "ridge", "stead", "water", "wood"),
        ("", " End", " Fold", " March", " Reach", " Side", " Vale", " Ward"),
    ),
    "hobbit": (
        ("Apple", "Bramble", "Brown", "Butter", "Clover", "Dimple", "Fern", "Hay", "Hazel", "Holly", "Merry", "Moss", "Nut", "Rush", "Thistle", "Willow"),
        ("bank", "bottom", "brook", "bury", "combe", "croft", "delving", "fold", "ham", "hollow", "mead", "ton", "well", "wick"),
        ("", " Green", " Hill", " Lane", " Side", " Wood"),
    ),
    "rohirric": (
        ("Ald", "Beor", "Brego", "Ceorl", "Déor", "Eorl", "Folc", "Fram", "Grim", "Helm", "Heru", "Léod", "Rid", "Thengel", "Wold"),
        ("berg", "burna", "denu", "feld", "fold", "ford", "gar", "ham", "holt", "mere", "seld", "stede", "wæd", "worth"),
        ("", " Eastmark", " Green", " March", " Westmark"),
    ),
    "khuzdul": (
        ("Azan", "Baraz", "Bizar", "Bund", "Dum", "Felek", "Gamil", "Gathol", "Gund", "Khaz", "Kheled", "Narg", "Shar", "Zigil"),
        ("abad", "aglar", "bizar", "dûm", "gathol", "inbar", "kibil", "nâla", "rakhas", "sigin", "tumun", "zirak"),
        ("", " Gate", " Halls", " Hold", " Mines", " Vault"),
    ),
    "dalish": (
        ("Amber", "Bard", "Bell", "Bow", "Celduin", "Dale", "East", "Esgar", "King", "Lake", "Long", "North", "Raven", "Red", "West"),
        ("bank", "by", "fell", "ford", "garth", "holm", "mark", "ness", "stead", "strand", "thorpe", "wick"),
        ("", " Reach", " Road", " Shore", " Vale"),
    ),
    "beorning": (
        ("Bear", "Bee", "Carrock", "Golden", "Honey", "Oak", "River", "Skin", "Stone", "Vale", "Wild", "Wood"),
        ("bank", "den", "ford", "hall", "holt", "mead", "rock", "stead", "ward", "wood"),
        ("", " Crossing", " Lodge", " Vale"),
    ),
    "entish": (
        ("Alder", "Beech", "Birch", "Bough", "Elm", "Fir", "Leaf", "Oak", "Rowan", "Root", "Willow"),
        ("bark", "bole", "bough", "deep", "dingle", "grove", "shade", "song", "well", "wood"),
        ("", " Entwood", " Long Slow Vale", " Welling"),
    ),
    "lossoth": (
        ("Cold", "Drift", "Frost", "Ice", "North", "Pale", "Seal", "Snow", "Star", "White", "Winter"),
        ("bay", "camp", "fell", "floe", "haven", "mere", "point", "shore", "water"),
        ("", " Reach", " Sound", " Waste"),
    ),
    "orkish": (
        ("Ash", "Azg", "Black", "Burz", "Dush", "Ghash", "Gor", "Grish", "Krimp", "Lug", "Mauh", "Muzg", "Nazg", "Skai", "Ugl", "Uruk"),
        ("bag", "burz", "dûr", "fang", "gash", "glob", "grat", "krak", "lug", "mauk", "nakh", "shak", "snaga", "zagh"),
        ("", " Camp", " Cleft", " Den", " Hold", " Pits"),
    ),
    "haradric": (
        ("Azr", "Bahr", "Dar", "Far", "Hadr", "Khar", "Mahr", "Nar", "Qas", "Rakh", "Sahr", "Taz", "Umr", "Zar"),
        ("abad", "ahir", "amar", "an", "ara", "asir", "em", "esh", "im", "ir", "un", "ur"),
        ("", " Gate", " Oasis", " Wells"),
    ),
    "khandish": (
        ("Arz", "Balk", "Draz", "Ghar", "Kand", "Khaz", "Khor", "Ruz", "Skarn", "Targ", "Vark", "Zand"),
        ("ak", "an", "ar", "ash", "ek", "esh", "or", "uk", "un"),
        ("", " Camp", " Ford", " Hold", " March"),
    ),
    "rhunic": (
        ("Bal", "Bor", "Gath", "Karm", "Khur", "Lod", "Nar", "Rhov", "Sag", "Shar", "Uld", "Wain", "Zor"),
        ("ach", "ad", "ar", "ath", "en", "od", "or", "un", "ur"),
        ("", " Camp", " March", " Road", " Steppe"),
    ),
}

REGION_STYLE = {
    "me_forochel_region": "lossoth",
    "me_angmar_region": "orkish",
    "me_northern_wastes_region": "lossoth",
    "me_umbar_region": "haradric",
    "me_near_harad_region": "haradric",
    "me_far_harad_region": "haradric",
    "me_rhun_region": "rhunic",
    "me_mordor_region": "orkish",
    "me_khand_region": "khandish",
    "me_belfalas_region": "sindarin",
    "me_lebennin_region": "sindarin",
    "me_ithilien_region": "sindarin",
    "me_anorien_region": "sindarin",
    "me_south_gondor_region": "sindarin",
    "me_grey_mountains_region": "khuzdul",
    "me_dale_region": "dalish",
    "me_mirkwood_region": "westron",
    "me_rohan_region": "rohirric",
    "me_anduin_vale_region": "westron",
    "me_brown_lands_region": "sindarin",
    "me_lindon_region": "sindarin",
    "me_north_arnor_region": "sindarin",
    "me_shire_breeland_region": "hobbit",
    "me_enedwaith_region": "westron",
}


def load_realms() -> tuple[Realm, ...]:
    with REALMS_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return tuple(
        Realm(
            tag=row["tag"],
            name=row["name"],
            adjective=row["adjective"],
            capital_ref=row["capital_ref"],
            x=float(row["x"]),
            y=float(row["y"]),
            regions=frozenset(row["regions"].split("|")),
            style=row["style"],
            color=tuple(int(value) for value in row["color"].split()),
            emblem=row["emblem"],
            max_locations=int(row["max_locations"]),
            source=row["source"],
        )
        for row in rows
    )


def load_landmarks() -> tuple[Landmark, ...]:
    with LANDMARKS_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return tuple(
        Landmark(
            ref=row["ref"],
            name=row["name"],
            x=float(row["x"]),
            y=float(row["y"]),
            rank=row["rank"],
            source=row["source"],
        )
        for row in rows
    )


def normalized_distance(location: Location, x: float, y: float) -> float:
    lx, ly = location.normalized
    # The 2:1 canvas makes horizontal and vertical strategic distances
    # comparable only after compressing the x term.
    return ((lx - x) * 0.72) ** 2 + (ly - y) ** 2


def resolve_landmarks(
    model: WorldModel,
) -> tuple[dict[str, str], dict[str, Landmark]]:
    anchors = load_anchors()
    land = [location for location in model.locations if location.kind == "land"]
    anchor_locations = [location for location in land if location.anchor]
    ref_to_location: dict[str, str] = {}
    reserved: set[str] = set()
    for anchor in anchors:
        location = min(
            anchor_locations,
            key=lambda item: normalized_distance(item, anchor.x, anchor.y),
        )
        ref_to_location[anchor.key] = location.key
        reserved.add(location.key)

    landmark_by_location: dict[str, Landmark] = {}
    for landmark in load_landmarks():
        if landmark.ref in ref_to_location:
            continue
        candidates = [location for location in land if location.key not in reserved]
        location = min(
            candidates,
            key=lambda item: normalized_distance(item, landmark.x, landmark.y),
        )
        ref_to_location[landmark.ref] = location.key
        landmark_by_location[location.key] = landmark
        reserved.add(location.key)
    return ref_to_location, landmark_by_location


def wilderness_reason(location: Location, protected: set[str]) -> str | None:
    if location.key in protected:
        return None
    x, y = location.normalized
    if location.region == "me_northern_wastes_region" and y < 0.155:
        return "wild_forodwaith"
    if (
        location.region == "me_enedwaith_region"
        and x < 0.39
        and 0.50 < y < 0.65
    ):
        return "wild_enedwaith"
    if (
        location.region == "me_brown_lands_region"
        and location.biome_id in {6, 8}
        and x < 0.70
    ):
        return "wild_brown_lands"
    if (
        location.region == "me_ithilien_region"
        and 0.645 < x < 0.690
        and 0.650 < y < 0.790
    ):
        return "wild_ithilien"
    return None


def assign_ownership(
    model: WorldModel,
    realms: tuple[Realm, ...],
    ref_to_location: dict[str, str],
) -> tuple[dict[str, str], dict[str, str]]:
    ownership: dict[str, str] = {}
    wild_reason: dict[str, str] = {}
    counts: Counter[str] = Counter()
    by_tag = {realm.tag: realm for realm in realms}
    forced_owner = {
        ref_to_location[realm.capital_ref]: realm.tag
        for realm in realms
    }
    if len(forced_owner) != len(realms):
        raise ValueError("two M3 realms resolve to the same capital location")
    hint_owner = {
        "Lindon": "LIN",
        "Angmar": "ANG",
        "Shire": "SHI",
        "Bree-land": "BRE",
        "Imladris": "RIV",
        "Misty Mountains": "GOB",
        "Gundabad": "GUN",
        "Moria": "MOA",
        "Beornings": "BEO",
        "Lothlórien": "LOR",
        "Dol Guldur": "DOL",
        "Woodland Realm": "WOO",
        "Lake-town": "ESG",
        "Dale": "DAL",
        "Erebor": "ERE",
        "Dorwinion": "DOR",
        "Isengard": "ISE",
        "Rohan": "ROH",
        "Gondor": "GON",
        "Mordor": "MOR",
        "Umbar": "UMB",
    }
    anchor_rank = {anchor.key: anchor.rank for anchor in load_anchors()}
    anchor_hint = {anchor.key: anchor.realm_hint for anchor in load_anchors()}
    for ref, location_key in ref_to_location.items():
        if ref not in anchor_hint or anchor_rank[ref] == "ruin":
            continue
        tag = hint_owner.get(anchor_hint[ref])
        if ref == "dol_amroth":
            tag = "DAM"
        if tag:
            forced_owner[location_key] = tag
    for key, tag in forced_owner.items():
        ownership[key] = tag
        counts[tag] += 1

    candidates_by_region: dict[str, list[Realm]] = defaultdict(list)
    for realm in realms:
        for region in realm.regions:
            candidates_by_region[region].append(realm)

    unassigned = [
        location
        for location in model.locations
        if location.kind == "land" and location.key not in ownership
    ]
    # Allocate the strongest Voronoi claims first so deliberately tiny realms
    # retain the compact heartland nearest their seat.
    scored: list[tuple[float, str, Location, list[tuple[float, Realm]]]] = []
    protected = set(forced_owner)
    for location in unassigned:
        reason = wilderness_reason(location, protected)
        if reason:
            ownership[location.key] = WILD
            wild_reason[location.key] = reason
            continue
        choices = sorted(
            (
                normalized_distance(location, realm.x, realm.y),
                realm,
            )
            for realm in candidates_by_region.get(location.region, ())
        )
        if not choices:
            ownership[location.key] = WILD
            wild_reason[location.key] = "wild_unclaimed"
            continue
        scored.append((choices[0][0], location.key, location, choices))
    for _, _, location, choices in sorted(scored):
        chosen: Realm | None = None
        for _, realm in choices:
            if realm.max_locations == 0 or counts[realm.tag] < realm.max_locations:
                chosen = realm
                break
        if chosen is None:
            ownership[location.key] = WILD
            wild_reason[location.key] = "wild_buffer"
        else:
            ownership[location.key] = chosen.tag
            counts[chosen.tag] += 1

    for location in model.locations:
        if location.kind != "land":
            ownership[location.key] = WILD
            wild_reason[location.key] = f"wild_{location.kind}"
    for tag in by_tag:
        if counts[tag] < 1:
            raise ValueError(f"{tag} owns no location")
    return ownership, wild_reason


def generated_compound(style: str, serial: int) -> str:
    first, second, third = STYLE_PARTS[style]
    base_count = len(first) * len(second) * len(third)
    base_serial = serial % base_count
    cycle = serial // base_count
    a = first[base_serial % len(first)]
    b = second[(base_serial // len(first)) % len(second)]
    c = third[(base_serial // (len(first) * len(second))) % len(third)]
    if style in {"sindarin"}:
        result = f"{a} {b}{c}"
    else:
        result = f"{a}{b}{c}"
    if cycle:
        # Productive "of X" compounds keep the generated lexicon finite-state
        # and deterministic without ever exposing engineering ordinals.
        qualifier_serial = cycle - 1
        qa = first[qualifier_serial % len(first)]
        qb = second[(qualifier_serial // len(first)) % len(second)]
        qualifier = f"{qa} {qb}" if style == "sindarin" else f"{qa}{qb}"
        result = f"{result} of {qualifier}"
    return result


def all_location_names(
    model: WorldModel,
    ownership: dict[str, str],
    by_tag: dict[str, Realm],
    landmark_by_location: dict[str, Landmark],
) -> tuple[dict[str, str], dict[str, str], dict[str, str]]:
    anchor_by_name = {anchor.name: anchor for anchor in load_anchors()}
    names: dict[str, str] = {}
    ranks: dict[str, str] = {}
    sources: dict[str, str] = {}
    used: set[str] = set()
    counters: Counter[tuple[str, str]] = Counter()
    for location in model.locations:
        if location.anchor:
            anchor = anchor_by_name[location.display_name]
            name = anchor.name
            rank = anchor.rank
            source = anchor.source
        elif location.key in landmark_by_location:
            landmark = landmark_by_location[location.key]
            name = landmark.name
            rank = landmark.rank
            source = landmark.source
        else:
            owner = ownership[location.key]
            style = (
                by_tag[owner].style
                if owner != WILD
                else REGION_STYLE[location.region]
            )
            counter_key = (style, location.kind)
            serial = counters[counter_key]
            while True:
                compound = generated_compound(style, serial)
                if location.kind == "mountain":
                    name = (
                        f"Ered {compound}"
                        if style == "sindarin"
                        else f"{compound} Heights"
                    )
                elif location.kind == "lake":
                    name = (
                        f"Nen {compound}"
                        if style == "sindarin"
                        else f"Lake {compound}"
                    )
                elif location.kind == "sea":
                    name = (
                        f"Bay of {compound}"
                        if serial % 3 == 0
                        else f"{compound} Reach"
                    )
                else:
                    name = compound
                serial += 1
                if name not in used:
                    break
            counters[counter_key] = serial
            rank = "wilderness" if owner == WILD else "place"
            source = "† M3 regional lexicon"
        if name in used:
            raise ValueError(f"duplicate M3 display name: {name}")
        used.add(name)
        names[location.key] = name
        ranks[location.key] = rank
        sources[location.key] = source
    return names, ranks, sources


@lru_cache(maxsize=1)
def build_state() -> RealmState:
    model = build_model()
    realms = load_realms()
    by_tag = {realm.tag: realm for realm in realms}
    ref_to_location, landmark_by_location = resolve_landmarks(model)
    ownership, wild_reason = assign_ownership(model, realms, ref_to_location)
    names, rank, source = all_location_names(
        model,
        ownership,
        by_tag,
        landmark_by_location,
    )
    return RealmState(
        model=model,
        realms=realms,
        by_tag=by_tag,
        ref_to_location=ref_to_location,
        landmark_by_location=landmark_by_location,
        ownership=ownership,
        wild_reason=wild_reason,
        names=names,
        rank=rank,
        source=source,
    )


def location_names(model: WorldModel | None = None) -> dict[str, str]:
    state = build_state()
    if model is not None and len(model.locations) != len(state.model.locations):
        raise ValueError("M3 naming model differs from M2 world model")
    return dict(state.names)


def physical_alignment(state: RealmState) -> dict[str, object]:
    """Prove political ownership and capitals sit on authored dry land."""
    with Image.open(CONTROL / "elevation.png") as image:
        elevation = np.asarray(image, dtype=np.uint16)
    if elevation.shape != state.model.labels.shape:
        raise ValueError(
            f"elevation shape {elevation.shape} differs from political labels "
            f"{state.model.labels.shape}"
        )
    owned_index = np.array(
        [
            state.ownership[location.key] != WILD
            for location in state.model.locations
        ],
        dtype=bool,
    )
    owned_pixels = owned_index[state.model.labels]
    wet_owned_pixels = int(
        np.count_nonzero(
            owned_pixels & (elevation <= ENGINE_WATER_LEVEL_SAMPLE)
        )
    )
    capitals: dict[str, dict[str, object]] = {}
    maximum_snap_distance = 0.0
    for realm in state.realms:
        key = state.ref_to_location[realm.capital_ref]
        location = state.model.by_key[key]
        distance = normalized_distance(location, realm.x, realm.y) ** 0.5
        maximum_snap_distance = max(maximum_snap_distance, distance)
        capitals[realm.tag] = {
            "location": key,
            "kind": location.kind,
            "normalized": [
                round(location.normalized[0], 6),
                round(location.normalized[1], 6),
            ],
            "authored": [realm.x, realm.y],
            "snap_distance": round(distance, 6),
            "raw_height": int(elevation[location.y, location.x]),
        }
    return {
        "engine_water_level_sample": ENGINE_WATER_LEVEL_SAMPLE,
        "owned_control_pixels": int(np.count_nonzero(owned_pixels)),
        "wet_owned_control_pixels": wet_owned_pixels,
        "maximum_capital_snap_distance": round(maximum_snap_distance, 6),
        "capitals": capitals,
    }


def political_qa_png(state: RealmState) -> bytes:
    """Render the exact ownership lookup over the physical control raster."""
    palette = np.zeros((len(state.model.locations), 3), dtype=np.uint8)
    for location in state.model.locations:
        owner = state.ownership[location.key]
        if owner != WILD:
            palette[location.index] = state.by_tag[owner].color
        elif location.kind == "sea":
            palette[location.index] = (20, 48, 72)
        elif location.kind == "lake":
            palette[location.index] = (30, 72, 88)
        elif location.kind == "mountain":
            palette[location.index] = (58, 56, 52)
        else:
            palette[location.index] = (118, 112, 96)
    image = Image.fromarray(palette[state.model.labels], mode="RGB")
    draw = ImageDraw.Draw(image)
    for realm in state.realms:
        location = state.model.by_key[
            state.ref_to_location[realm.capital_ref]
        ]
        x, y = location.x, location.y
        draw.rectangle((x - 2, y - 2, x + 2, y + 2), fill=(8, 8, 8))
        draw.point((x, y), fill=(255, 255, 255))
    output = io.BytesIO()
    image.save(output, format="PNG", compress_level=9)
    return output.getvalue()


def country_definitions(state: RealmState) -> str:
    lines = [
        "\ufeff" + M3_MARKER,
        "# M3 realm registry; technical culture and faith are replaced in M4.",
    ]
    for realm in state.realms:
        red, green, blue = realm.color
        lines.extend(
            (
                "",
                f"{realm.tag} = {{ # {realm.name}; {realm.source}",
                f"\tcolor = rgb {{ {red} {green} {blue} }}",
                f"\tcolor2 = rgb {{ {255-red} {255-green} {255-blue} }}",
                "\tculture_definition = swedish",
                "\treligion_definition = catholic",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def coa_definitions(state: RealmState) -> str:
    color_names = ("black", "white", "red", "green", "blue", "yellow", "purple")
    lines = [M3_MARKER, "# Script-only M3 arms; bespoke emblems replace these in M11."]
    for index, realm in enumerate(state.realms):
        primary = color_names[index % len(color_names)]
        secondary = color_names[(index + 1 + index // len(color_names)) % len(color_names)]
        if primary == secondary:
            secondary = "white" if primary != "white" else "black"
        lines.extend(
            (
                "",
                f"{realm.tag} = {{",
                '\tpattern = "pattern_solid.dds"',
                f'\tcolor1 = "{primary}"',
                f'\tcolor2 = "{secondary}"',
                '\tcolor3 = "white"',
                "\tcolored_emblem = {",
                f'\t\ttexture = "{realm.emblem}"',
                "\t\tcolor1 = color2",
                "\t\tcolor2 = color2",
                "\t\tcolor3 = color3",
                "\t\tinstance = { position = { 0.5 0.5 } scale = { 0.78 0.78 } }",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def flag_definitions(state: RealmState) -> str:
    lines = [
        "\ufeff" + M3_MARKER,
        "DEFAULT = {",
        "\tflag_definition = {",
        "\t\tcoa = GON",
        "\t\tpriority = -100",
        "\t\ttrigger = {",
        "\t\t\talways = no",
        "\t\t\thas_variable = has_had_war_of_the_roses_disaster",
        "\t\t\thas_variable = hab_imperial_flag",
        "\t\t}",
        "\t}",
        "}",
    ]
    for realm in state.realms:
        lines.extend(
            (
                f"{realm.tag} = {{",
                "\tflag_definition = {",
                f"\t\tcoa = {realm.tag}",
                "\t\tpriority = 1",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def start_countries(state: RealmState) -> str:
    discovered = sorted({location.region for location in state.model.locations})
    owned_by_tag: dict[str, list[str]] = defaultdict(list)
    for key, tag in state.ownership.items():
        if tag != WILD:
            owned_by_tag[tag].append(key)
    monarchy = sanitized_monarchy_template().splitlines()
    lines = [
        M3_MARKER,
        "current_age = age_1_traditions",
        "",
        "countries = {",
        "\tcountries = {",
    ]
    for realm in state.realms:
        owned = sorted(owned_by_tag[realm.tag])
        lines.append(f"\t\t{realm.tag} = {{ # {realm.name}")
        lines.append("\t\t\town_control_core = {")
        lines.extend(f"\t\t\t\t{key}" for key in owned)
        lines.append("\t\t\t}")
        lines.extend(f"\t\t\t{line}" if line else "" for line in monarchy)
        lines.append("\t\t\tcountry_rank = rank_county")
        lines.append("\t\t\tdiscovered_regions = {")
        lines.extend(f"\t\t\t\t{region}" for region in discovered)
        lines.append("\t\t\t}")
        lines.append(
            f"\t\t\tcapital = {state.ref_to_location[realm.capital_ref]}"
        )
        lines.extend(("\t\t}", ""))
    lines.extend(("\t}", "}", ""))
    return "\n".join(lines)


def start_locations(state: RealmState) -> str:
    ruins = sorted(
        key
        for key, rank in state.rank.items()
        if rank == "ruin"
    )
    lines = [
        M3_MARKER,
        "# Canonical ruins are deliberately wild and receive no census pop.",
        "locations = {",
    ]
    for key in ruins:
        lines.append(f"\t# ruin: {key}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def localization(state: RealmState) -> str:
    lines = ["\ufeffl_english:", " # Generated M3 realm and ruin localization."]
    for realm in state.realms:
        lines.append(f' {realm.tag}: "{realm.name}"')
        lines.append(f' {realm.tag}_ADJ: "{realm.adjective}"')
    return "\n".join(lines) + "\n"


def ownership_csv(state: RealmState) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(("location", "kind", "region", "realm", "status"))
    for location in state.model.locations:
        owner = state.ownership[location.key]
        status = (
            "owned"
            if owner != WILD
            else state.wild_reason[location.key]
        )
        writer.writerow((location.key, location.kind, location.region, owner, status))
    return output.getvalue()


def gazetteer_csv(state: RealmState) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(("location", "name", "kind", "region", "realm", "rank", "source"))
    for location in state.model.locations:
        writer.writerow(
            (
                location.key,
                state.names[location.key],
                location.kind,
                location.region,
                state.ownership[location.key],
                state.rank[location.key],
                state.source[location.key],
            )
        )
    return output.getvalue()


def manifest(state: RealmState) -> str:
    counts = Counter(state.ownership.values())
    payload = {
        "schema": 1,
        "milestone": "M3",
        "model_sha256": model_manifest(state.model)["model_sha256"],
        "realm_count": len(state.realms),
        "owned_land": sum(
            1
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] != WILD
        ),
        "wild_land": sum(
            1
            for location in state.model.locations
            if location.kind == "land" and state.ownership[location.key] == WILD
        ),
        "ruins": sum(rank == "ruin" for rank in state.rank.values()),
        "minas_morgul_decision": MINAS_MORGUL_DECISION,
        "physical_alignment": physical_alignment(state),
        "realm_location_counts": {
            realm.tag: counts[realm.tag]
            for realm in state.realms
        },
        "source_sha256": hashlib.sha256(
            REALMS_CSV.read_bytes() + b"\0" + LANDMARKS_CSV.read_bytes()
        ).hexdigest(),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def scenario() -> str:
    return (
        "\ufeff"
        f"{M3_MARKER}\n"
        "me_war_of_the_ring_scenario = {\n"
        "\tcountry = GON\n"
        "\tplayer_playstyle = ADMINISTRATIVE\n"
        "\tplayer_proficiency = NOVICE\n"
        "}\n"
    )


def expected_payloads() -> dict[Path, str]:
    state = build_state()
    return {
        COUNTRY_OUT: country_definitions(state),
        SCANDINAVIA_OUT: (
            "\ufeff"
            f"{M3_MARKER}\n"
            "# M3 replaces the technical SWE gate country with Middle-earth realms.\n"
        ),
        START_COUNTRIES_OUT: start_countries(state),
        START_LOCATIONS_OUT: start_locations(state),
        COA_OUT: coa_definitions(state),
        FLAGS_OUT: flag_definitions(state),
        SCENARIO_OUT: scenario(),
        LOCALIZATION_OUT: localization(state),
        OWNERSHIP_CSV: ownership_csv(state),
        GAZETTEER_CSV: gazetteer_csv(state),
        MANIFEST_JSON: manifest(state),
    }


def expected_binary_payloads() -> dict[Path, bytes]:
    state = build_state()
    return {
        POLITICAL_QA_OUT: political_qa_png(state),
    }


def owned_paths() -> tuple[Path, ...]:
    return (
        COUNTRY_OUT,
        SCANDINAVIA_OUT,
        START_COUNTRIES_OUT,
        START_LOCATIONS_OUT,
        COA_OUT,
        FLAGS_OUT,
        SCENARIO_OUT,
        LOCALIZATION_OUT,
        OWNERSHIP_CSV,
        GAZETTEER_CSV,
        MANIFEST_JSON,
        POLITICAL_QA_OUT,
    )


def write() -> None:
    payloads = expected_payloads()
    for path, text in payloads.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    for path, payload in expected_binary_payloads().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    stale_modifier = ROOT / "main_menu/common/static_modifiers/me_m3_locations.txt"
    if stale_modifier.is_file():
        stale_modifier.unlink()
    print(
        f"m3_realms: wrote {len(build_state().realms)} realms and "
        f"{len(build_state().model.locations)} gazetteer entries"
    )


def check() -> list[str]:
    failures: list[str] = []
    state = build_state()
    realms = state.realms
    if len(realms) != EXPECTED_REALM_COUNT:
        failures.append(
            f"realm roster has {len(realms)} rows, expected {EXPECTED_REALM_COUNT}"
        )
    tags = [realm.tag for realm in realms]
    if len(tags) != len(set(tags)):
        failures.append("realm roster repeats a tag")
    if any(not re.fullmatch(r"[A-Z0-9]{3}", tag) for tag in tags):
        failures.append("every realm tag must be exactly three uppercase alphanumerics")
    colors = [realm.color for realm in realms]
    if len(colors) != len(set(colors)):
        failures.append("realm map colors are not unique")
    if any(realm.style not in STYLE_PARTS for realm in realms):
        failures.append("realm roster uses an undefined naming style")
    alignment = physical_alignment(state)
    if alignment["wet_owned_control_pixels"]:
        failures.append(
            "political ownership paints "
            f"{alignment['wet_owned_control_pixels']} below-water control pixels"
        )
    if alignment["maximum_capital_snap_distance"] > 0.025:
        failures.append(
            "a realm capital snaps too far from its authored position: "
            f"{alignment['maximum_capital_snap_distance']:.6f}"
        )
    regions = {location.region for location in state.model.locations}
    for realm in realms:
        unknown = realm.regions - regions
        if unknown:
            failures.append(f"{realm.tag} uses unknown regions: {sorted(unknown)}")
        capital = state.ref_to_location.get(realm.capital_ref)
        if capital is None:
            failures.append(f"{realm.tag} has unresolved capital {realm.capital_ref}")
        elif state.ownership.get(capital) != realm.tag:
            failures.append(f"{realm.tag} does not own its capital {capital}")
        elif state.model.by_key[capital].kind != "land":
            failures.append(f"{realm.tag} capital {capital} is not passable land")
        count = sum(value == realm.tag for value in state.ownership.values())
        if count < 1:
            failures.append(f"{realm.tag} owns no locations")
        if realm.max_locations and count > realm.max_locations:
            failures.append(
                f"{realm.tag} owns {count}, above cap {realm.max_locations}"
            )
    parent = list(range(len(state.model.locations)))

    def find(value: int) -> int:
        while parent[value] != value:
            parent[value] = parent[parent[value]]
            value = parent[value]
        return value

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    labels = state.model.labels
    kind = [location.kind for location in state.model.locations]
    pairs = np.concatenate(
        (
            np.stack((labels[:, :-1].ravel(), labels[:, 1:].ravel()), axis=1),
            np.stack((labels[:-1, :].ravel(), labels[1:, :].ravel()), axis=1),
        )
    )
    for left, right in np.unique(pairs[pairs[:, 0] != pairs[:, 1]], axis=0):
        if kind[int(left)] == "land" and kind[int(right)] == "land":
            union(int(left), int(right))
    with PORTS_OUT.open("r", encoding="utf-8-sig", newline="") as handle:
        port_locations = {
            row["LandProvince"]
            for row in csv.DictReader(handle, delimiter=";")
        }
    port_components = {
        find(state.model.by_key[key].index)
        for key in port_locations
    }
    for realm in realms:
        capital = state.ref_to_location[realm.capital_ref]
        capital_component = find(state.model.by_key[capital].index)
        if capital_component not in port_components:
            failures.append(
                f"{realm.tag} capital {capital} has no reachable port component"
            )
    missing = {
        location.key
        for location in state.model.locations
        if location.key not in state.ownership
    }
    if missing:
        failures.append(f"ownership ledger omits {len(missing)} locations")
    owned_non_land = [
        location.key
        for location in state.model.locations
        if location.kind != "land" and state.ownership[location.key] != WILD
    ]
    if owned_non_land:
        failures.append(
            f"{len(owned_non_land)} non-land locations have political owners"
        )
    bad_land = [
        location.key
        for location in state.model.locations
        if location.kind == "land"
        and state.ownership[location.key] == WILD
        and location.key not in state.wild_reason
    ]
    if bad_land:
        failures.append(f"{len(bad_land)} wild land locations lack a reason")
    pops = (ROOT / "main_menu/setup/start/06_pops.txt").read_text(
        encoding="utf-8-sig"
    )
    populated_ruins = [
        key
        for key, rank in state.rank.items()
        if rank == "ruin" and re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*\{{", pops)
    ]
    if populated_ruins:
        failures.append(f"canonical ruins retain census pops: {populated_ruins[:5]}")
    if len(state.names) != len(state.model.locations):
        failures.append("gazetteer does not cover every location")
    if len(set(state.names.values())) != len(state.names):
        failures.append("gazetteer display names are not unique")
    engineering = [
        name
        for name in state.names.values()
        if re.fullmatch(r"(?:Land|Sea|Lake|Mountain) \d+", name)
    ]
    if engineering:
        failures.append("engineering fill display names remain")
    banned = re.compile(
        r"\b(?:colonial|colony|crusade|pope|papal|catholic|protestant|"
        r"gunpowder|musket|cannon|renaissance|parliament|senate|republic|"
        r"Europe|Asia|Africa|America|French|Roman|Byzantine)\b",
        re.IGNORECASE,
    )
    visible = list(state.names.values()) + [
        value
        for realm in realms
        for value in (realm.name, realm.adjective)
    ]
    hits = [value for value in visible if banned.search(value)]
    if hits:
        failures.append(f"banned visible terms in M3 data: {hits[:5]}")
    game_dir = Path(
        json.loads(
            (ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig")
        )["game_dir"]
    )
    emblem_dir = game_dir / "game/main_menu/gfx/coat_of_arms/colored_emblems"
    for realm in realms:
        if not (emblem_dir / realm.emblem).is_file():
            failures.append(f"{realm.tag} missing vanilla COA emblem {realm.emblem}")
    for path, expected in expected_payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M3 model")
    for path, expected in expected_binary_payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M3 model")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"m3_realms: FAIL {failure}")
        return 1
    state = build_state()
    print(
        f"m3_realms: PASS ({len(state.realms)} realms, "
        f"{sum(value != WILD for value in state.ownership.values())} assigned, "
        f"{sum(value == WILD for value in state.ownership.values())} wild)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
