#!/usr/bin/env python3
"""Generate/check the M4 Middle-earth culture, language, and faith atlas."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from m3_realms import WILD, build_state
from worldgen import ROOT, game_map

DATA = ROOT / "docs/world/peoples"
CULTURES_CSV = DATA / "cultures.csv"
FAITHS_CSV = DATA / "faiths.csv"
FAMILIES_CSV = DATA / "language_families.csv"
LANGUAGES_CSV = DATA / "languages.csv"
NAME_POOLS_JSON = DATA / "name_pools.json"
REALM_PROFILES_CSV = DATA / "realm_profiles.csv"
REGION_PROFILES_CSV = DATA / "region_profiles.csv"

COMMON = ROOT / "in_game/common"
LOCALIZATION_OUT = ROOT / "in_game/localization/english/m4_peoples_l_english.yml"
COLORS_OUT = ROOT / "main_menu/common/named_colors/me_m4_colors.txt"
ASSIGNMENTS_OUT = ROOT / "docs/world/derived/m4_people_assignments.csv"
MANIFEST_OUT = ROOT / "docs/world/derived/m4_manifest.json"

CULTURE_GROUPS_OUT = COMMON / "culture_groups/me_m4_groups.txt"
CULTURES_OUT = COMMON / "cultures/me_m4_cultures.txt"
RELIGION_GROUPS_OUT = COMMON / "religion_groups/me_m4_groups.txt"
RELIGIONS_OUT = COMMON / "religions/me_m4_faiths.txt"
LANGUAGES_OUT = COMMON / "languages/me_m4_languages.txt"

M4_MARKER = "# Generated by tools/m4_peoples.py --write."
RELIGION_ABI_MARKER = (
    "# Generated by tools/m4_peoples.py --write; M4 religion ABI overlay."
)
TERMINAL_RELIGION_DATE = "3200.1.2"
MAJOR_POOL_TARGETS = (60, 40, 30)
MINOR_POOL_TARGETS = (30, 20, 15)


@dataclass(frozen=True)
class Culture:
    key: str
    name: str
    group: str
    language: str
    color: tuple[int, int, int]
    source: str
    note: str


@dataclass(frozen=True)
class Faith:
    key: str
    name: str
    group: str
    color: tuple[int, int, int]
    source: str
    note: str


@dataclass(frozen=True)
class Family:
    semantic_key: str
    name: str
    engine_key: str
    source: str
    note: str


@dataclass(frozen=True)
class Language:
    key: str
    name: str
    semantic_family: str
    engine_family: str
    color: tuple[int, int, int]
    major: bool
    dialects: tuple[str, ...]
    source: str
    note: str


@dataclass(frozen=True)
class Profile:
    key: str
    culture: str
    faith: str
    source: str
    note: str


@dataclass(frozen=True)
class NamePools:
    male: tuple[str, ...]
    female: tuple[str, ...]
    houses: tuple[str, ...]


def _rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _color(value: str) -> tuple[int, int, int]:
    color = tuple(int(part) for part in value.split())
    if len(color) != 3 or any(part < 0 or part > 255 for part in color):
        raise ValueError(f"invalid RGB color {value!r}")
    return color


def cultures() -> tuple[Culture, ...]:
    return tuple(
        Culture(
            key=row["key"],
            name=row["name"],
            group=row["group"],
            language=row["language"],
            color=_color(row["color"]),
            source=row["source"],
            note=row["note"],
        )
        for row in _rows(CULTURES_CSV)
    )


def faiths() -> tuple[Faith, ...]:
    return tuple(
        Faith(
            key=row["key"],
            name=row["name"],
            group=row["group"],
            color=_color(row["color"]),
            source=row["source"],
            note=row["note"],
        )
        for row in _rows(FAITHS_CSV)
    )


def families() -> tuple[Family, ...]:
    return tuple(
        Family(
            semantic_key=row["semantic_key"],
            name=row["name"],
            engine_key=row["engine_key"],
            source=row["source"],
            note=row["note"],
        )
        for row in _rows(FAMILIES_CSV)
    )


def languages() -> tuple[Language, ...]:
    return tuple(
        Language(
            key=row["key"],
            name=row["name"],
            semantic_family=row["semantic_family"],
            engine_family=row["engine_family"],
            color=_color(row["color"]),
            major=row["major"].lower() == "yes",
            dialects=tuple(row["dialects"].split("|")),
            source=row["source"],
            note=row["note"],
        )
        for row in _rows(LANGUAGES_CSV)
    )


def profiles(path: Path, key_field: str) -> dict[str, Profile]:
    result: dict[str, Profile] = {}
    for row in _rows(path):
        key = row[key_field]
        if key in result:
            raise ValueError(f"duplicate profile {key} in {path}")
        result[key] = Profile(
            key=key,
            culture=row["culture"],
            faith=row["faith"],
            source=row["source"],
            note=row["note"],
        )
    return result


def realm_profiles() -> dict[str, Profile]:
    return profiles(REALM_PROFILES_CSV, "tag")


def region_profiles() -> dict[str, Profile]:
    return profiles(REGION_PROFILES_CSV, "region")


def _dedupe(values: list[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for value in values:
        value = value.strip()
        folded = value.casefold()
        if value and folded not in seen:
            result.append(value)
            seen.add(folded)
    return result


def _expand_names(
    seed: list[str],
    stems: list[str],
    endings: list[str],
    target: int,
    label: str,
) -> tuple[str, ...]:
    values = list(seed)
    values.extend(f"{stem}{ending}" for stem in stems for ending in endings)
    result = _dedupe(values)
    if len(result) < target:
        raise ValueError(f"{label} produces only {len(result)} names, needs {target}")
    return tuple(result[:target])


def name_pools() -> dict[str, NamePools]:
    raw = json.loads(NAME_POOLS_JSON.read_text(encoding="utf-8-sig"))
    language_by_key = {row.key: row for row in languages()}
    if set(raw) != set(language_by_key):
        raise ValueError("name-pool keys do not exactly match language keys")
    result: dict[str, NamePools] = {}
    for key, spec in raw.items():
        language = language_by_key[key]
        male_target, female_target, house_target = (
            MAJOR_POOL_TARGETS if language.major else MINOR_POOL_TARGETS
        )
        result[key] = NamePools(
            male=_expand_names(
                spec["male_seed"],
                spec["male_stems"],
                spec["male_endings"],
                male_target,
                f"{key} male",
            ),
            female=_expand_names(
                spec["female_seed"],
                spec["female_stems"],
                spec["female_endings"],
                female_target,
                f"{key} female",
            ),
            houses=_expand_names(
                spec["house_seed"],
                spec["house_stems"],
                spec["house_endings"],
                house_target,
                f"{key} houses",
            ),
        )
    return result


def assignments() -> dict[str, Profile]:
    state = build_state()
    realms = realm_profiles()
    regions = region_profiles()
    result: dict[str, Profile] = {}
    for location in state.model.locations:
        if location.kind != "land":
            continue
        owner = state.ownership[location.key]
        if owner != WILD:
            result[location.key] = realms[owner]
        else:
            result[location.key] = regions[location.region]
    return result


def country_profile(tag: str) -> tuple[str, str]:
    profile = realm_profiles()[tag]
    return profile.culture, profile.faith


def location_profile(location: str) -> tuple[str, str]:
    profile = assignments()[location]
    return profile.culture, profile.faith


def _name_keys(language: Language, pools: NamePools) -> dict[str, list[tuple[str, str]]]:
    prefix = re.sub(r"^me_|_language$", "", language.key)
    return {
        kind: [
            (f"me_name_{prefix}_{kind}_{index:03d}", value)
            for index, value in enumerate(values, 1)
        ]
        for kind, values in (
            ("male", pools.male),
            ("female", pools.female),
            ("house", pools.houses),
        )
    }


def culture_groups_text(rows: tuple[Culture, ...]) -> str:
    lines = [M4_MARKER, "# Race and kindred are modeled at culture-group level."]
    for group in sorted({row.group for row in rows}):
        lines.extend(("", f"{group} = {{", "}"))
    return "\n".join(lines) + "\n"


def cultures_text(rows: tuple[Culture, ...]) -> str:
    lines = [M4_MARKER, "# Middle-earth culture registry."]
    for row in rows:
        lines.extend(
            (
                "",
                f"{row.key} = {{ # {row.source}; {row.note}",
                f"\tlanguage = {row.language}",
                f"\tcolor = me_culture_color_{row.key}",
                "\ttags = { european_gfx }",
                "\tculture_groups = {",
                f"\t\t{row.group}",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def religion_groups_text(rows: tuple[Faith, ...]) -> str:
    labels = {
        "me_free_faiths": "The Light of the West",
        "me_shadow_cults": "The Shadow",
        "me_old_ways": "The Old Ways",
    }
    lines = [M4_MARKER, "# Spiritual allegiances; no Earth church hierarchy survives."]
    for index, group in enumerate(sorted({row.group for row in rows})):
        color = ((93 + index * 53) % 220, (111 + index * 37) % 220, (127 + index * 29) % 220)
        lines.extend(
            (
                "",
                f"{group} = {{ # {labels[group]}",
                f"\tcolor = rgb {{ {color[0]} {color[1]} {color[2]} }}",
                "\tconvert_slaves_at_start = no",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def religions_text(rows: tuple[Faith, ...]) -> str:
    lines = [
        M4_MARKER,
        "# Middle-earth spiritual allegiances. M10 owns aspects, offerings, and Places of Power.",
    ]
    for row in rows:
        lines.extend(
            (
                "",
                f"{row.key} = {{ # {row.source}; {row.note}",
                f"\tcolor = me_religion_color_{row.key}",
                f"\tgroup = {row.group}",
                "\tdefinition_modifier = {",
                "\t\ttolerance_own = 0.01",
                "\t}",
                "\topinions = {",
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def languages_text(rows: tuple[Language, ...], pools: dict[str, NamePools]) -> str:
    lines = [
        M4_MARKER,
        "# Installed build 24187685 requires native engine-family adapters; semantic families are localized below.",
    ]
    for row in rows:
        keys = _name_keys(row, pools[row.key])
        lines.extend(
            (
                "",
                f"{row.key} = {{ # {row.source}; {row.note}",
                f"\tcolor = me_language_color_{row.key}",
                f"\tfamily = {row.engine_family}",
                "\tfallback = english_language",
                "\tmale_names = {",
                "\t\t" + " ".join(key for key, _ in keys["male"]),
                "\t}",
                "\tfemale_names = {",
                "\t\t" + " ".join(key for key, _ in keys["female"]),
                "\t}",
                "\tdynasty_names = {",
                "\t\t" + " ".join(key for key, _ in keys["house"]),
                "\t}",
                "\tlowborn = {",
                "\t\t" + " ".join(key for key, _ in keys["house"]),
                "\t}",
                "\tdialects = {",
                *(f"\t\t{dialect} = {{ }}" for dialect in row.dialects),
                "\t}",
                "}",
            )
        )
    return "\n".join(lines) + "\n"


def colors_text(
    culture_rows: tuple[Culture, ...],
    faith_rows: tuple[Faith, ...],
    language_rows: tuple[Language, ...],
) -> str:
    lines = [M4_MARKER, "colors = {"]
    for kind, rows in (
        ("culture", culture_rows),
        ("religion", faith_rows),
        ("language", language_rows),
    ):
        for row in rows:
            red, green, blue = row.color
            lines.append(
                f"\tme_{kind}_color_{row.key} = rgb {{ {red} {green} {blue} }}"
            )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def localization_text(
    culture_rows: tuple[Culture, ...],
    faith_rows: tuple[Faith, ...],
    family_rows: tuple[Family, ...],
    language_rows: tuple[Language, ...],
    pools: dict[str, NamePools],
) -> str:
    group_names = {
        "me_dunedain_group": "Dúnedain",
        "me_northmen_group": "Northmen",
        "me_middle_men_group": "Middle Men",
        "me_southron_group": "Southrons",
        "me_easterling_group": "Easterlings",
        "me_hobbit_group": "Hobbits",
        "me_elven_group": "Elves",
        "me_dwarven_group": "Dwarves",
        "me_orc_group": "Orcs",
        "me_ent_group": "Ents",
    }
    faith_group_names = {
        "me_free_faiths": "The Light of the West",
        "me_shadow_cults": "The Shadow",
        "me_old_ways": "The Old Ways",
    }
    lines = ["\ufeffl_english:", " # Generated M4 peoples and faith localization."]
    for row in culture_rows:
        lines.append(f' {row.key}: "{_escape(row.name)}"')
        lines.append(f' {row.key}_ADJ: "{_escape(row.name)}"')
        lines.append(f' {row.key}_desc: "{_escape(row.note)}."')
    for key, name in group_names.items():
        lines.append(f' {key}: "{name}"')
        lines.append(f' {key}_ADJ: "{name}"')
        lines.append(f' {key}_desc: "{name} kindred."')
    for row in faith_rows:
        lines.append(f' {row.key}: "{_escape(row.name)}"')
        lines.append(f' {row.key}_ADJ: "{_escape(row.name)}"')
        lines.append(f' {row.key}_desc: "{_escape(row.note)}."')
    for key, name in faith_group_names.items():
        lines.append(f' {key}: "{name}"')
        lines.append(f' {key}_ADJ: "{name}"')
        lines.append(f' {key}_desc: "{name} spiritual allegiance."')
    for row in family_rows:
        lines.append(f' {row.semantic_key}: "{_escape(row.name)}"')
        lines.append(f' {row.engine_key}: "{_escape(row.name)}"')
        lines.append(f' {row.engine_key}_desc: "{_escape(row.note)}."')
    for row in language_rows:
        lines.append(f' {row.key}: "{_escape(row.name)}"')
        for dialect in row.dialects:
            label = dialect.removeprefix("me_").removesuffix("_dialect").replace("_", " ").title()
            lines.append(f' {dialect}: "{_escape(label)}"')
        for entries in _name_keys(row, pools[row.key]).values():
            lines.extend(f' {key}: "{_escape(value)}"' for key, value in entries)
    return "\n".join(lines) + "\n"


def assignment_csv() -> str:
    state = build_state()
    assigned = assignments()
    output = ["location,region,realm,culture,faith,rank,source"]
    for location in state.model.locations:
        if location.kind != "land":
            continue
        profile = assigned[location.key]
        output.append(
            ",".join(
                (
                    location.key,
                    location.region,
                    state.ownership[location.key],
                    profile.culture,
                    profile.faith,
                    state.rank[location.key],
                    '"' + profile.source.replace('"', '""') + '"',
                )
            )
        )
    return "\n".join(output) + "\n"


def _brace_delta(line: str) -> int:
    code = line.split("#", 1)[0]
    return code.count("{") - code.count("}")


def religion_abi_text(path: Path) -> str:
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    output = [
        RELIGION_ABI_MARKER,
        "# Retail symbols remain script-valid but are unavailable throughout TA 3018-3200.",
    ]
    depth = 0
    for line in lines:
        code = line.split("#", 1)[0]
        top_level_open = depth == 0 and re.match(r"^\s*[A-Za-z0-9_]+\s*=\s*\{", code)
        direct_child_enable = depth == 1 and re.match(r"^\s*enable\s*=", code)
        delta = _brace_delta(line)
        if direct_child_enable:
            depth += delta
            continue
        output.append(line)
        if top_level_open:
            output.append(
                f"\tenable = {TERMINAL_RELIGION_DATE} # total-conversion ABI guard"
            )
        depth += delta
        if depth < 0:
            raise ValueError(f"{path} closes before opening")
    if depth:
        raise ValueError(f"{path} ends at brace depth {depth}")
    return "\n".join(output) + "\n"


def religion_abi_outputs() -> dict[Path, str]:
    source_dir = game_map().parent / "common/religions"
    return {
        COMMON / "religions" / path.name: religion_abi_text(path)
        for path in sorted(source_dir.glob("*.txt"))
    }


def manifest_text() -> str:
    culture_rows = cultures()
    faith_rows = faiths()
    language_rows = languages()
    pool_rows = name_pools()
    assigned = assignments()
    state = build_state()
    source_paths = (
        CULTURES_CSV,
        FAITHS_CSV,
        FAMILIES_CSV,
        LANGUAGES_CSV,
        NAME_POOLS_JSON,
        REALM_PROFILES_CSV,
        REGION_PROFILES_CSV,
    )
    digest = hashlib.sha256()
    for path in source_paths:
        digest.update(path.read_bytes())
        digest.update(b"\0")
    payload = {
        "milestone": "M4",
        "cultures": len(culture_rows),
        "culture_groups": len({row.group for row in culture_rows}),
        "faiths": len(faith_rows),
        "faith_groups": len({row.group for row in faith_rows}),
        "languages": len(language_rows),
        "dialects": sum(len(row.dialects) for row in language_rows),
        "semantic_language_families": len(families()),
        "assigned_land_locations": len(assigned),
        "owned_land_locations": sum(
            location.kind == "land" and state.ownership[location.key] != WILD
            for location in state.model.locations
        ),
        "wild_land_locations": sum(
            location.kind == "land" and state.ownership[location.key] == WILD
            for location in state.model.locations
        ),
        "major_pool_targets": list(MAJOR_POOL_TARGETS),
        "minor_pool_targets": list(MINOR_POOL_TARGETS),
        "name_entries": sum(
            len(pool.male) + len(pool.female) + len(pool.houses)
            for pool in pool_rows.values()
        ),
        "vanilla_religion_abi_files_gated": len(religion_abi_outputs()),
        "terminal_religion_date": TERMINAL_RELIGION_DATE,
        "source_sha256": digest.hexdigest(),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def base_outputs() -> dict[Path, str]:
    culture_rows = cultures()
    faith_rows = faiths()
    family_rows = families()
    language_rows = languages()
    pools = name_pools()
    result = {
        CULTURE_GROUPS_OUT: culture_groups_text(culture_rows),
        CULTURES_OUT: cultures_text(culture_rows),
        RELIGION_GROUPS_OUT: religion_groups_text(faith_rows),
        RELIGIONS_OUT: religions_text(faith_rows),
        LANGUAGES_OUT: languages_text(language_rows, pools),
        COLORS_OUT: colors_text(culture_rows, faith_rows, language_rows),
        LOCALIZATION_OUT: localization_text(
            culture_rows, faith_rows, family_rows, language_rows, pools
        ),
        ASSIGNMENTS_OUT: assignment_csv(),
        MANIFEST_OUT: manifest_text(),
    }
    result.update(religion_abi_outputs())
    return result


def owned_paths() -> tuple[Path, ...]:
    return tuple(base_outputs())


def _installed_family_keys() -> set[str]:
    source = game_map().parent / "common/language_families"
    keys: set[str] = set()
    for path in source.glob("*.txt"):
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            match = re.match(r"^([A-Za-z0-9_]+)\s*=\s*\{", line)
            if match:
                keys.add(match.group(1))
    return keys


def validate_model() -> list[str]:
    failures: list[str] = []
    culture_rows = cultures()
    faith_rows = faiths()
    family_rows = families()
    language_rows = languages()
    realm_rows = realm_profiles()
    region_rows = region_profiles()
    state = build_state()

    for label, keys in (
        ("culture", [row.key for row in culture_rows]),
        ("faith", [row.key for row in faith_rows]),
        ("semantic family", [row.semantic_key for row in family_rows]),
        ("language", [row.key for row in language_rows]),
    ):
        if len(keys) != len(set(keys)):
            failures.append(f"duplicate {label} key")
        if any(not key.startswith("me_") for key in keys):
            failures.append(f"{label} key is not namespaced")

    all_colors = [row.color for row in (*culture_rows, *faith_rows, *language_rows)]
    if len(all_colors) != len(set(all_colors)):
        failures.append("M4 culture/faith/language colors are not globally unique")

    dialects = {
        dialect
        for language in language_rows
        for dialect in language.dialects
    }
    if len(dialects) != sum(len(row.dialects) for row in language_rows):
        failures.append("language dialect keys are not unique")
    unknown_languages = sorted(
        {row.language for row in culture_rows} - dialects
    )
    if unknown_languages:
        failures.append(f"cultures use unknown dialects: {unknown_languages}")

    installed_families = _installed_family_keys()
    semantic_by_key = {row.semantic_key: row for row in family_rows}
    for row in language_rows:
        if row.semantic_family not in semantic_by_key:
            failures.append(f"{row.key} uses unknown semantic family")
        if row.engine_family not in installed_families:
            failures.append(f"{row.key} uses unknown installed family {row.engine_family}")
        elif semantic_by_key[row.semantic_family].engine_key != row.engine_family:
            failures.append(f"{row.key} disagrees with its family adapter")

    culture_keys = {row.key for row in culture_rows}
    faith_keys = {row.key for row in faith_rows}
    if set(realm_rows) != {realm.tag for realm in state.realms}:
        failures.append("realm profiles do not exactly cover the M3 realm roster")
    regions = {location.region for location in state.model.locations}
    if set(region_rows) != regions:
        failures.append("region profiles do not exactly cover the M2 region registry")
    for profile in (*realm_rows.values(), *region_rows.values()):
        if profile.culture not in culture_keys:
            failures.append(f"{profile.key} uses unknown culture {profile.culture}")
        if profile.faith not in faith_keys:
            failures.append(f"{profile.key} uses unknown faith {profile.faith}")

    assigned = assignments()
    land = {
        location.key
        for location in state.model.locations
        if location.kind == "land"
    }
    if set(assigned) != land:
        failures.append("M4 assignment does not exactly cover passable land")
    used_cultures = {profile.culture for profile in assigned.values()}
    used_faiths = {profile.faith for profile in assigned.values()}
    if culture_keys - used_cultures != {"me_black_numenorean", "me_bree_hobbit"}:
        failures.append(
            "only the two deliberate M5 minority cultures may lack dominant locations"
        )
    if faith_keys - used_faiths:
        failures.append(f"faiths lack a dominant location: {sorted(faith_keys - used_faiths)}")

    pools = name_pools()
    for row in language_rows:
        pool = pools[row.key]
        targets = MAJOR_POOL_TARGETS if row.major else MINOR_POOL_TARGETS
        counts = (len(pool.male), len(pool.female), len(pool.houses))
        if counts != targets:
            failures.append(f"{row.key} name pool {counts} != {targets}")
    return sorted(set(failures))


def write() -> None:
    failures = validate_model()
    if failures:
        raise ValueError("\n".join(failures))
    outputs = base_outputs()
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        encoding = "utf-8" if path in {LOCALIZATION_OUT, ASSIGNMENTS_OUT, MANIFEST_OUT} else "utf-8-sig"
        path.write_text(text, encoding=encoding)
    print(
        f"m4_peoples: wrote {len(cultures())} cultures, {len(languages())} "
        f"languages, {len(faiths())} faiths, and {len(assignments())} land profiles"
    )


def check() -> list[str]:
    failures = validate_model()
    try:
        outputs = base_outputs()
    except (KeyError, ValueError, json.JSONDecodeError) as exc:
        return failures + [f"cannot render M4 outputs: {exc}"]
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
            continue
        encoding = "utf-8" if path in {LOCALIZATION_OUT, ASSIGNMENTS_OUT, MANIFEST_OUT} else "utf-8-sig"
        if path.read_text(encoding=encoding) != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M4 model")
    return sorted(set(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"m4_peoples: FAIL {failure}")
        return 1
    print(
        f"m4_peoples: PASS ({len(cultures())} cultures, {len(languages())} "
        f"languages, {len(faiths())} faiths)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
