#!/usr/bin/env python3
"""Generate/check the M5 Middle-earth census and opening economy."""

from __future__ import annotations

import argparse
import csv
import hashlib
import heapq
import io
import json
import math
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

from m3_realms import WILD, build_state
from m4_peoples import assignments, cultures, faiths
from worldgen import (
    ROOT,
    WorldModel,
    build_model,
    coastal_edges,
    effective_template_biomes,
    game_map,
)

DATA = ROOT / "docs/world/economy"
PROFILES_CSV = DATA / "population_profiles.csv"
CENSUS_CSV = DATA / "realm_census.csv"
MARKETS_CSV = DATA / "markets.csv"
ROUTES_CSV = DATA / "routes.csv"
SETTLEMENTS_CSV = DATA / "settlement_overrides.csv"

DERIVED_CENSUS = ROOT / "docs/world/derived/m5_census.csv"
MANIFEST_OUT = ROOT / "docs/world/derived/m5_manifest.json"
TOWN_SETUPS_OUT = ROOT / "in_game/common/town_setups/me_m5_setups.txt"
ROAD_TYPES_OUT = ROOT / "in_game/common/road_types/00_generic.txt"
LOCALIZATION_ROOT = ROOT / "main_menu/localization"
START_OUT = ROOT / "main_menu/setup/start"

CLIENT_LANGUAGES = (
    "english",
    "french",
    "german",
    "spanish",
    "polish",
    "russian",
    "braz_por",
    "simp_chinese",
    "japanese",
    "korean",
    "turkish",
)
POP_LOC_OUTS = {
    language: (
        LOCALIZATION_ROOT
        / language
        / f"pops_l_{language}.yml"
    )
    for language in CLIENT_LANGUAGES
}

M5_MARKER = "# Generated by tools/m5_census.py --write."
START_NAMES = (
    "03_markets.txt",
    "06_pops.txt",
    "07_cities_and_buildings.txt",
    "09_roads.txt",
    "14_development.txt",
    "24_town_rights.txt",
    "27_armies.txt",
)
POP_TYPES = (
    "nobles",
    "clergy",
    "burghers",
    "laborers",
    "soldiers",
    "peasants",
    "tribesmen",
    "slaves",
)
# Eight entries are accepted in live M4/M5 setup evidence. Compatibility-only
# culture ABI pops are placed only in robust, custom-dominant locations below.
MAX_SETUP_POP_ENTRIES = 8
# The reduced 12,104-location topology still distributes the canon census over
# enough inhabited cells that compatibility hosts need a bounded floor. A
# 750-person floor keeps every engine-required installed-culture shim
# subordinate to a robust custom majority without inflating demographics.
MIN_ABI_HOST_UNITS = 750
RAW_GOODS = frozenset(
    {
        "wheat",
        "wild_game",
        "fish",
        "fur",
        "livestock",
        "horses",
        "clay",
        "iron",
        "copper",
        "goods_gold",
        "silver",
        "stone",
        "fiber_crops",
        "lumber",
        "salt",
        "medicaments",
        "gems",
        "amber",
        "wine",
        "wool",
    }
)


@dataclass(frozen=True)
class PopulationProfile:
    key: str
    shares: tuple[float, ...]
    note: str


@dataclass(frozen=True)
class RealmCensus:
    tag: str
    total_units: int
    profile: str
    minority_culture: str
    minority_faith: str
    minority_units: int
    minority_location: str
    minority_type: str
    source: str
    note: str


@dataclass(frozen=True)
class Market:
    location: str
    name: str
    kind: str
    source: str
    note: str


@dataclass(frozen=True)
class Route:
    key: str
    name: str
    waypoints: tuple[str, ...]
    condition: str
    source: str
    note: str


@dataclass(frozen=True)
class SettlementOverride:
    location: str
    engine_rank: str
    town_setup: str
    development_bonus: int
    source: str
    note: str


@dataclass(frozen=True)
class PopEntry:
    pop_type: str
    units: int
    culture: str
    faith: str
    technical_abi: bool = False


@dataclass(frozen=True)
class CensusLocation:
    location: str
    realm: str
    custom_units: int
    entries: tuple[PopEntry, ...]


@dataclass(frozen=True)
class M5State:
    locations: dict[str, CensusLocation]
    abi_cultures: dict[str, tuple[str, ...]]
    raw_materials: dict[str, str]
    settlements: dict[str, tuple[str, str, int]]
    route_edges: tuple[tuple[str, str], ...]
    route_edge_counts: dict[str, int]


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


@lru_cache(maxsize=1)
def population_profiles() -> dict[str, PopulationProfile]:
    result: dict[str, PopulationProfile] = {}
    for row in _read_csv(PROFILES_CSV):
        shares = tuple(float(row[key]) for key in POP_TYPES)
        result[row["profile"]] = PopulationProfile(
            key=row["profile"],
            shares=shares,
            note=row["note"],
        )
    return result


@lru_cache(maxsize=1)
def realm_census() -> dict[str, RealmCensus]:
    result: dict[str, RealmCensus] = {}
    for row in _read_csv(CENSUS_CSV):
        tag = row["tag"]
        result[tag] = RealmCensus(
            tag=tag,
            total_units=round(float(row["total_k"]) * 1000),
            profile=row["profile"],
            minority_culture=row["minority_culture"],
            minority_faith=row["minority_faith"],
            minority_units=round(float(row["minority_k"] or 0) * 1000),
            minority_location=row["minority_location"],
            minority_type=row["minority_type"],
            source=row["source"],
            note=row["note"],
        )
    return result


@lru_cache(maxsize=1)
def markets() -> tuple[Market, ...]:
    return tuple(
        Market(
            location=row["location"],
            name=row["name"],
            kind=row["kind"],
            source=row["source"],
            note=row["note"],
        )
        for row in _read_csv(MARKETS_CSV)
    )


@lru_cache(maxsize=1)
def routes() -> tuple[Route, ...]:
    return tuple(
        Route(
            key=row["key"],
            name=row["name"],
            waypoints=tuple(row["waypoints"].split(";")),
            condition=row["condition"],
            source=row["source"],
            note=row["note"],
        )
        for row in _read_csv(ROUTES_CSV)
    )


@lru_cache(maxsize=1)
def settlement_overrides() -> dict[str, SettlementOverride]:
    return {
        row["location"]: SettlementOverride(
            location=row["location"],
            engine_rank=row["engine_rank"],
            town_setup=row["town_setup"],
            development_bonus=int(row["development_bonus"]),
            source=row["source"],
            note=row["note"],
        )
        for row in _read_csv(SETTLEMENTS_CSV)
    }


def _installed_cultures() -> tuple[str, ...]:
    # This private helper is the binding installed-registry parser already used
    # by the proven M4 runtime generator.
    from m2_runtime import _installed_definitions

    return tuple(_installed_definitions("cultures", exclude_inactive=True))


def _resolve_location(ref: str) -> str:
    state = build_state()
    key = state.ref_to_location.get(ref, ref)
    if key not in state.model.by_key:
        raise ValueError(f"unresolved M5 location reference {ref}")
    return key


def _nonruin_land() -> list[str]:
    state = build_state()
    return [
        location.key
        for location in state.model.locations
        if location.kind == "land" and state.rank[location.key] != "ruin"
    ]


def _abi_assignments(
    keys: list[str],
    custom_units: dict[str, int],
) -> dict[str, tuple[str, ...]]:
    cultures = _installed_cultures()
    ranked = sorted(
        keys,
        key=lambda key: (custom_units[key], key),
        reverse=True,
    )
    if len(ranked) < len(cultures):
        raise ValueError("not enough custom-dominant locations for installed culture ABI")
    hosts = ranked[: len(cultures)]
    if custom_units[hosts[-1]] < MIN_ABI_HOST_UNITS:
        raise ValueError(
            "installed culture ABI host population falls below "
            f"{MIN_ABI_HOST_UNITS / 1000:.1f}k"
        )
    result: dict[str, list[str]] = defaultdict(list)
    for culture, key in zip(cultures, hosts, strict=True):
        result[key].append(culture)
    return {key: tuple(values) for key, values in result.items()}


def _location_weight(model: WorldModel, key: str, rank: str) -> float:
    location = model.by_key[key]
    rank_weight = {
        "capital": 14.0,
        "city": 10.0,
        "town": 6.0,
        "port": 6.0,
        "fortress": 5.0,
        "hold": 5.0,
        "refuge": 4.0,
        "village": 3.0,
        "camp": 1.5,
        "landmark": 1.0,
        "place": 1.0,
        "wilderness": 0.18,
    }.get(rank, 1.0)
    density = float(model.density[location.y, location.x]) / 255.0
    biome_factor = {
        1: 1.20,
        2: 0.85,
        3: 0.65,
        4: 0.45,
        5: 0.25,
        6: 0.35,
        8: 0.20,
        9: 0.90,
        10: 0.35,
    }.get(location.biome_id, 0.75)
    area_factor = max(
        0.65,
        min(1.50, math.sqrt(float(model.areas[location.index]) / 70.0)),
    )
    return rank_weight * (0.35 + 1.65 * density) * biome_factor * area_factor


def _allocate_units(
    total_units: int,
    keys: list[str],
    weights: dict[str, float],
    minima: dict[str, int],
    preferred: str,
) -> dict[str, int]:
    minimum_total = sum(minima[key] for key in keys)
    if minimum_total > total_units:
        raise ValueError(
            f"minimum census {minimum_total / 1000:.3f} exceeds "
            f"target {total_units / 1000:.3f}"
        )
    residual = total_units - minimum_total
    weight_total = sum(weights[key] for key in keys)
    raw = {
        key: (residual * weights[key] / weight_total if weight_total else 0.0)
        for key in keys
    }
    additions = {key: int(math.floor(value)) for key, value in raw.items()}
    remainder = residual - sum(additions.values())
    order = sorted(
        keys,
        key=lambda key: (raw[key] - additions[key], key == preferred, key),
        reverse=True,
    )
    for key in order[:remainder]:
        additions[key] += 1
    return {key: minima[key] + additions[key] for key in keys}


def _split_types(units: int, profile: PopulationProfile) -> list[tuple[str, int]]:
    if units < 50:
        index = max(range(len(POP_TYPES)), key=lambda value: profile.shares[value])
        return [(POP_TYPES[index], units)]
    raw = [units * share for share in profile.shares]
    values = [int(math.floor(value)) for value in raw]
    remainder = units - sum(values)
    order = sorted(
        range(len(values)),
        key=lambda index: (raw[index] - values[index], -index),
        reverse=True,
    )
    for index in order[:remainder]:
        values[index] += 1
    return [
        (pop_type, value)
        for pop_type, value in zip(POP_TYPES, values, strict=True)
        if value
    ]


def _cap_type_split(
    values: list[tuple[str, int]],
    maximum: int,
) -> list[tuple[str, int]]:
    """Merge the smallest strata until all reserved setup slots remain available."""
    result = list(values)
    while len(result) > maximum:
        smallest = min(range(len(result)), key=lambda index: result[index][1])
        _, units = result.pop(smallest)
        largest = max(range(len(result)), key=lambda index: result[index][1])
        pop_type, current = result[largest]
        result[largest] = (pop_type, current + units)
    return result


def _base_raw_materials(model: WorldModel) -> dict[str, str]:
    coast = set(coastal_edges(model))
    dominant_biomes = effective_template_biomes(model)
    result: dict[str, str] = {}
    for location in model.locations:
        if location.kind != "land":
            continue
        token = int.from_bytes(
            hashlib.sha256(location.key.encode("utf-8")).digest()[:4],
            "little",
        )
        biome_id = int(dominant_biomes[location.index])
        biome_choices = {
            1: ("wheat", "livestock", "clay", "wool"),
            # Forests are continuous material/object fields rather than
            # location-template terrain.  The playable templates deliberately
            # remain grasslands so their borders cannot appear as Voronoi
            # patches in the close renderer; lumber's installed
            # location_potential therefore rejects these otherwise wooded
            # cells.  Keep only goods whose potential accepts the neutral
            # template until a seamless forest terrain contract is proven.
            2: ("wild_game", "wool", "medicaments"),
            3: ("wild_game", "medicaments", "wool"),
            4: ("stone", "iron", "copper", "gems"),
            5: ("fur", "wild_game", "fish"),
            6: ("medicaments", "fish", "clay"),
            8: ("iron", "stone", "salt"),
            9: ("horses", "livestock", "wool", "wheat"),
            10: ("livestock", "salt", "wool", "copper"),
        }.get(biome_id, ("wheat", "livestock", "clay"))
        good = biome_choices[token % len(biome_choices)]
        if location.index in coast and token % 4 == 0:
            good = "fish"
        if location.region == "me_rohan_region" and token % 3 == 0:
            good = "horses"
        elif location.region == "me_shire_breeland_region":
            good = ("wheat", "wool", "fiber_crops")[token % 3]
        elif location.region == "me_mordor_region":
            good = ("iron", "stone", "wheat", "livestock")[token % 4]
        elif location.region == "me_forochel_region":
            good = ("fur", "fish", "wild_game")[token % 3]
        result[location.key] = good

    state = build_state()
    special = {
        "hobbiton": "fiber_crops",
        "michel_delving": "wheat",
        "bucklebury": "wheat",
        "edoras": "horses",
        "helms_deep": "gems",
        "pelargir": "fish",
        "dol_amroth": "fish",
        "umbar": "fish",
        "erebor": "goods_gold",
        "iron_hills": "iron",
        "moria": "gems",
        "dorwinion": "wine",
        "me_land_5092": "wheat",
        state.ref_to_location["forochel_camp"]: "fur",
    }
    for ref, good in special.items():
        key = _resolve_location(ref)
        if key in result:
            result[key] = good
    return result


def _base_settlements() -> dict[str, tuple[str, str, int]]:
    people = assignments()
    political = build_state()
    result: dict[str, tuple[str, str, int]] = {}
    for key, person in people.items():
        rank = political.rank[key]
        value: tuple[str, str, int] | None = None
        if rank in {"capital", "city"}:
            value = ("city", "me_m5_city", 8)
        elif rank == "town":
            value = ("town", "me_m5_town", 4)
        elif rank == "port":
            value = ("town", "me_m5_town_port", 4)
        elif rank == "fortress":
            value = ("town", "me_m5_fortress", 4)
        elif rank == "refuge":
            value = ("town", "me_m5_refuge", 3)
        elif rank == "hold":
            setup = (
                "me_m5_dwarf_hold"
                if person.culture in {"me_longbeard", "me_firebeard_broadbeam"}
                else "me_m5_shadow_hold"
            )
            value = ("town", setup, 4)
        if value:
            result[key] = value

    for realm in political.realms:
        capital = political.ref_to_location[realm.capital_ref]
        if capital not in result:
            culture = people[capital].culture
            setup = (
                "me_m5_dwarf_hold"
                if culture in {"me_longbeard", "me_firebeard_broadbeam"}
                else "me_m5_town"
            )
            result[capital] = ("town", setup, 3)

    for market in markets():
        key = _resolve_location(market.location)
        result.setdefault(key, ("town", "me_m5_town", 3))
    for override in settlement_overrides().values():
        key = _resolve_location(override.location)
        result[key] = (
            override.engine_rank,
            override.town_setup,
            override.development_bonus,
        )
    return result


@lru_cache(maxsize=1)
def _land_graph() -> dict[int, tuple[int, ...]]:
    model = build_model()
    land = np.array(
        [location.kind == "land" for location in model.locations],
        dtype=bool,
    )
    graph: dict[int, set[int]] = defaultdict(set)
    for first, second in (
        (model.labels[:, :-1], model.labels[:, 1:]),
        (model.labels[:-1, :], model.labels[1:, :]),
    ):
        mask = first != second
        for a, b in zip(first[mask].tolist(), second[mask].tolist(), strict=True):
            a = int(a)
            b = int(b)
            if land[a] and land[b]:
                graph[a].add(b)
                graph[b].add(a)
    return {key: tuple(sorted(values)) for key, values in graph.items()}


def _shortest_land_path(start_key: str, end_key: str) -> tuple[int, ...]:
    model = build_model()
    start_key = _resolve_location(start_key)
    end_key = _resolve_location(end_key)
    start = model.by_key[start_key].index
    end = model.by_key[end_key].index
    graph = _land_graph()
    end_location = model.locations[end]

    def heuristic(index: int) -> float:
        location = model.locations[index]
        return math.hypot(
            location.x - end_location.x,
            location.y - end_location.y,
        ) / 32.0

    queue: list[tuple[float, float, int]] = [(heuristic(start), 0.0, start)]
    previous: dict[int, int] = {}
    best = {start: 0.0}
    while queue:
        _, cost, current = heapq.heappop(queue)
        if current == end:
            break
        if cost != best.get(current):
            continue
        for neighbor in graph.get(current, ()):
            biome = model.locations[neighbor].biome_id
            step = 1.0 + (0.35 if biome in {3, 5, 6, 8, 10} else 0.0)
            new_cost = cost + step
            if new_cost < best.get(neighbor, float("inf")):
                best[neighbor] = new_cost
                previous[neighbor] = current
                heapq.heappush(
                    queue,
                    (new_cost + heuristic(neighbor), new_cost, neighbor),
                )
    if end not in best:
        raise ValueError(f"no passable road path from {start_key} to {end_key}")
    path = [end]
    while path[-1] != start:
        path.append(previous[path[-1]])
    return tuple(reversed(path))


def _roads() -> tuple[tuple[tuple[str, str], ...], dict[str, int]]:
    model = build_model()
    all_edges: set[tuple[int, int]] = set()
    counts: dict[str, int] = {}
    for route in routes():
        route_edges: set[tuple[int, int]] = set()
        for start, end in zip(route.waypoints, route.waypoints[1:]):
            path = _shortest_land_path(start, end)
            for a, b in zip(path, path[1:]):
                edge = (a, b) if a < b else (b, a)
                all_edges.add(edge)
                route_edges.add(edge)
        counts[route.key] = len(route_edges)
    rendered = tuple(
        (model.locations[a].key, model.locations[b].key)
        for a, b in sorted(all_edges)
    )
    return rendered, counts


@lru_cache(maxsize=1)
def build_m5_state() -> M5State:
    political = build_state()
    people = assignments()
    profiles = population_profiles()
    targets = realm_census()
    keys = _nonruin_land()
    by_realm: dict[str, list[str]] = defaultdict(list)
    for key in keys:
        by_realm[political.ownership[key]].append(key)

    majority_units: dict[str, int] = {}
    profile_by_location: dict[str, PopulationProfile] = {}
    minority_by_location: dict[str, PopEntry] = {}
    for tag, target in targets.items():
        realm_keys = by_realm[tag]
        weights = {
            key: _location_weight(political.model, key, political.rank[key])
            for key in realm_keys
        }
        realm_majority_units = target.total_units - target.minority_units
        # A fixed five-unit floor can exceed a small realm's canonical target
        # even on the reduced 12,104-location world. Keep every non-ruin
        # location inhabited, scale the floor to local cell density, and
        # reserve at least half the census for geographic/rank weighting.
        minimum_per_location = min(
            5,
            max(
                1,
                realm_majority_units // max(1, len(realm_keys) * 2),
            ),
        )
        minima = {
            key: minimum_per_location
            for key in realm_keys
        }
        if tag == WILD:
            preferred = max(realm_keys, key=lambda key: weights[key])
        else:
            realm = political.by_tag[tag]
            preferred = political.ref_to_location[realm.capital_ref]
        allocation = _allocate_units(
            realm_majority_units,
            realm_keys,
            weights,
            minima,
            preferred,
        )
        profile = profiles[target.profile]
        for key in realm_keys:
            majority_units[key] = allocation[key]
            profile_by_location[key] = profile
        if target.minority_units:
            key = _resolve_location(target.minority_location)
            minority_by_location[key] = PopEntry(
                target.minority_type,
                target.minority_units,
                target.minority_culture,
                target.minority_faith,
            )

    custom_units = dict(majority_units)
    for key, minority in minority_by_location.items():
        custom_units[key] += minority.units
    abi = _abi_assignments(keys, custom_units)

    locations: dict[str, CensusLocation] = {}
    for key in keys:
        person = people[key]
        split = _split_types(
            majority_units[key],
            profile_by_location[key],
        )
        reserved_slots = (1 if key in abi else 0) + (
            1 if key in minority_by_location else 0
        )
        split = _cap_type_split(
            split,
            MAX_SETUP_POP_ENTRIES - reserved_slots,
        )
        entries = [
            PopEntry(pop_type, units, person.culture, person.faith)
            for pop_type, units in split
        ]
        locations[key] = CensusLocation(
            location=key,
            realm=political.ownership[key],
            custom_units=custom_units[key],
            entries=tuple(entries),
        )
        if key in minority_by_location:
            current = locations[key]
            minority = minority_by_location[key]
            locations[key] = CensusLocation(
                location=key,
                realm=current.realm,
                custom_units=current.custom_units,
                entries=current.entries + (minority,),
            )

    for key, culture_keys in abi.items():
        current = locations[key]
        technical = tuple(
            PopEntry(
                "peasants",
                10,
                culture,
                "me_valar_worship",
                technical_abi=True,
            )
            for culture in culture_keys
        )
        locations[key] = CensusLocation(
            location=key,
            realm=current.realm,
            custom_units=current.custom_units,
            entries=current.entries + technical,
        )

    route_edges, route_counts = _roads()
    return M5State(
        locations=locations,
        abi_cultures=abi,
        raw_materials=_base_raw_materials(political.model),
        settlements=_base_settlements(),
        route_edges=route_edges,
        route_edge_counts=route_counts,
    )


def raw_materials() -> dict[str, str]:
    return build_m5_state().raw_materials


def _format_units(units: int) -> str:
    return f"{units / 1000:.3f}".rstrip("0").rstrip(".")


def _pops_payload(state: M5State) -> str:
    lines = [M5_MARKER, "locations = {"]
    for key in _nonruin_land():
        location = state.locations[key]
        lines.append(f"\t{key} = {{")
        for pop in location.entries:
            suffix = " # installed culture ABI" if pop.technical_abi else ""
            lines.append(
                "\t\tdefine_pop = { "
                f"type = {pop.pop_type} size = {_format_units(pop.units)} "
                f"culture = {pop.culture} religion = {pop.faith} "
                f"}}{suffix}"
            )
        lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _markets_payload() -> str:
    lines = [M5_MARKER, "market_manager = {"]
    lines.extend(
        f"\tadd_market = {_resolve_location(market.location)}"
        for market in markets()
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _settlements_payload(state: M5State) -> str:
    lines = [M5_MARKER, "locations = {"]
    for key, (rank, setup, _) in sorted(state.settlements.items()):
        lines.append(
            f"\t{key} = {{ rank = {rank} town_setup = {setup} }}"
        )
    lines.extend(("}", "building_manager = {", "}"))
    return "\n".join(lines) + "\n"


def _roads_payload() -> str:
    # The 302 authored edges are retained and validated in the route ledger, but
    # EU5 renders a starting road only when the edge also has an Arda-native
    # strip in spline_network.splnet.  Shipping the gameplay graph without that
    # binary produces one runtime diagnostic per edge; retaining the installed
    # Earth binary would violate the custom-map contract.  Keep runtime empty
    # until a materially different spline-serialization route succeeds.
    return (
        f"{M5_MARKER}\n"
        "# Deferred: authored routes lack an Arda-native spline network.\n"
        "road_network = {\n}\n"
    )


def _development_payload(state: M5State) -> str:
    model = build_model()
    by_region: dict[str, list[float]] = defaultdict(list)
    for location in model.locations:
        if location.kind == "land":
            by_region[location.region].append(
                float(model.density[location.y, location.x])
            )
    lines = [
        M5_MARKER,
        "development = {",
        "\tbase = 0",
        "\troad = 1",
        "\tcity = 5",
        "\ttown = 2",
    ]
    for region, values in sorted(by_region.items()):
        bonus = round(float(np.mean(values)) / 255.0 * 10.0)
        lines.append(f"\t{region} = {bonus}")
    for key, (_, _, bonus) in sorted(state.settlements.items()):
        if bonus:
            lines.append(f"\t{key} = {bonus}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _armies_payload() -> str:
    political = build_state()
    targets = realm_census()
    lines = [M5_MARKER, "unit_manager = {"]
    for realm in political.realms:
        target = targets[realm.tag].total_units
        count = (
            7
            if target >= 1_000_000
            else 5
            if target >= 500_000
            else 4
            if target >= 200_000
            else 3
            if target >= 50_000
            else 2
            if target >= 10_000
            else 1
        )
        capital = political.ref_to_location[realm.capital_ref]
        lines.extend(
            (
                "\tarmy = {",
                f"\t\tcountry = {realm.tag}",
                f"\t\tlocation = {capital}",
                "\t\tsub_units = {",
            )
        )
        lines.extend(
            "\t\t\ta_footmen = { strength = 1 }"
            for _ in range(count)
        )
        lines.extend(("\t\t}", "\t\tmorale = 1", "\t}", ""))
    lines.append("}")
    return "\n".join(lines) + "\n"


def runtime_payloads() -> dict[str, str]:
    state = build_m5_state()
    return {
        "03_markets.txt": _markets_payload(),
        "06_pops.txt": _pops_payload(state),
        "07_cities_and_buildings.txt": _settlements_payload(state),
        "09_roads.txt": _roads_payload(),
        "14_development.txt": _development_payload(state),
        "24_town_rights.txt": (
            f"{M5_MARKER}\n"
            "# Middle-earth town ranks do not inherit Earth charter-right systems.\n"
            "townrights_manager = {\n}\n"
        ),
        "27_armies.txt": _armies_payload(),
    }


def _town_setup_payload() -> str:
    return f"""{M5_MARKER}
me_m5_town = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttannery = 1
}}

me_m5_town_port = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttannery = 1
}}

me_m5_city = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttools_guild = 1
\tweapon_guild = 1
\ttannery = 1
\tbrewery = 1
\tcastle = 1
}}

me_m5_city_port = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttools_guild = 1
\tweapon_guild = 1
\ttannery = 1
\tbrewery = 1
\tcastle = 1
}}

me_m5_fortress = {{
\tgranary = 1
\tmason = 1
\tweapon_guild = 1
\tcastle = 1
}}

me_m5_shadow_fortress = {{
\tgranary = 1
\tmason = 1
\tweapon_guild = 1
\tcastle = 1
}}

me_m5_refuge = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttools_guild = 1
}}

me_m5_dwarf_hold = {{
\tmarketplace = 1
\tgranary = 1
\tmason = 1
\ttools_guild = 1
\tweapon_guild = 1
\tcastle = 1
}}

me_m5_shadow_hold = {{
\tgranary = 1
\tmason = 1
\tweapon_guild = 1
\tcastle = 1
}}
"""


def _pop_localization_payload(language: str) -> str:
    return f"""l_{language}:
 nobles: "Lords & Elders"
 nobles_desc: "Hereditary houses, clan elders, and office-holding households entrusted with land, counsel, and authority."
 clergy: "Loremasters & Keepers"
 clergy_desc: "Lorekeepers, healers, memory-wardens, ritual specialists, and other custodians of a people's spiritual and learned traditions."
 burghers: "Townsfolk & Traders"
 burghers_desc: "Merchants, householders, innkeepers, and independent craftsfolk sustaining towns, havens, and long roads."
 laborers: "Craftsfolk & Laborers"
 laborers_desc: "Smiths, masons, miners, carriers, and other working households supporting workshops, delvings, and great works."
 soldiers: "Warriors & Garrisons"
 soldiers_desc: "Retainers, riders, guards, scouts, and the households that sustain standing watches and hosts."
 peasants: "Freeholders & Husbandmen"
 peasants_desc: "Farmers, herders, gardeners, and village households who keep the settled lands."
 tribesmen: "Wild Folk"
 tribesmen_desc: "Kin-based and self-governing communities of hunters, herders, forest folk, and people beyond close state control."
 slaves: "Thralls"
 slaves_desc: "People held in bondage by the Shadow, corsair powers, or warlike masters and compelled to labour or serve."
"""


def _census_ledger_payload(state: M5State) -> str:
    political = build_state()
    people = assignments()
    output = io.StringIO(newline="")
    writer = csv.DictWriter(
        output,
        fieldnames=(
            "location",
            "name",
            "region",
            "realm",
            "rank",
            "population_k",
            "culture",
            "faith",
            "minorities",
            "raw_material",
            "engine_rank",
            "abi_cultures",
        ),
        lineterminator="\n",
    )
    writer.writeheader()
    for location in political.model.locations:
        if location.kind != "land":
            continue
        person = people[location.key]
        census = state.locations.get(location.key)
        minorities = ""
        if census:
            minorities = "|".join(
                f"{entry.culture}:{_format_units(entry.units)}"
                for entry in census.entries
                if not entry.technical_abi and entry.culture != person.culture
            )
        settlement = state.settlements.get(location.key)
        writer.writerow(
            {
                "location": location.key,
                "name": political.names[location.key],
                "region": location.region,
                "realm": political.ownership[location.key],
                "rank": political.rank[location.key],
                "population_k": (
                    _format_units(census.custom_units) if census else "0"
                ),
                "culture": person.culture,
                "faith": person.faith,
                "minorities": minorities,
                "raw_material": state.raw_materials[location.key],
                "engine_rank": settlement[0] if settlement else "rural_settlement",
                "abi_cultures": "|".join(
                    state.abi_cultures.get(location.key, ())
                ),
            }
        )
    return output.getvalue()


def _source_sha256() -> str:
    digest = hashlib.sha256()
    for path in (
        PROFILES_CSV,
        CENSUS_CSV,
        MARKETS_CSV,
        ROUTES_CSV,
        SETTLEMENTS_CSV,
        ROOT / "docs/world/census_notes.md",
    ):
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def _manifest(state: M5State) -> dict[str, object]:
    targets = realm_census()
    type_units: Counter[str] = Counter()
    culture_units: Counter[str] = Counter()
    faith_units: Counter[str] = Counter()
    for location in state.locations.values():
        for entry in location.entries:
            if entry.technical_abi:
                continue
            type_units[entry.pop_type] += entry.units
            culture_units[entry.culture] += entry.units
            faith_units[entry.faith] += entry.units
    raw_counts = Counter(state.raw_materials.values())
    political = build_state()
    return {
        "milestone": "M5",
        "authored_population_k": round(
            sum(target.total_units for target in targets.values()) / 1000,
            3,
        ),
        "technical_abi_population_k": round(
            len(_installed_cultures()) * 0.01,
            3,
        ),
        "populated_locations": len(state.locations),
        "empty_ruins": sum(
            location.kind == "land"
            and political.rank[location.key] == "ruin"
            for location in political.model.locations
        ),
        "realm_targets_k": {
            key: target.total_units / 1000
            for key, target in sorted(targets.items())
        },
        "population_types_k": {
            key: round(value / 1000, 3)
            for key, value in sorted(type_units.items())
        },
        "culture_population_k": {
            key: round(value / 1000, 3)
            for key, value in sorted(culture_units.items())
        },
        "faith_population_k": {
            key: round(value / 1000, 3)
            for key, value in sorted(faith_units.items())
        },
        "markets": len(markets()),
        "urban_locations": len(state.settlements),
        "authored_route_edges": len(state.route_edges),
        "runtime_road_edges": 0,
        "route_edge_counts": state.route_edge_counts,
        "starting_armies": len(political.realms),
        "raw_material_counts": dict(sorted(raw_counts.items())),
        "source_sha256": _source_sha256(),
    }


def direct_payloads() -> dict[Path, str]:
    state = build_m5_state()
    payloads = {
        TOWN_SETUPS_OUT: _town_setup_payload(),
        DERIVED_CENSUS: _census_ledger_payload(state),
        MANIFEST_OUT: json.dumps(
            _manifest(state),
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
    }
    payloads.update(
        {
            path: _pop_localization_payload(language)
            for language, path in POP_LOC_OUTS.items()
        }
    )
    return payloads


def write() -> None:
    for path, payload in direct_payloads().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            payload,
            encoding=(
                "utf-8-sig"
                if path in {*POP_LOC_OUTS.values(), TOWN_SETUPS_OUT}
                else "utf-8"
            ),
        )
    if ROAD_TYPES_OUT.is_file():
        ROAD_TYPES_OUT.unlink()
    from m2_runtime import start_payloads

    runtime = start_payloads()
    for name in START_NAMES:
        path = START_OUT / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(runtime[path], encoding="utf-8")
    state = build_m5_state()
    print(
        "m5_census: wrote "
        f"{len(state.locations):,} populated locations, "
        f"{len(state.route_edges):,} authored route edges "
        f"(runtime deferred), and {len(markets())} markets"
    )


def _installed_building_keys() -> set[str]:
    result: set[str] = set()
    for root in (
        game_map().parent / "common/building_types",
        ROOT / "in_game/common/building_types",
    ):
        if not root.is_dir():
            continue
        for path in root.glob("*.txt"):
            result.update(
                re.findall(
                    r"(?m)^([A-Za-z0-9_]+)\s*=\s*\{",
                    path.read_text(encoding="utf-8-sig"),
                )
            )
    return result


def check() -> list[str]:
    failures: list[str] = []
    try:
        state = build_m5_state()
    except Exception as exc:
        return [f"could not build M5 state: {exc}"]

    for path, expected in direct_payloads().items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(
            encoding=(
                "utf-8-sig"
                if path in {*POP_LOC_OUTS.values(), TOWN_SETUPS_OUT}
                else "utf-8"
            )
        ) != expected:
            failures.append(f"{path.relative_to(ROOT)} differs from M5 model")
    if ROAD_TYPES_OUT.exists():
        failures.append(
            "stale M5 road-type experiment survives; installed road ABI must remain"
        )

    from m2_runtime import start_payloads

    runtime = start_payloads()
    for name in START_NAMES:
        path = START_OUT / name
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != runtime[path]:
            failures.append(f"{path.relative_to(ROOT)} differs from M5 runtime")

    profiles = population_profiles()
    for profile in profiles.values():
        if abs(sum(profile.shares) - 1.0) > 1e-9:
            failures.append(f"profile {profile.key} shares do not sum to one")
    targets = realm_census()
    political = build_state()
    expected_tags = {realm.tag for realm in political.realms} | {WILD}
    if set(targets) != expected_tags:
        failures.append("realm census is not bijective with 38 realms plus WILD")

    realm_units: Counter[str] = Counter()
    custom_cultures: set[str] = set()
    custom_faiths: set[str] = set()
    abi_entries = 0
    for key, location in state.locations.items():
        if len(location.entries) > MAX_SETUP_POP_ENTRIES:
            failures.append(
                f"{key} exceeds the installed "
                f"{MAX_SETUP_POP_ENTRIES}-pop setup contract"
            )
        if state.abi_cultures.get(key) and (
            location.custom_units < MIN_ABI_HOST_UNITS
        ):
            failures.append(
                f"{key} hosts installed culture ABI below "
                f"{MIN_ABI_HOST_UNITS / 1000:.1f}k custom population"
            )
        realm_units[location.realm] += location.custom_units
        custom_total = 0
        for entry in location.entries:
            if entry.technical_abi:
                abi_entries += 1
            else:
                custom_total += entry.units
                custom_cultures.add(entry.culture)
                custom_faiths.add(entry.faith)
        if custom_total != location.custom_units:
            failures.append(f"{key} custom pop split does not match location total")
        if state.abi_cultures.get(key) and location.custom_units <= 10:
            failures.append(f"{key} custom culture does not dominate ABI presence")
    for tag, target in targets.items():
        if realm_units[tag] != target.total_units:
            failures.append(
                f"{tag} census is {_format_units(realm_units[tag])}, "
                f"expected {_format_units(target.total_units)}"
            )
    if custom_cultures != {row.key for row in cultures()}:
        failures.append("custom census does not cover all 33 M4 cultures")
    if custom_faiths != {row.key for row in faiths()}:
        failures.append("custom census does not cover all 10 M4 faiths")
    if abi_entries != len(_installed_cultures()):
        failures.append("installed culture ABI census is incomplete")

    ruin_keys = {
        location.key
        for location in political.model.locations
        if location.kind == "land" and political.rank[location.key] == "ruin"
    }
    if ruin_keys & set(state.locations):
        failures.append("one or more canonical ruins has a starting population")
    land_keys = {
        location.key
        for location in political.model.locations
        if location.kind == "land"
    }
    if set(state.raw_materials) != land_keys:
        failures.append("raw-material map is not bijective with passable land")
    invalid_goods = set(state.raw_materials.values()) - RAW_GOODS
    if invalid_goods:
        failures.append("invalid M5 raw goods: " + ", ".join(sorted(invalid_goods)))
    invalid_lumber = [
        location.key
        for location in political.model.locations
        if state.raw_materials.get(location.key) == "lumber"
    ]
    if invalid_lumber:
        failures.append(
            "lumber assigned while all playable location templates are neutral: "
            + ", ".join(invalid_lumber[:20])
        )

    market_keys = {_resolve_location(market.location) for market in markets()}
    if len(market_keys) != len(markets()):
        failures.append("duplicate market location")
    if not market_keys <= set(state.settlements):
        failures.append("one or more market hubs lacks an urban settlement")
    wild_settlements = sorted(
        key
        for key in state.settlements
        if political.ownership.get(key, WILD) == WILD
    )
    if wild_settlements:
        failures.append(
            "urban setup assigned to deliberately wild land: "
            + ", ".join(wild_settlements[:20])
        )

    graph = _land_graph()
    by_key = political.model.by_key
    for first, second in state.route_edges:
        if by_key[second].index not in graph.get(by_key[first].index, ()):
            failures.append(f"nonadjacent road edge {first} = {second}")
            break
    if not state.route_edges:
        failures.append("authored route ledger is empty")
    if re.search(r"(?m)^\t[A-Za-z0-9_]+\s*=", _roads_payload()):
        failures.append("runtime road graph is not deferred")

    setup_text = _town_setup_payload()
    building_keys = set(
        re.findall(r"(?m)^\t([A-Za-z0-9_]+)\s*=", setup_text)
    )
    missing_buildings = building_keys - _installed_building_keys()
    if missing_buildings:
        failures.append(
            "town setups use missing buildings: "
            + ", ".join(sorted(missing_buildings))
        )
    if len(political.realms) != _armies_payload().count("\tarmy = {"):
        failures.append("starting armies are not bijective with the realm roster")

    generated = "\n".join(runtime_payloads().values()).lower()
    banned = re.findall(
        r"\b(?:cannon|firearm|musket|railroad|cathedral|university|church)\b",
        generated,
    )
    if banned:
        failures.append("anachronistic M5 generated terms: " + ", ".join(banned))
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        return 0
    failures = check()
    if failures:
        for failure in failures:
            print(f"m5_census: FAIL {failure}")
        return 1
    state = build_m5_state()
    print(
        "m5_census: PASS "
        f"({len(state.locations):,} populated, "
        f"{len(state.route_edges):,} authored route edges / 0 runtime, "
        f"{len(markets())} markets)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
